// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.stripe.PromotionCodeArgs;
import com.pulumi.stripe.Utilities;
import com.pulumi.stripe.inputs.PromotionCodeState;
import com.pulumi.stripe.outputs.PromotionCodePromotion;
import com.pulumi.stripe.outputs.PromotionCodeRestrictions;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="stripe:index/promotionCode:PromotionCode")
public class PromotionCode extends com.pulumi.resources.CustomResource {
    /**
     * Whether the promotion code is currently active.
     * 
     */
    @Export(name="active", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> active;

    /**
     * @return Whether the promotion code is currently active.
     * 
     */
    public Output<Boolean> active() {
        return this.active;
    }
    /**
     * The customer-facing code. Regardless of case, this code must be unique across all active promotion codes for a specific customer. Valid characters are lower case letters (a-z), upper case letters (A-Z), and digits (0-9). If left blank, we will generate one automatically.
     * 
     */
    @Export(name="code", refs={String.class}, tree="[0]")
    private Output<String> code;

    /**
     * @return The customer-facing code. Regardless of case, this code must be unique across all active promotion codes for a specific customer. Valid characters are lower case letters (a-z), upper case letters (A-Z), and digits (0-9). If left blank, we will generate one automatically.
     * 
     */
    public Output<String> code() {
        return this.code;
    }
    /**
     * The customer that this promotion code can be used by. If not set, the promotion code can be used by all customers.
     * 
     */
    @Export(name="customer", refs={String.class}, tree="[0]")
    private Output<String> customer;

    /**
     * @return The customer that this promotion code can be used by. If not set, the promotion code can be used by all customers.
     * 
     */
    public Output<String> customer() {
        return this.customer;
    }
    /**
     * The account that this promotion code can be used by. If not set, the promotion code can be used by all accounts.
     * 
     */
    @Export(name="customerAccount", refs={String.class}, tree="[0]")
    private Output<String> customerAccount;

    /**
     * @return The account that this promotion code can be used by. If not set, the promotion code can be used by all accounts.
     * 
     */
    public Output<String> customerAccount() {
        return this.customerAccount;
    }
    /**
     * The timestamp at which this promotion code will expire. If the coupon has specified a &lt;span pulumi-lang-nodejs=&#34;`redeemsBy`&#34; pulumi-lang-dotnet=&#34;`RedeemsBy`&#34; pulumi-lang-go=&#34;`redeemsBy`&#34; pulumi-lang-python=&#34;`redeems_by`&#34; pulumi-lang-yaml=&#34;`redeemsBy`&#34; pulumi-lang-java=&#34;`redeemsBy`&#34; pulumi-lang-hcl=&#34;`redeems_by`&#34;&gt;`redeemsBy`&lt;/span&gt;, then this value cannot be after the coupon&#39;s &lt;span pulumi-lang-nodejs=&#34;`redeemsBy`&#34; pulumi-lang-dotnet=&#34;`RedeemsBy`&#34; pulumi-lang-go=&#34;`redeemsBy`&#34; pulumi-lang-python=&#34;`redeems_by`&#34; pulumi-lang-yaml=&#34;`redeemsBy`&#34; pulumi-lang-java=&#34;`redeemsBy`&#34; pulumi-lang-hcl=&#34;`redeems_by`&#34;&gt;`redeemsBy`&lt;/span&gt;.
     * 
     */
    @Export(name="expiresAt", refs={Double.class}, tree="[0]")
    private Output<Double> expiresAt;

    /**
     * @return The timestamp at which this promotion code will expire. If the coupon has specified a &lt;span pulumi-lang-nodejs=&#34;`redeemsBy`&#34; pulumi-lang-dotnet=&#34;`RedeemsBy`&#34; pulumi-lang-go=&#34;`redeemsBy`&#34; pulumi-lang-python=&#34;`redeems_by`&#34; pulumi-lang-yaml=&#34;`redeemsBy`&#34; pulumi-lang-java=&#34;`redeemsBy`&#34; pulumi-lang-hcl=&#34;`redeems_by`&#34;&gt;`redeemsBy`&lt;/span&gt;, then this value cannot be after the coupon&#39;s &lt;span pulumi-lang-nodejs=&#34;`redeemsBy`&#34; pulumi-lang-dotnet=&#34;`RedeemsBy`&#34; pulumi-lang-go=&#34;`redeemsBy`&#34; pulumi-lang-python=&#34;`redeems_by`&#34; pulumi-lang-yaml=&#34;`redeemsBy`&#34; pulumi-lang-java=&#34;`redeemsBy`&#34; pulumi-lang-hcl=&#34;`redeems_by`&#34;&gt;`redeemsBy`&lt;/span&gt;.
     * 
     */
    public Output<Double> expiresAt() {
        return this.expiresAt;
    }
    /**
     * A positive integer specifying the number of times the promotion code can be redeemed. If the coupon has specified a &lt;span pulumi-lang-nodejs=&#34;`maxRedemptions`&#34; pulumi-lang-dotnet=&#34;`MaxRedemptions`&#34; pulumi-lang-go=&#34;`maxRedemptions`&#34; pulumi-lang-python=&#34;`max_redemptions`&#34; pulumi-lang-yaml=&#34;`maxRedemptions`&#34; pulumi-lang-java=&#34;`maxRedemptions`&#34; pulumi-lang-hcl=&#34;`max_redemptions`&#34;&gt;`maxRedemptions`&lt;/span&gt;, then this value cannot be greater than the coupon&#39;s &lt;span pulumi-lang-nodejs=&#34;`maxRedemptions`&#34; pulumi-lang-dotnet=&#34;`MaxRedemptions`&#34; pulumi-lang-go=&#34;`maxRedemptions`&#34; pulumi-lang-python=&#34;`max_redemptions`&#34; pulumi-lang-yaml=&#34;`maxRedemptions`&#34; pulumi-lang-java=&#34;`maxRedemptions`&#34; pulumi-lang-hcl=&#34;`max_redemptions`&#34;&gt;`maxRedemptions`&lt;/span&gt;.
     * 
     */
    @Export(name="maxRedemptions", refs={Double.class}, tree="[0]")
    private Output<Double> maxRedemptions;

    /**
     * @return A positive integer specifying the number of times the promotion code can be redeemed. If the coupon has specified a &lt;span pulumi-lang-nodejs=&#34;`maxRedemptions`&#34; pulumi-lang-dotnet=&#34;`MaxRedemptions`&#34; pulumi-lang-go=&#34;`maxRedemptions`&#34; pulumi-lang-python=&#34;`max_redemptions`&#34; pulumi-lang-yaml=&#34;`maxRedemptions`&#34; pulumi-lang-java=&#34;`maxRedemptions`&#34; pulumi-lang-hcl=&#34;`max_redemptions`&#34;&gt;`maxRedemptions`&lt;/span&gt;, then this value cannot be greater than the coupon&#39;s &lt;span pulumi-lang-nodejs=&#34;`maxRedemptions`&#34; pulumi-lang-dotnet=&#34;`MaxRedemptions`&#34; pulumi-lang-go=&#34;`maxRedemptions`&#34; pulumi-lang-python=&#34;`max_redemptions`&#34; pulumi-lang-yaml=&#34;`maxRedemptions`&#34; pulumi-lang-java=&#34;`maxRedemptions`&#34; pulumi-lang-hcl=&#34;`max_redemptions`&#34;&gt;`maxRedemptions`&lt;/span&gt;.
     * 
     */
    public Output<Double> maxRedemptions() {
        return this.maxRedemptions;
    }
    /**
     * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to &lt;span pulumi-lang-nodejs=&#34;`metadata`&#34; pulumi-lang-dotnet=&#34;`Metadata`&#34; pulumi-lang-go=&#34;`metadata`&#34; pulumi-lang-python=&#34;`metadata`&#34; pulumi-lang-yaml=&#34;`metadata`&#34; pulumi-lang-java=&#34;`metadata`&#34; pulumi-lang-hcl=&#34;`metadata`&#34;&gt;`metadata`&lt;/span&gt;.
     * 
     */
    @Export(name="metadata", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output<Map<String,String>> metadata;

    /**
     * @return Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to &lt;span pulumi-lang-nodejs=&#34;`metadata`&#34; pulumi-lang-dotnet=&#34;`Metadata`&#34; pulumi-lang-go=&#34;`metadata`&#34; pulumi-lang-python=&#34;`metadata`&#34; pulumi-lang-yaml=&#34;`metadata`&#34; pulumi-lang-java=&#34;`metadata`&#34; pulumi-lang-hcl=&#34;`metadata`&#34;&gt;`metadata`&lt;/span&gt;.
     * 
     */
    public Output<Map<String,String>> metadata() {
        return this.metadata;
    }
    /**
     * The promotion referenced by this promotion code.
     * 
     */
    @Export(name="promotion", refs={PromotionCodePromotion.class}, tree="[0]")
    private Output<PromotionCodePromotion> promotion;

    /**
     * @return The promotion referenced by this promotion code.
     * 
     */
    public Output<PromotionCodePromotion> promotion() {
        return this.promotion;
    }
    /**
     * Settings that restrict the redemption of the promotion code.
     * 
     */
    @Export(name="restrictions", refs={PromotionCodeRestrictions.class}, tree="[0]")
    private Output</* @Nullable */ PromotionCodeRestrictions> restrictions;

    /**
     * @return Settings that restrict the redemption of the promotion code.
     * 
     */
    public Output<Optional<PromotionCodeRestrictions>> restrictions() {
        return Codegen.optional(this.restrictions);
    }
    /**
     * Number of times this promotion code has been used.
     * 
     */
    @Export(name="timesRedeemed", refs={Double.class}, tree="[0]")
    private Output<Double> timesRedeemed;

    /**
     * @return Number of times this promotion code has been used.
     * 
     */
    public Output<Double> timesRedeemed() {
        return this.timesRedeemed;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public PromotionCode(java.lang.String name) {
        this(name, PromotionCodeArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public PromotionCode(java.lang.String name, PromotionCodeArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public PromotionCode(java.lang.String name, PromotionCodeArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("stripe:index/promotionCode:PromotionCode", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private PromotionCode(java.lang.String name, Output<java.lang.String> id, @Nullable PromotionCodeState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("stripe:index/promotionCode:PromotionCode", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static PromotionCodeArgs makeArgs(PromotionCodeArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? PromotionCodeArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static PromotionCode get(java.lang.String name, Output<java.lang.String> id, @Nullable PromotionCodeState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new PromotionCode(name, id, state, options);
    }
}
