// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class BillingPortalConfigurationFeaturesSubscriptionUpdateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determines the value to use for the billing cycle anchor on subscription updates. Valid values are &lt;span pulumi-lang-nodejs="`now`" pulumi-lang-dotnet="`Now`" pulumi-lang-go="`now`" pulumi-lang-python="`now`" pulumi-lang-yaml="`now`" pulumi-lang-java="`now`" pulumi-lang-hcl="`now`"&gt;`now`&lt;/span&gt; or &lt;span pulumi-lang-nodejs="`unchanged`" pulumi-lang-dotnet="`Unchanged`" pulumi-lang-go="`unchanged`" pulumi-lang-python="`unchanged`" pulumi-lang-yaml="`unchanged`" pulumi-lang-java="`unchanged`" pulumi-lang-hcl="`unchanged`"&gt;`unchanged`&lt;/span&gt;, and the default value is &lt;span pulumi-lang-nodejs="`unchanged`" pulumi-lang-dotnet="`Unchanged`" pulumi-lang-go="`unchanged`" pulumi-lang-python="`unchanged`" pulumi-lang-yaml="`unchanged`" pulumi-lang-java="`unchanged`" pulumi-lang-hcl="`unchanged`"&gt;`unchanged`&lt;/span&gt;. Setting the value to &lt;span pulumi-lang-nodejs="`now`" pulumi-lang-dotnet="`Now`" pulumi-lang-go="`now`" pulumi-lang-python="`now`" pulumi-lang-yaml="`now`" pulumi-lang-java="`now`" pulumi-lang-hcl="`now`"&gt;`now`&lt;/span&gt; resets the subscription's billing cycle anchor to the current time (in UTC). For more information, see the billing cycle [documentation](https://docs.stripe.com/billing/subscriptions/billing-cycle).
        /// </summary>
        [Input("billingCycleAnchor")]
        public Input<string>? BillingCycleAnchor { get; set; }

        [Input("defaultAllowedUpdates")]
        private InputList<string>? _defaultAllowedUpdates;

        /// <summary>
        /// The types of subscription updates that are supported for items listed in the &lt;span pulumi-lang-nodejs="`products`" pulumi-lang-dotnet="`Products`" pulumi-lang-go="`products`" pulumi-lang-python="`products`" pulumi-lang-yaml="`products`" pulumi-lang-java="`products`" pulumi-lang-hcl="`products`"&gt;`products`&lt;/span&gt; attribute. When empty, subscriptions are not updateable.
        /// </summary>
        public InputList<string> DefaultAllowedUpdates
        {
            get => _defaultAllowedUpdates ?? (_defaultAllowedUpdates = new InputList<string>());
            set => _defaultAllowedUpdates = value;
        }

        /// <summary>
        /// Whether the feature is enabled.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        [Input("products")]
        private InputList<Inputs.BillingPortalConfigurationFeaturesSubscriptionUpdateProductArgs>? _products;

        /// <summary>
        /// The list of up to 10 products that support subscription updates.
        /// </summary>
        public InputList<Inputs.BillingPortalConfigurationFeaturesSubscriptionUpdateProductArgs> Products
        {
            get => _products ?? (_products = new InputList<Inputs.BillingPortalConfigurationFeaturesSubscriptionUpdateProductArgs>());
            set => _products = value;
        }

        /// <summary>
        /// Determines how to handle prorations resulting from subscription updates. Valid values are &lt;span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`"&gt;`none`&lt;/span&gt;, &lt;span pulumi-lang-nodejs="`createProrations`" pulumi-lang-dotnet="`CreateProrations`" pulumi-lang-go="`createProrations`" pulumi-lang-python="`create_prorations`" pulumi-lang-yaml="`createProrations`" pulumi-lang-java="`createProrations`" pulumi-lang-hcl="`create_prorations`"&gt;`createProrations`&lt;/span&gt;, and &lt;span pulumi-lang-nodejs="`alwaysInvoice`" pulumi-lang-dotnet="`AlwaysInvoice`" pulumi-lang-go="`alwaysInvoice`" pulumi-lang-python="`always_invoice`" pulumi-lang-yaml="`alwaysInvoice`" pulumi-lang-java="`alwaysInvoice`" pulumi-lang-hcl="`always_invoice`"&gt;`alwaysInvoice`&lt;/span&gt;. Defaults to a value of &lt;span pulumi-lang-nodejs="`none`" pulumi-lang-dotnet="`None`" pulumi-lang-go="`none`" pulumi-lang-python="`none`" pulumi-lang-yaml="`none`" pulumi-lang-java="`none`" pulumi-lang-hcl="`none`"&gt;`none`&lt;/span&gt; if you don't set it during creation.
        /// </summary>
        [Input("prorationBehavior")]
        public Input<string>? ProrationBehavior { get; set; }

        [Input("scheduleAtPeriodEnd")]
        public Input<Inputs.BillingPortalConfigurationFeaturesSubscriptionUpdateScheduleAtPeriodEndArgs>? ScheduleAtPeriodEnd { get; set; }

        /// <summary>
        /// Determines how handle updates to trialing subscriptions. Valid values are &lt;span pulumi-lang-nodejs="`endTrial`" pulumi-lang-dotnet="`EndTrial`" pulumi-lang-go="`endTrial`" pulumi-lang-python="`end_trial`" pulumi-lang-yaml="`endTrial`" pulumi-lang-java="`endTrial`" pulumi-lang-hcl="`end_trial`"&gt;`endTrial`&lt;/span&gt; and &lt;span pulumi-lang-nodejs="`continueTrial`" pulumi-lang-dotnet="`ContinueTrial`" pulumi-lang-go="`continueTrial`" pulumi-lang-python="`continue_trial`" pulumi-lang-yaml="`continueTrial`" pulumi-lang-java="`continueTrial`" pulumi-lang-hcl="`continue_trial`"&gt;`continueTrial`&lt;/span&gt;. Defaults to a value of &lt;span pulumi-lang-nodejs="`endTrial`" pulumi-lang-dotnet="`EndTrial`" pulumi-lang-go="`endTrial`" pulumi-lang-python="`end_trial`" pulumi-lang-yaml="`endTrial`" pulumi-lang-java="`endTrial`" pulumi-lang-hcl="`end_trial`"&gt;`endTrial`&lt;/span&gt; if you don't set it during creation.
        /// </summary>
        [Input("trialUpdateBehavior")]
        public Input<string>? TrialUpdateBehavior { get; set; }

        public BillingPortalConfigurationFeaturesSubscriptionUpdateArgs()
        {
        }
        public static new BillingPortalConfigurationFeaturesSubscriptionUpdateArgs Empty => new BillingPortalConfigurationFeaturesSubscriptionUpdateArgs();
    }
}
