// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class BillingPortalConfigurationFeaturesPaymentMethodUpdateGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the feature is enabled.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// The [Payment Method Configuration](https://www.terraform.io/api/payment_method_configurations) to use for this portal session. When specified, customers will be able to update their payment method to one of the options specified by the payment method configuration. If not set, the default payment method configuration is used.
        /// </summary>
        [Input("paymentMethodConfiguration")]
        public Input<string>? PaymentMethodConfiguration { get; set; }

        public BillingPortalConfigurationFeaturesPaymentMethodUpdateGetArgs()
        {
        }
        public static new BillingPortalConfigurationFeaturesPaymentMethodUpdateGetArgs Empty => new BillingPortalConfigurationFeaturesPaymentMethodUpdateGetArgs();
    }
}
