// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class ChargePaymentMethodDetailsBlikArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A unique and immutable identifier assigned by BLIK to every buyer.
        /// </summary>
        [Input("buyerId")]
        public Input<string>? BuyerId { get; set; }

        public ChargePaymentMethodDetailsBlikArgs()
        {
        }
        public static new ChargePaymentMethodDetailsBlikArgs Empty => new ChargePaymentMethodDetailsBlikArgs();
    }
}
