// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class ChargePaymentMethodDetailsKlarnaPayerDetailsAddressGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The payer address country
        /// </summary>
        [Input("country")]
        public Input<string>? Country { get; set; }

        public ChargePaymentMethodDetailsKlarnaPayerDetailsAddressGetArgs()
        {
        }
        public static new ChargePaymentMethodDetailsKlarnaPayerDetailsAddressGetArgs Empty => new ChargePaymentMethodDetailsKlarnaPayerDetailsAddressGetArgs();
    }
}
