// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class ChargePaymentMethodDetailsPaytoGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Bank-State-Branch number of the bank account.
        /// </summary>
        [Input("bsbNumber")]
        public Input<string>? BsbNumber { get; set; }

        /// <summary>
        /// Last four digits of the bank account number.
        /// </summary>
        [Input("last4")]
        public Input<string>? Last4 { get; set; }

        /// <summary>
        /// ID of the mandate used to make this payment.
        /// </summary>
        [Input("mandate")]
        public Input<string>? Mandate { get; set; }

        /// <summary>
        /// The PayID alias for the bank account.
        /// </summary>
        [Input("payId")]
        public Input<string>? PayId { get; set; }

        public ChargePaymentMethodDetailsPaytoGetArgs()
        {
        }
        public static new ChargePaymentMethodDetailsPaytoGetArgs Empty => new ChargePaymentMethodDetailsPaytoGetArgs();
    }
}
