// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class PaymentMethodCardGeneratedFromPaymentMethodDetailsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("cardPresent")]
        public Input<Inputs.PaymentMethodCardGeneratedFromPaymentMethodDetailsCardPresentGetArgs>? CardPresent { get; set; }

        /// <summary>
        /// The type of payment method transaction-specific details from the transaction that generated this &lt;span pulumi-lang-nodejs="`card`" pulumi-lang-dotnet="`Card`" pulumi-lang-go="`card`" pulumi-lang-python="`card`" pulumi-lang-yaml="`card`" pulumi-lang-java="`card`" pulumi-lang-hcl="`card`"&gt;`card`&lt;/span&gt; payment method. Always &lt;span pulumi-lang-nodejs="`cardPresent`" pulumi-lang-dotnet="`CardPresent`" pulumi-lang-go="`cardPresent`" pulumi-lang-python="`card_present`" pulumi-lang-yaml="`cardPresent`" pulumi-lang-java="`cardPresent`" pulumi-lang-hcl="`card_present`"&gt;`cardPresent`&lt;/span&gt;.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public PaymentMethodCardGeneratedFromPaymentMethodDetailsGetArgs()
        {
        }
        public static new PaymentMethodCardGeneratedFromPaymentMethodDetailsGetArgs Empty => new PaymentMethodCardGeneratedFromPaymentMethodDetailsGetArgs();
    }
}
