// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class PaymentMethodP24Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The customer's bank, if provided.
        /// </summary>
        [Input("bank")]
        public Input<string>? Bank { get; set; }

        public PaymentMethodP24Args()
        {
        }
        public static new PaymentMethodP24Args Empty => new PaymentMethodP24Args();
    }
}
