// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class PaymentMethodDomainApplePayStatusDetailsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The error message associated with the status of the payment method on the domain.
        /// </summary>
        [Input("errorMessage")]
        public Input<string>? ErrorMessage { get; set; }

        public PaymentMethodDomainApplePayStatusDetailsGetArgs()
        {
        }
        public static new PaymentMethodDomainApplePayStatusDetailsGetArgs Empty => new PaymentMethodDomainApplePayStatusDetailsGetArgs();
    }
}
