// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class PaymentLinkAutomaticTaxArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If &lt;span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`"&gt;`true`&lt;/span&gt;, tax will be calculated automatically using the customer's location.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// The account that's liable for tax. If set, the business address and tax registrations required to perform the tax calculation are loaded from this account. The tax transaction is returned in the report of the connected account.
        /// </summary>
        [Input("liability")]
        public Input<Inputs.PaymentLinkAutomaticTaxLiabilityArgs>? Liability { get; set; }

        public PaymentLinkAutomaticTaxArgs()
        {
        }
        public static new PaymentLinkAutomaticTaxArgs Empty => new PaymentLinkAutomaticTaxArgs();
    }
}
