// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class PaymentIntentManagedPaymentsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Set to &lt;span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`"&gt;`true`&lt;/span&gt; to enable [Managed Payments](https://docs.stripe.com/payments/managed-payments), Stripe's merchant of record solution, for this session.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        public PaymentIntentManagedPaymentsArgs()
        {
        }
        public static new PaymentIntentManagedPaymentsArgs Empty => new PaymentIntentManagedPaymentsArgs();
    }
}
