// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class PaymentMethodDomainKlarnaGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The status of the payment method on the domain.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Contains additional details about the status of a payment method for a specific payment method domain.
        /// </summary>
        [Input("statusDetails")]
        public Input<Inputs.PaymentMethodDomainKlarnaStatusDetailsGetArgs>? StatusDetails { get; set; }

        public PaymentMethodDomainKlarnaGetArgs()
        {
        }
        public static new PaymentMethodDomainKlarnaGetArgs Empty => new PaymentMethodDomainKlarnaGetArgs();
    }
}
