// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class SourceMandateAcceptanceOnlineArgs : global::Pulumi.ResourceArgs
    {
        [Input("date")]
        private Input<double>? _date;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// The Unix timestamp (in seconds) when the mandate was accepted or refused by the customer.
        /// </summary>
        public Input<double>? Date
        {
            get => _date;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _date = Output.Tuple<Input<double>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("ip")]
        private Input<string>? _ip;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// The IP address from which the mandate was accepted or refused by the customer.
        /// </summary>
        public Input<string>? Ip
        {
            get => _ip;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _ip = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("userAgent")]
        private Input<string>? _userAgent;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// The user agent of the browser from which the mandate was accepted or refused by the customer.
        /// </summary>
        public Input<string>? UserAgent
        {
            get => _userAgent;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _userAgent = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public SourceMandateAcceptanceOnlineArgs()
        {
        }
        public static new SourceMandateAcceptanceOnlineArgs Empty => new SourceMandateAcceptanceOnlineArgs();
    }
}
