// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class SubscriptionSchedulePhaseAddInvoiceItemGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Controls whether discounts apply to this invoice item. Defaults to true if no value is provided.
        /// </summary>
        [Input("discountable")]
        public Input<bool>? Discountable { get; set; }

        [Input("discounts")]
        private InputList<Inputs.SubscriptionSchedulePhaseAddInvoiceItemDiscountGetArgs>? _discounts;

        /// <summary>
        /// The stackable discounts that will be applied to the item.
        /// </summary>
        public InputList<Inputs.SubscriptionSchedulePhaseAddInvoiceItemDiscountGetArgs> Discounts
        {
            get => _discounts ?? (_discounts = new InputList<Inputs.SubscriptionSchedulePhaseAddInvoiceItemDiscountGetArgs>());
            set => _discounts = value;
        }

        [Input("metadata")]
        private InputMap<string>? _metadata;

        /// <summary>
        /// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        /// </summary>
        public InputMap<string> Metadata
        {
            get => _metadata ?? (_metadata = new InputMap<string>());
            set => _metadata = value;
        }

        [Input("period")]
        public Input<Inputs.SubscriptionSchedulePhaseAddInvoiceItemPeriodGetArgs>? Period { get; set; }

        /// <summary>
        /// ID of the price used to generate the invoice item.
        /// </summary>
        [Input("price")]
        public Input<string>? Price { get; set; }

        /// <summary>
        /// Data used to generate a new [Price](https://docs.stripe.com/api/prices) object inline. One of &lt;span pulumi-lang-nodejs="`price`" pulumi-lang-dotnet="`Price`" pulumi-lang-go="`price`" pulumi-lang-python="`price`" pulumi-lang-yaml="`price`" pulumi-lang-java="`price`" pulumi-lang-hcl="`price`"&gt;`price`&lt;/span&gt; or &lt;span pulumi-lang-nodejs="`priceData`" pulumi-lang-dotnet="`PriceData`" pulumi-lang-go="`priceData`" pulumi-lang-python="`price_data`" pulumi-lang-yaml="`priceData`" pulumi-lang-java="`priceData`" pulumi-lang-hcl="`price_data`"&gt;`priceData`&lt;/span&gt; is required.
        /// </summary>
        [Input("priceData")]
        public Input<Inputs.SubscriptionSchedulePhaseAddInvoiceItemPriceDataGetArgs>? PriceData { get; set; }

        /// <summary>
        /// The quantity of the invoice item.
        /// </summary>
        [Input("quantity")]
        public Input<double>? Quantity { get; set; }

        [Input("taxRates")]
        private InputList<string>? _taxRates;

        /// <summary>
        /// The tax rates which apply to the item. When set, the &lt;span pulumi-lang-nodejs="`defaultTaxRates`" pulumi-lang-dotnet="`DefaultTaxRates`" pulumi-lang-go="`defaultTaxRates`" pulumi-lang-python="`default_tax_rates`" pulumi-lang-yaml="`defaultTaxRates`" pulumi-lang-java="`defaultTaxRates`" pulumi-lang-hcl="`default_tax_rates`"&gt;`defaultTaxRates`&lt;/span&gt; do not apply to this item.
        /// </summary>
        public InputList<string> TaxRates
        {
            get => _taxRates ?? (_taxRates = new InputList<string>());
            set => _taxRates = value;
        }

        public SubscriptionSchedulePhaseAddInvoiceItemGetArgs()
        {
        }
        public static new SubscriptionSchedulePhaseAddInvoiceItemGetArgs Empty => new SubscriptionSchedulePhaseAddInvoiceItemGetArgs();
    }
}
