// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class SubscriptionSchedulePhaseAutomaticTaxArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If Stripe disabled automatic tax, this enum describes why.
        /// </summary>
        [Input("disabledReason")]
        public Input<string>? DisabledReason { get; set; }

        /// <summary>
        /// Whether Stripe automatically computes tax on invoices created during this phase.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// The account that's liable for tax. If set, the business address and tax registrations required to perform the tax calculation are loaded from this account. The tax transaction is returned in the report of the connected account.
        /// </summary>
        [Input("liability")]
        public Input<Inputs.SubscriptionSchedulePhaseAutomaticTaxLiabilityArgs>? Liability { get; set; }

        public SubscriptionSchedulePhaseAutomaticTaxArgs()
        {
        }
        public static new SubscriptionSchedulePhaseAutomaticTaxArgs Empty => new SubscriptionSchedulePhaseAutomaticTaxArgs();
    }
}
