// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class TaxRegistrationCountryOptionsMtGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("standard")]
        public Input<Inputs.TaxRegistrationCountryOptionsMtStandardGetArgs>? Standard { get; set; }

        /// <summary>
        /// Type of registration in an EU country.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public TaxRegistrationCountryOptionsMtGetArgs()
        {
        }
        public static new TaxRegistrationCountryOptionsMtGetArgs Empty => new TaxRegistrationCountryOptionsMtGetArgs();
    }
}
