// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class TreasuryFinancialAccountFinancialAddressArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ABA Records contain U.S. bank account details per the ABA format.
        /// </summary>
        [Input("aba")]
        public Input<Inputs.TreasuryFinancialAccountFinancialAddressAbaArgs>? Aba { get; set; }

        [Input("supportedNetworks")]
        private InputList<string>? _supportedNetworks;

        /// <summary>
        /// The list of networks that the address supports
        /// </summary>
        public InputList<string> SupportedNetworks
        {
            get => _supportedNetworks ?? (_supportedNetworks = new InputList<string>());
            set => _supportedNetworks = value;
        }

        /// <summary>
        /// The type of financial address
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public TreasuryFinancialAccountFinancialAddressArgs()
        {
        }
        public static new TreasuryFinancialAccountFinancialAddressArgs Empty => new TreasuryFinancialAccountFinancialAddressArgs();
    }
}
