// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class V2CoreEventDestinationStatusDetailsDisabledArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Reason event destination has been disabled.
        /// </summary>
        [Input("reason")]
        public Input<string>? Reason { get; set; }

        public V2CoreEventDestinationStatusDetailsDisabledArgs()
        {
        }
        public static new V2CoreEventDestinationStatusDetailsDisabledArgs Empty => new V2CoreEventDestinationStatusDetailsDisabledArgs();
    }
}
