# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['IssuingCardholderArgs', 'IssuingCardholder']

@pulumi.input_type
class IssuingCardholderArgs:
    def __init__(__self__, *,
                 billing: pulumi.Input['IssuingCardholderBillingArgs'],
                 company: pulumi.Input[Optional['IssuingCardholderCompanyArgs']] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 individual: pulumi.Input[Optional['IssuingCardholderIndividualArgs']] = None,
                 metadata: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 phone_number: pulumi.Input[Optional[_builtins.str]] = None,
                 preferred_locales: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 spending_controls: pulumi.Input[Optional['IssuingCardholderSpendingControlsArgs']] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a IssuingCardholder resource.

        :param pulumi.Input['IssuingCardholderCompanyArgs'] company: Additional information about a <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span> cardholder.
        :param pulumi.Input[_builtins.str] email: The cardholder's email address.
        :param pulumi.Input['IssuingCardholderIndividualArgs'] individual: Additional information about an <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> cardholder.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        :param pulumi.Input[_builtins.str] name: The cardholder's name. This will be printed on cards issued to them.
        :param pulumi.Input[_builtins.str] phone_number: The cardholder's phone number. This is required for all cardholders who will be creating EU cards. See the [3D Secure documentation](https://docs.stripe.com/issuing/3d-secure#when-is-3d-secure-applied) for more details.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] preferred_locales: The cardholder’s preferred locales (languages), ordered by preference. Locales can be <span pulumi-lang-nodejs="`da`" pulumi-lang-dotnet="`Da`" pulumi-lang-go="`da`" pulumi-lang-python="`da`" pulumi-lang-yaml="`da`" pulumi-lang-java="`da`" pulumi-lang-hcl="`da`">`da`</span>, <span pulumi-lang-nodejs="`de`" pulumi-lang-dotnet="`De`" pulumi-lang-go="`de`" pulumi-lang-python="`de`" pulumi-lang-yaml="`de`" pulumi-lang-java="`de`" pulumi-lang-hcl="`de`">`de`</span>, <span pulumi-lang-nodejs="`en`" pulumi-lang-dotnet="`En`" pulumi-lang-go="`en`" pulumi-lang-python="`en`" pulumi-lang-yaml="`en`" pulumi-lang-java="`en`" pulumi-lang-hcl="`en`">`en`</span>, <span pulumi-lang-nodejs="`es`" pulumi-lang-dotnet="`Es`" pulumi-lang-go="`es`" pulumi-lang-python="`es`" pulumi-lang-yaml="`es`" pulumi-lang-java="`es`" pulumi-lang-hcl="`es`">`es`</span>, <span pulumi-lang-nodejs="`fr`" pulumi-lang-dotnet="`Fr`" pulumi-lang-go="`fr`" pulumi-lang-python="`fr`" pulumi-lang-yaml="`fr`" pulumi-lang-java="`fr`" pulumi-lang-hcl="`fr`">`fr`</span>, <span pulumi-lang-nodejs="`it`" pulumi-lang-dotnet="`It`" pulumi-lang-go="`it`" pulumi-lang-python="`it`" pulumi-lang-yaml="`it`" pulumi-lang-java="`it`" pulumi-lang-hcl="`it`">`it`</span>, <span pulumi-lang-nodejs="`pl`" pulumi-lang-dotnet="`Pl`" pulumi-lang-go="`pl`" pulumi-lang-python="`pl`" pulumi-lang-yaml="`pl`" pulumi-lang-java="`pl`" pulumi-lang-hcl="`pl`">`pl`</span>, or <span pulumi-lang-nodejs="`sv`" pulumi-lang-dotnet="`Sv`" pulumi-lang-go="`sv`" pulumi-lang-python="`sv`" pulumi-lang-yaml="`sv`" pulumi-lang-java="`sv`" pulumi-lang-hcl="`sv`">`sv`</span>.
                This changes the language of the [3D Secure flow](https://docs.stripe.com/issuing/3d-secure) and one-time password messages sent to the cardholder.
        :param pulumi.Input['IssuingCardholderSpendingControlsArgs'] spending_controls: Rules that control spending across this cardholder's cards. Refer to our [documentation](https://docs.stripe.com/issuing/controls/spending-controls) for more details.
        :param pulumi.Input[_builtins.str] status: Specifies whether to permit authorizations on this cardholder's cards.
        :param pulumi.Input[_builtins.str] type: One of <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> or <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span>. See [Choose a cardholder type](https://docs.stripe.com/issuing/other/choose-cardholder) for more details.
        """
        pulumi.set(__self__, "billing", billing)
        if company is not None:
            pulumi.set(__self__, "company", company)
        if email is not None:
            pulumi.set(__self__, "email", email)
        if individual is not None:
            pulumi.set(__self__, "individual", individual)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if phone_number is not None:
            pulumi.set(__self__, "phone_number", phone_number)
        if preferred_locales is not None:
            pulumi.set(__self__, "preferred_locales", preferred_locales)
        if spending_controls is not None:
            pulumi.set(__self__, "spending_controls", spending_controls)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def billing(self) -> pulumi.Input['IssuingCardholderBillingArgs']:
        return pulumi.get(self, "billing")

    @billing.setter
    def billing(self, value: pulumi.Input['IssuingCardholderBillingArgs']):
        pulumi.set(self, "billing", value)

    @_builtins.property
    @pulumi.getter
    def company(self) -> pulumi.Input[Optional['IssuingCardholderCompanyArgs']]:
        """
        Additional information about a <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span> cardholder.
        """
        return pulumi.get(self, "company")

    @company.setter
    def company(self, value: pulumi.Input[Optional['IssuingCardholderCompanyArgs']]):
        pulumi.set(self, "company", value)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The cardholder's email address.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter
    def individual(self) -> pulumi.Input[Optional['IssuingCardholderIndividualArgs']]:
        """
        Additional information about an <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> cardholder.
        """
        return pulumi.get(self, "individual")

    @individual.setter
    def individual(self, value: pulumi.Input[Optional['IssuingCardholderIndividualArgs']]):
        pulumi.set(self, "individual", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The cardholder's name. This will be printed on cards issued to them.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="phoneNumber")
    def phone_number(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The cardholder's phone number. This is required for all cardholders who will be creating EU cards. See the [3D Secure documentation](https://docs.stripe.com/issuing/3d-secure#when-is-3d-secure-applied) for more details.
        """
        return pulumi.get(self, "phone_number")

    @phone_number.setter
    def phone_number(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "phone_number", value)

    @_builtins.property
    @pulumi.getter(name="preferredLocales")
    def preferred_locales(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The cardholder’s preferred locales (languages), ordered by preference. Locales can be <span pulumi-lang-nodejs="`da`" pulumi-lang-dotnet="`Da`" pulumi-lang-go="`da`" pulumi-lang-python="`da`" pulumi-lang-yaml="`da`" pulumi-lang-java="`da`" pulumi-lang-hcl="`da`">`da`</span>, <span pulumi-lang-nodejs="`de`" pulumi-lang-dotnet="`De`" pulumi-lang-go="`de`" pulumi-lang-python="`de`" pulumi-lang-yaml="`de`" pulumi-lang-java="`de`" pulumi-lang-hcl="`de`">`de`</span>, <span pulumi-lang-nodejs="`en`" pulumi-lang-dotnet="`En`" pulumi-lang-go="`en`" pulumi-lang-python="`en`" pulumi-lang-yaml="`en`" pulumi-lang-java="`en`" pulumi-lang-hcl="`en`">`en`</span>, <span pulumi-lang-nodejs="`es`" pulumi-lang-dotnet="`Es`" pulumi-lang-go="`es`" pulumi-lang-python="`es`" pulumi-lang-yaml="`es`" pulumi-lang-java="`es`" pulumi-lang-hcl="`es`">`es`</span>, <span pulumi-lang-nodejs="`fr`" pulumi-lang-dotnet="`Fr`" pulumi-lang-go="`fr`" pulumi-lang-python="`fr`" pulumi-lang-yaml="`fr`" pulumi-lang-java="`fr`" pulumi-lang-hcl="`fr`">`fr`</span>, <span pulumi-lang-nodejs="`it`" pulumi-lang-dotnet="`It`" pulumi-lang-go="`it`" pulumi-lang-python="`it`" pulumi-lang-yaml="`it`" pulumi-lang-java="`it`" pulumi-lang-hcl="`it`">`it`</span>, <span pulumi-lang-nodejs="`pl`" pulumi-lang-dotnet="`Pl`" pulumi-lang-go="`pl`" pulumi-lang-python="`pl`" pulumi-lang-yaml="`pl`" pulumi-lang-java="`pl`" pulumi-lang-hcl="`pl`">`pl`</span>, or <span pulumi-lang-nodejs="`sv`" pulumi-lang-dotnet="`Sv`" pulumi-lang-go="`sv`" pulumi-lang-python="`sv`" pulumi-lang-yaml="`sv`" pulumi-lang-java="`sv`" pulumi-lang-hcl="`sv`">`sv`</span>.
         This changes the language of the [3D Secure flow](https://docs.stripe.com/issuing/3d-secure) and one-time password messages sent to the cardholder.
        """
        return pulumi.get(self, "preferred_locales")

    @preferred_locales.setter
    def preferred_locales(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "preferred_locales", value)

    @_builtins.property
    @pulumi.getter(name="spendingControls")
    def spending_controls(self) -> pulumi.Input[Optional['IssuingCardholderSpendingControlsArgs']]:
        """
        Rules that control spending across this cardholder's cards. Refer to our [documentation](https://docs.stripe.com/issuing/controls/spending-controls) for more details.
        """
        return pulumi.get(self, "spending_controls")

    @spending_controls.setter
    def spending_controls(self, value: pulumi.Input[Optional['IssuingCardholderSpendingControlsArgs']]):
        pulumi.set(self, "spending_controls", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Specifies whether to permit authorizations on this cardholder's cards.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        One of <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> or <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span>. See [Choose a cardholder type](https://docs.stripe.com/issuing/other/choose-cardholder) for more details.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.input_type
class _IssuingCardholderState:
    def __init__(__self__, *,
                 billing: pulumi.Input[Optional['IssuingCardholderBillingArgs']] = None,
                 company: pulumi.Input[Optional['IssuingCardholderCompanyArgs']] = None,
                 created: pulumi.Input[Optional[_builtins.float]] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 individual: pulumi.Input[Optional['IssuingCardholderIndividualArgs']] = None,
                 livemode: pulumi.Input[Optional[_builtins.bool]] = None,
                 metadata: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 object: pulumi.Input[Optional[_builtins.str]] = None,
                 phone_number: pulumi.Input[Optional[_builtins.str]] = None,
                 preferred_locales: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 requirements: pulumi.Input[Optional['IssuingCardholderRequirementsArgs']] = None,
                 spending_controls: pulumi.Input[Optional['IssuingCardholderSpendingControlsArgs']] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering IssuingCardholder resources.

        :param pulumi.Input['IssuingCardholderCompanyArgs'] company: Additional information about a <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span> cardholder.
        :param pulumi.Input[_builtins.float] created: Time at which the object was created. Measured in seconds since the Unix epoch.
        :param pulumi.Input[_builtins.str] email: The cardholder's email address.
        :param pulumi.Input['IssuingCardholderIndividualArgs'] individual: Additional information about an <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> cardholder.
        :param pulumi.Input[_builtins.bool] livemode: If the object exists in live mode, the value is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>. If the object exists in test mode, the value is <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        :param pulumi.Input[_builtins.str] name: The cardholder's name. This will be printed on cards issued to them.
        :param pulumi.Input[_builtins.str] object: String representing the object's type. Objects of the same type share the same value.
        :param pulumi.Input[_builtins.str] phone_number: The cardholder's phone number. This is required for all cardholders who will be creating EU cards. See the [3D Secure documentation](https://docs.stripe.com/issuing/3d-secure#when-is-3d-secure-applied) for more details.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] preferred_locales: The cardholder’s preferred locales (languages), ordered by preference. Locales can be <span pulumi-lang-nodejs="`da`" pulumi-lang-dotnet="`Da`" pulumi-lang-go="`da`" pulumi-lang-python="`da`" pulumi-lang-yaml="`da`" pulumi-lang-java="`da`" pulumi-lang-hcl="`da`">`da`</span>, <span pulumi-lang-nodejs="`de`" pulumi-lang-dotnet="`De`" pulumi-lang-go="`de`" pulumi-lang-python="`de`" pulumi-lang-yaml="`de`" pulumi-lang-java="`de`" pulumi-lang-hcl="`de`">`de`</span>, <span pulumi-lang-nodejs="`en`" pulumi-lang-dotnet="`En`" pulumi-lang-go="`en`" pulumi-lang-python="`en`" pulumi-lang-yaml="`en`" pulumi-lang-java="`en`" pulumi-lang-hcl="`en`">`en`</span>, <span pulumi-lang-nodejs="`es`" pulumi-lang-dotnet="`Es`" pulumi-lang-go="`es`" pulumi-lang-python="`es`" pulumi-lang-yaml="`es`" pulumi-lang-java="`es`" pulumi-lang-hcl="`es`">`es`</span>, <span pulumi-lang-nodejs="`fr`" pulumi-lang-dotnet="`Fr`" pulumi-lang-go="`fr`" pulumi-lang-python="`fr`" pulumi-lang-yaml="`fr`" pulumi-lang-java="`fr`" pulumi-lang-hcl="`fr`">`fr`</span>, <span pulumi-lang-nodejs="`it`" pulumi-lang-dotnet="`It`" pulumi-lang-go="`it`" pulumi-lang-python="`it`" pulumi-lang-yaml="`it`" pulumi-lang-java="`it`" pulumi-lang-hcl="`it`">`it`</span>, <span pulumi-lang-nodejs="`pl`" pulumi-lang-dotnet="`Pl`" pulumi-lang-go="`pl`" pulumi-lang-python="`pl`" pulumi-lang-yaml="`pl`" pulumi-lang-java="`pl`" pulumi-lang-hcl="`pl`">`pl`</span>, or <span pulumi-lang-nodejs="`sv`" pulumi-lang-dotnet="`Sv`" pulumi-lang-go="`sv`" pulumi-lang-python="`sv`" pulumi-lang-yaml="`sv`" pulumi-lang-java="`sv`" pulumi-lang-hcl="`sv`">`sv`</span>.
                This changes the language of the [3D Secure flow](https://docs.stripe.com/issuing/3d-secure) and one-time password messages sent to the cardholder.
        :param pulumi.Input['IssuingCardholderSpendingControlsArgs'] spending_controls: Rules that control spending across this cardholder's cards. Refer to our [documentation](https://docs.stripe.com/issuing/controls/spending-controls) for more details.
        :param pulumi.Input[_builtins.str] status: Specifies whether to permit authorizations on this cardholder's cards.
        :param pulumi.Input[_builtins.str] type: One of <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> or <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span>. See [Choose a cardholder type](https://docs.stripe.com/issuing/other/choose-cardholder) for more details.
        """
        if billing is not None:
            pulumi.set(__self__, "billing", billing)
        if company is not None:
            pulumi.set(__self__, "company", company)
        if created is not None:
            pulumi.set(__self__, "created", created)
        if email is not None:
            pulumi.set(__self__, "email", email)
        if individual is not None:
            pulumi.set(__self__, "individual", individual)
        if livemode is not None:
            pulumi.set(__self__, "livemode", livemode)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if object is not None:
            pulumi.set(__self__, "object", object)
        if phone_number is not None:
            pulumi.set(__self__, "phone_number", phone_number)
        if preferred_locales is not None:
            pulumi.set(__self__, "preferred_locales", preferred_locales)
        if requirements is not None:
            pulumi.set(__self__, "requirements", requirements)
        if spending_controls is not None:
            pulumi.set(__self__, "spending_controls", spending_controls)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def billing(self) -> pulumi.Input[Optional['IssuingCardholderBillingArgs']]:
        return pulumi.get(self, "billing")

    @billing.setter
    def billing(self, value: pulumi.Input[Optional['IssuingCardholderBillingArgs']]):
        pulumi.set(self, "billing", value)

    @_builtins.property
    @pulumi.getter
    def company(self) -> pulumi.Input[Optional['IssuingCardholderCompanyArgs']]:
        """
        Additional information about a <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span> cardholder.
        """
        return pulumi.get(self, "company")

    @company.setter
    def company(self, value: pulumi.Input[Optional['IssuingCardholderCompanyArgs']]):
        pulumi.set(self, "company", value)

    @_builtins.property
    @pulumi.getter
    def created(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Time at which the object was created. Measured in seconds since the Unix epoch.
        """
        return pulumi.get(self, "created")

    @created.setter
    def created(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "created", value)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The cardholder's email address.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter
    def individual(self) -> pulumi.Input[Optional['IssuingCardholderIndividualArgs']]:
        """
        Additional information about an <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> cardholder.
        """
        return pulumi.get(self, "individual")

    @individual.setter
    def individual(self, value: pulumi.Input[Optional['IssuingCardholderIndividualArgs']]):
        pulumi.set(self, "individual", value)

    @_builtins.property
    @pulumi.getter
    def livemode(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        If the object exists in live mode, the value is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>. If the object exists in test mode, the value is <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
        """
        return pulumi.get(self, "livemode")

    @livemode.setter
    def livemode(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "livemode", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The cardholder's name. This will be printed on cards issued to them.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def object(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        String representing the object's type. Objects of the same type share the same value.
        """
        return pulumi.get(self, "object")

    @object.setter
    def object(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "object", value)

    @_builtins.property
    @pulumi.getter(name="phoneNumber")
    def phone_number(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The cardholder's phone number. This is required for all cardholders who will be creating EU cards. See the [3D Secure documentation](https://docs.stripe.com/issuing/3d-secure#when-is-3d-secure-applied) for more details.
        """
        return pulumi.get(self, "phone_number")

    @phone_number.setter
    def phone_number(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "phone_number", value)

    @_builtins.property
    @pulumi.getter(name="preferredLocales")
    def preferred_locales(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The cardholder’s preferred locales (languages), ordered by preference. Locales can be <span pulumi-lang-nodejs="`da`" pulumi-lang-dotnet="`Da`" pulumi-lang-go="`da`" pulumi-lang-python="`da`" pulumi-lang-yaml="`da`" pulumi-lang-java="`da`" pulumi-lang-hcl="`da`">`da`</span>, <span pulumi-lang-nodejs="`de`" pulumi-lang-dotnet="`De`" pulumi-lang-go="`de`" pulumi-lang-python="`de`" pulumi-lang-yaml="`de`" pulumi-lang-java="`de`" pulumi-lang-hcl="`de`">`de`</span>, <span pulumi-lang-nodejs="`en`" pulumi-lang-dotnet="`En`" pulumi-lang-go="`en`" pulumi-lang-python="`en`" pulumi-lang-yaml="`en`" pulumi-lang-java="`en`" pulumi-lang-hcl="`en`">`en`</span>, <span pulumi-lang-nodejs="`es`" pulumi-lang-dotnet="`Es`" pulumi-lang-go="`es`" pulumi-lang-python="`es`" pulumi-lang-yaml="`es`" pulumi-lang-java="`es`" pulumi-lang-hcl="`es`">`es`</span>, <span pulumi-lang-nodejs="`fr`" pulumi-lang-dotnet="`Fr`" pulumi-lang-go="`fr`" pulumi-lang-python="`fr`" pulumi-lang-yaml="`fr`" pulumi-lang-java="`fr`" pulumi-lang-hcl="`fr`">`fr`</span>, <span pulumi-lang-nodejs="`it`" pulumi-lang-dotnet="`It`" pulumi-lang-go="`it`" pulumi-lang-python="`it`" pulumi-lang-yaml="`it`" pulumi-lang-java="`it`" pulumi-lang-hcl="`it`">`it`</span>, <span pulumi-lang-nodejs="`pl`" pulumi-lang-dotnet="`Pl`" pulumi-lang-go="`pl`" pulumi-lang-python="`pl`" pulumi-lang-yaml="`pl`" pulumi-lang-java="`pl`" pulumi-lang-hcl="`pl`">`pl`</span>, or <span pulumi-lang-nodejs="`sv`" pulumi-lang-dotnet="`Sv`" pulumi-lang-go="`sv`" pulumi-lang-python="`sv`" pulumi-lang-yaml="`sv`" pulumi-lang-java="`sv`" pulumi-lang-hcl="`sv`">`sv`</span>.
         This changes the language of the [3D Secure flow](https://docs.stripe.com/issuing/3d-secure) and one-time password messages sent to the cardholder.
        """
        return pulumi.get(self, "preferred_locales")

    @preferred_locales.setter
    def preferred_locales(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "preferred_locales", value)

    @_builtins.property
    @pulumi.getter
    def requirements(self) -> pulumi.Input[Optional['IssuingCardholderRequirementsArgs']]:
        return pulumi.get(self, "requirements")

    @requirements.setter
    def requirements(self, value: pulumi.Input[Optional['IssuingCardholderRequirementsArgs']]):
        pulumi.set(self, "requirements", value)

    @_builtins.property
    @pulumi.getter(name="spendingControls")
    def spending_controls(self) -> pulumi.Input[Optional['IssuingCardholderSpendingControlsArgs']]:
        """
        Rules that control spending across this cardholder's cards. Refer to our [documentation](https://docs.stripe.com/issuing/controls/spending-controls) for more details.
        """
        return pulumi.get(self, "spending_controls")

    @spending_controls.setter
    def spending_controls(self, value: pulumi.Input[Optional['IssuingCardholderSpendingControlsArgs']]):
        pulumi.set(self, "spending_controls", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Specifies whether to permit authorizations on this cardholder's cards.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        One of <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> or <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span>. See [Choose a cardholder type](https://docs.stripe.com/issuing/other/choose-cardholder) for more details.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.type_token("stripe:index/issuingCardholder:IssuingCardholder")
class IssuingCardholder(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 billing: pulumi.Input[Optional[Union['IssuingCardholderBillingArgs', 'IssuingCardholderBillingArgsDict']]] = None,
                 company: pulumi.Input[Optional[Union['IssuingCardholderCompanyArgs', 'IssuingCardholderCompanyArgsDict']]] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 individual: pulumi.Input[Optional[Union['IssuingCardholderIndividualArgs', 'IssuingCardholderIndividualArgsDict']]] = None,
                 metadata: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 phone_number: pulumi.Input[Optional[_builtins.str]] = None,
                 preferred_locales: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 spending_controls: pulumi.Input[Optional[Union['IssuingCardholderSpendingControlsArgs', 'IssuingCardholderSpendingControlsArgsDict']]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a IssuingCardholder resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['IssuingCardholderCompanyArgs', 'IssuingCardholderCompanyArgsDict']] company: Additional information about a <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span> cardholder.
        :param pulumi.Input[_builtins.str] email: The cardholder's email address.
        :param pulumi.Input[Union['IssuingCardholderIndividualArgs', 'IssuingCardholderIndividualArgsDict']] individual: Additional information about an <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> cardholder.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        :param pulumi.Input[_builtins.str] name: The cardholder's name. This will be printed on cards issued to them.
        :param pulumi.Input[_builtins.str] phone_number: The cardholder's phone number. This is required for all cardholders who will be creating EU cards. See the [3D Secure documentation](https://docs.stripe.com/issuing/3d-secure#when-is-3d-secure-applied) for more details.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] preferred_locales: The cardholder’s preferred locales (languages), ordered by preference. Locales can be <span pulumi-lang-nodejs="`da`" pulumi-lang-dotnet="`Da`" pulumi-lang-go="`da`" pulumi-lang-python="`da`" pulumi-lang-yaml="`da`" pulumi-lang-java="`da`" pulumi-lang-hcl="`da`">`da`</span>, <span pulumi-lang-nodejs="`de`" pulumi-lang-dotnet="`De`" pulumi-lang-go="`de`" pulumi-lang-python="`de`" pulumi-lang-yaml="`de`" pulumi-lang-java="`de`" pulumi-lang-hcl="`de`">`de`</span>, <span pulumi-lang-nodejs="`en`" pulumi-lang-dotnet="`En`" pulumi-lang-go="`en`" pulumi-lang-python="`en`" pulumi-lang-yaml="`en`" pulumi-lang-java="`en`" pulumi-lang-hcl="`en`">`en`</span>, <span pulumi-lang-nodejs="`es`" pulumi-lang-dotnet="`Es`" pulumi-lang-go="`es`" pulumi-lang-python="`es`" pulumi-lang-yaml="`es`" pulumi-lang-java="`es`" pulumi-lang-hcl="`es`">`es`</span>, <span pulumi-lang-nodejs="`fr`" pulumi-lang-dotnet="`Fr`" pulumi-lang-go="`fr`" pulumi-lang-python="`fr`" pulumi-lang-yaml="`fr`" pulumi-lang-java="`fr`" pulumi-lang-hcl="`fr`">`fr`</span>, <span pulumi-lang-nodejs="`it`" pulumi-lang-dotnet="`It`" pulumi-lang-go="`it`" pulumi-lang-python="`it`" pulumi-lang-yaml="`it`" pulumi-lang-java="`it`" pulumi-lang-hcl="`it`">`it`</span>, <span pulumi-lang-nodejs="`pl`" pulumi-lang-dotnet="`Pl`" pulumi-lang-go="`pl`" pulumi-lang-python="`pl`" pulumi-lang-yaml="`pl`" pulumi-lang-java="`pl`" pulumi-lang-hcl="`pl`">`pl`</span>, or <span pulumi-lang-nodejs="`sv`" pulumi-lang-dotnet="`Sv`" pulumi-lang-go="`sv`" pulumi-lang-python="`sv`" pulumi-lang-yaml="`sv`" pulumi-lang-java="`sv`" pulumi-lang-hcl="`sv`">`sv`</span>.
                This changes the language of the [3D Secure flow](https://docs.stripe.com/issuing/3d-secure) and one-time password messages sent to the cardholder.
        :param pulumi.Input[Union['IssuingCardholderSpendingControlsArgs', 'IssuingCardholderSpendingControlsArgsDict']] spending_controls: Rules that control spending across this cardholder's cards. Refer to our [documentation](https://docs.stripe.com/issuing/controls/spending-controls) for more details.
        :param pulumi.Input[_builtins.str] status: Specifies whether to permit authorizations on this cardholder's cards.
        :param pulumi.Input[_builtins.str] type: One of <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> or <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span>. See [Choose a cardholder type](https://docs.stripe.com/issuing/other/choose-cardholder) for more details.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: IssuingCardholderArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a IssuingCardholder resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param IssuingCardholderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(IssuingCardholderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 billing: pulumi.Input[Optional[Union['IssuingCardholderBillingArgs', 'IssuingCardholderBillingArgsDict']]] = None,
                 company: pulumi.Input[Optional[Union['IssuingCardholderCompanyArgs', 'IssuingCardholderCompanyArgsDict']]] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 individual: pulumi.Input[Optional[Union['IssuingCardholderIndividualArgs', 'IssuingCardholderIndividualArgsDict']]] = None,
                 metadata: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 phone_number: pulumi.Input[Optional[_builtins.str]] = None,
                 preferred_locales: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 spending_controls: pulumi.Input[Optional[Union['IssuingCardholderSpendingControlsArgs', 'IssuingCardholderSpendingControlsArgsDict']]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = IssuingCardholderArgs.__new__(IssuingCardholderArgs)

            if billing is None and not opts.urn:
                raise TypeError("Missing required property 'billing'")
            __props__.__dict__["billing"] = billing
            __props__.__dict__["company"] = company
            __props__.__dict__["email"] = email
            __props__.__dict__["individual"] = individual
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["name"] = name
            __props__.__dict__["phone_number"] = phone_number
            __props__.__dict__["preferred_locales"] = preferred_locales
            __props__.__dict__["spending_controls"] = spending_controls
            __props__.__dict__["status"] = status
            __props__.__dict__["type"] = type
            __props__.__dict__["created"] = None
            __props__.__dict__["livemode"] = None
            __props__.__dict__["object"] = None
            __props__.__dict__["requirements"] = None
        super(IssuingCardholder, __self__).__init__(
            'stripe:index/issuingCardholder:IssuingCardholder',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            billing: pulumi.Input[Optional[Union['IssuingCardholderBillingArgs', 'IssuingCardholderBillingArgsDict']]] = None,
            company: pulumi.Input[Optional[Union['IssuingCardholderCompanyArgs', 'IssuingCardholderCompanyArgsDict']]] = None,
            created: pulumi.Input[Optional[_builtins.float]] = None,
            email: pulumi.Input[Optional[_builtins.str]] = None,
            individual: pulumi.Input[Optional[Union['IssuingCardholderIndividualArgs', 'IssuingCardholderIndividualArgsDict']]] = None,
            livemode: pulumi.Input[Optional[_builtins.bool]] = None,
            metadata: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            object: pulumi.Input[Optional[_builtins.str]] = None,
            phone_number: pulumi.Input[Optional[_builtins.str]] = None,
            preferred_locales: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            requirements: pulumi.Input[Optional[Union['IssuingCardholderRequirementsArgs', 'IssuingCardholderRequirementsArgsDict']]] = None,
            spending_controls: pulumi.Input[Optional[Union['IssuingCardholderSpendingControlsArgs', 'IssuingCardholderSpendingControlsArgsDict']]] = None,
            status: pulumi.Input[Optional[_builtins.str]] = None,
            type: pulumi.Input[Optional[_builtins.str]] = None) -> 'IssuingCardholder':
        """
        Get an existing IssuingCardholder resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['IssuingCardholderCompanyArgs', 'IssuingCardholderCompanyArgsDict']] company: Additional information about a <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span> cardholder.
        :param pulumi.Input[_builtins.float] created: Time at which the object was created. Measured in seconds since the Unix epoch.
        :param pulumi.Input[_builtins.str] email: The cardholder's email address.
        :param pulumi.Input[Union['IssuingCardholderIndividualArgs', 'IssuingCardholderIndividualArgsDict']] individual: Additional information about an <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> cardholder.
        :param pulumi.Input[_builtins.bool] livemode: If the object exists in live mode, the value is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>. If the object exists in test mode, the value is <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        :param pulumi.Input[_builtins.str] name: The cardholder's name. This will be printed on cards issued to them.
        :param pulumi.Input[_builtins.str] object: String representing the object's type. Objects of the same type share the same value.
        :param pulumi.Input[_builtins.str] phone_number: The cardholder's phone number. This is required for all cardholders who will be creating EU cards. See the [3D Secure documentation](https://docs.stripe.com/issuing/3d-secure#when-is-3d-secure-applied) for more details.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] preferred_locales: The cardholder’s preferred locales (languages), ordered by preference. Locales can be <span pulumi-lang-nodejs="`da`" pulumi-lang-dotnet="`Da`" pulumi-lang-go="`da`" pulumi-lang-python="`da`" pulumi-lang-yaml="`da`" pulumi-lang-java="`da`" pulumi-lang-hcl="`da`">`da`</span>, <span pulumi-lang-nodejs="`de`" pulumi-lang-dotnet="`De`" pulumi-lang-go="`de`" pulumi-lang-python="`de`" pulumi-lang-yaml="`de`" pulumi-lang-java="`de`" pulumi-lang-hcl="`de`">`de`</span>, <span pulumi-lang-nodejs="`en`" pulumi-lang-dotnet="`En`" pulumi-lang-go="`en`" pulumi-lang-python="`en`" pulumi-lang-yaml="`en`" pulumi-lang-java="`en`" pulumi-lang-hcl="`en`">`en`</span>, <span pulumi-lang-nodejs="`es`" pulumi-lang-dotnet="`Es`" pulumi-lang-go="`es`" pulumi-lang-python="`es`" pulumi-lang-yaml="`es`" pulumi-lang-java="`es`" pulumi-lang-hcl="`es`">`es`</span>, <span pulumi-lang-nodejs="`fr`" pulumi-lang-dotnet="`Fr`" pulumi-lang-go="`fr`" pulumi-lang-python="`fr`" pulumi-lang-yaml="`fr`" pulumi-lang-java="`fr`" pulumi-lang-hcl="`fr`">`fr`</span>, <span pulumi-lang-nodejs="`it`" pulumi-lang-dotnet="`It`" pulumi-lang-go="`it`" pulumi-lang-python="`it`" pulumi-lang-yaml="`it`" pulumi-lang-java="`it`" pulumi-lang-hcl="`it`">`it`</span>, <span pulumi-lang-nodejs="`pl`" pulumi-lang-dotnet="`Pl`" pulumi-lang-go="`pl`" pulumi-lang-python="`pl`" pulumi-lang-yaml="`pl`" pulumi-lang-java="`pl`" pulumi-lang-hcl="`pl`">`pl`</span>, or <span pulumi-lang-nodejs="`sv`" pulumi-lang-dotnet="`Sv`" pulumi-lang-go="`sv`" pulumi-lang-python="`sv`" pulumi-lang-yaml="`sv`" pulumi-lang-java="`sv`" pulumi-lang-hcl="`sv`">`sv`</span>.
                This changes the language of the [3D Secure flow](https://docs.stripe.com/issuing/3d-secure) and one-time password messages sent to the cardholder.
        :param pulumi.Input[Union['IssuingCardholderSpendingControlsArgs', 'IssuingCardholderSpendingControlsArgsDict']] spending_controls: Rules that control spending across this cardholder's cards. Refer to our [documentation](https://docs.stripe.com/issuing/controls/spending-controls) for more details.
        :param pulumi.Input[_builtins.str] status: Specifies whether to permit authorizations on this cardholder's cards.
        :param pulumi.Input[_builtins.str] type: One of <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> or <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span>. See [Choose a cardholder type](https://docs.stripe.com/issuing/other/choose-cardholder) for more details.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _IssuingCardholderState.__new__(_IssuingCardholderState)

        __props__.__dict__["billing"] = billing
        __props__.__dict__["company"] = company
        __props__.__dict__["created"] = created
        __props__.__dict__["email"] = email
        __props__.__dict__["individual"] = individual
        __props__.__dict__["livemode"] = livemode
        __props__.__dict__["metadata"] = metadata
        __props__.__dict__["name"] = name
        __props__.__dict__["object"] = object
        __props__.__dict__["phone_number"] = phone_number
        __props__.__dict__["preferred_locales"] = preferred_locales
        __props__.__dict__["requirements"] = requirements
        __props__.__dict__["spending_controls"] = spending_controls
        __props__.__dict__["status"] = status
        __props__.__dict__["type"] = type
        return IssuingCardholder(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def billing(self) -> pulumi.Output['outputs.IssuingCardholderBilling']:
        return pulumi.get(self, "billing")

    @_builtins.property
    @pulumi.getter
    def company(self) -> pulumi.Output['outputs.IssuingCardholderCompany']:
        """
        Additional information about a <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span> cardholder.
        """
        return pulumi.get(self, "company")

    @_builtins.property
    @pulumi.getter
    def created(self) -> pulumi.Output[_builtins.float]:
        """
        Time at which the object was created. Measured in seconds since the Unix epoch.
        """
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Output[_builtins.str]:
        """
        The cardholder's email address.
        """
        return pulumi.get(self, "email")

    @_builtins.property
    @pulumi.getter
    def individual(self) -> pulumi.Output['outputs.IssuingCardholderIndividual']:
        """
        Additional information about an <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> cardholder.
        """
        return pulumi.get(self, "individual")

    @_builtins.property
    @pulumi.getter
    def livemode(self) -> pulumi.Output[_builtins.bool]:
        """
        If the object exists in live mode, the value is <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>. If the object exists in test mode, the value is <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
        """
        return pulumi.get(self, "livemode")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The cardholder's name. This will be printed on cards issued to them.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def object(self) -> pulumi.Output[_builtins.str]:
        """
        String representing the object's type. Objects of the same type share the same value.
        """
        return pulumi.get(self, "object")

    @_builtins.property
    @pulumi.getter(name="phoneNumber")
    def phone_number(self) -> pulumi.Output[_builtins.str]:
        """
        The cardholder's phone number. This is required for all cardholders who will be creating EU cards. See the [3D Secure documentation](https://docs.stripe.com/issuing/3d-secure#when-is-3d-secure-applied) for more details.
        """
        return pulumi.get(self, "phone_number")

    @_builtins.property
    @pulumi.getter(name="preferredLocales")
    def preferred_locales(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        The cardholder’s preferred locales (languages), ordered by preference. Locales can be <span pulumi-lang-nodejs="`da`" pulumi-lang-dotnet="`Da`" pulumi-lang-go="`da`" pulumi-lang-python="`da`" pulumi-lang-yaml="`da`" pulumi-lang-java="`da`" pulumi-lang-hcl="`da`">`da`</span>, <span pulumi-lang-nodejs="`de`" pulumi-lang-dotnet="`De`" pulumi-lang-go="`de`" pulumi-lang-python="`de`" pulumi-lang-yaml="`de`" pulumi-lang-java="`de`" pulumi-lang-hcl="`de`">`de`</span>, <span pulumi-lang-nodejs="`en`" pulumi-lang-dotnet="`En`" pulumi-lang-go="`en`" pulumi-lang-python="`en`" pulumi-lang-yaml="`en`" pulumi-lang-java="`en`" pulumi-lang-hcl="`en`">`en`</span>, <span pulumi-lang-nodejs="`es`" pulumi-lang-dotnet="`Es`" pulumi-lang-go="`es`" pulumi-lang-python="`es`" pulumi-lang-yaml="`es`" pulumi-lang-java="`es`" pulumi-lang-hcl="`es`">`es`</span>, <span pulumi-lang-nodejs="`fr`" pulumi-lang-dotnet="`Fr`" pulumi-lang-go="`fr`" pulumi-lang-python="`fr`" pulumi-lang-yaml="`fr`" pulumi-lang-java="`fr`" pulumi-lang-hcl="`fr`">`fr`</span>, <span pulumi-lang-nodejs="`it`" pulumi-lang-dotnet="`It`" pulumi-lang-go="`it`" pulumi-lang-python="`it`" pulumi-lang-yaml="`it`" pulumi-lang-java="`it`" pulumi-lang-hcl="`it`">`it`</span>, <span pulumi-lang-nodejs="`pl`" pulumi-lang-dotnet="`Pl`" pulumi-lang-go="`pl`" pulumi-lang-python="`pl`" pulumi-lang-yaml="`pl`" pulumi-lang-java="`pl`" pulumi-lang-hcl="`pl`">`pl`</span>, or <span pulumi-lang-nodejs="`sv`" pulumi-lang-dotnet="`Sv`" pulumi-lang-go="`sv`" pulumi-lang-python="`sv`" pulumi-lang-yaml="`sv`" pulumi-lang-java="`sv`" pulumi-lang-hcl="`sv`">`sv`</span>.
         This changes the language of the [3D Secure flow](https://docs.stripe.com/issuing/3d-secure) and one-time password messages sent to the cardholder.
        """
        return pulumi.get(self, "preferred_locales")

    @_builtins.property
    @pulumi.getter
    def requirements(self) -> pulumi.Output['outputs.IssuingCardholderRequirements']:
        return pulumi.get(self, "requirements")

    @_builtins.property
    @pulumi.getter(name="spendingControls")
    def spending_controls(self) -> pulumi.Output['outputs.IssuingCardholderSpendingControls']:
        """
        Rules that control spending across this cardholder's cards. Refer to our [documentation](https://docs.stripe.com/issuing/controls/spending-controls) for more details.
        """
        return pulumi.get(self, "spending_controls")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Specifies whether to permit authorizations on this cardholder's cards.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]:
        """
        One of <span pulumi-lang-nodejs="`individual`" pulumi-lang-dotnet="`Individual`" pulumi-lang-go="`individual`" pulumi-lang-python="`individual`" pulumi-lang-yaml="`individual`" pulumi-lang-java="`individual`" pulumi-lang-hcl="`individual`">`individual`</span> or <span pulumi-lang-nodejs="`company`" pulumi-lang-dotnet="`Company`" pulumi-lang-go="`company`" pulumi-lang-python="`company`" pulumi-lang-yaml="`company`" pulumi-lang-java="`company`" pulumi-lang-hcl="`company`">`company`</span>. See [Choose a cardholder type](https://docs.stripe.com/issuing/other/choose-cardholder) for more details.
        """
        return pulumi.get(self, "type")

