// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class BillingPortalConfigurationFeaturesSubscriptionCancelCancellationReason {
    /**
     * @return Whether the feature is enabled.
     * 
     */
    private Boolean enabled;
    /**
     * @return Which cancellation reasons will be given as options to the customer.
     * 
     */
    private List<String> options;

    private BillingPortalConfigurationFeaturesSubscriptionCancelCancellationReason() {}
    /**
     * @return Whether the feature is enabled.
     * 
     */
    public Boolean enabled() {
        return this.enabled;
    }
    /**
     * @return Which cancellation reasons will be given as options to the customer.
     * 
     */
    public List<String> options() {
        return this.options;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(BillingPortalConfigurationFeaturesSubscriptionCancelCancellationReason defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean enabled;
        private List<String> options;
        public Builder() {}
        public Builder(BillingPortalConfigurationFeaturesSubscriptionCancelCancellationReason defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
    	      this.options = defaults.options;
        }

        @CustomType.Setter
        public Builder enabled(Boolean enabled) {
            if (enabled == null) {
              throw new MissingRequiredPropertyException("BillingPortalConfigurationFeaturesSubscriptionCancelCancellationReason", "enabled");
            }
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder options(List<String> options) {
            if (options == null) {
              throw new MissingRequiredPropertyException("BillingPortalConfigurationFeaturesSubscriptionCancelCancellationReason", "options");
            }
            this.options = options;
            return this;
        }
        public Builder options(String... options) {
            return options(List.of(options));
        }
        public BillingPortalConfigurationFeaturesSubscriptionCancelCancellationReason build() {
            final var _resultValue = new BillingPortalConfigurationFeaturesSubscriptionCancelCancellationReason();
            _resultValue.enabled = enabled;
            _resultValue.options = options;
            return _resultValue;
        }
    }
}
