// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ChargePaymentMethodDetailsPaypalSellerProtection {
    /**
     * @return An array of conditions that are covered for the transaction, if applicable.
     * 
     */
    private @Nullable List<String> disputeCategories;
    /**
     * @return Indicates whether the transaction is eligible for PayPal&#39;s seller protection.
     * 
     */
    private @Nullable String status;

    private ChargePaymentMethodDetailsPaypalSellerProtection() {}
    /**
     * @return An array of conditions that are covered for the transaction, if applicable.
     * 
     */
    public List<String> disputeCategories() {
        return this.disputeCategories == null ? List.of() : this.disputeCategories;
    }
    /**
     * @return Indicates whether the transaction is eligible for PayPal&#39;s seller protection.
     * 
     */
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ChargePaymentMethodDetailsPaypalSellerProtection defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> disputeCategories;
        private @Nullable String status;
        public Builder() {}
        public Builder(ChargePaymentMethodDetailsPaypalSellerProtection defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.disputeCategories = defaults.disputeCategories;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder disputeCategories(@Nullable List<String> disputeCategories) {

            this.disputeCategories = disputeCategories;
            return this;
        }
        public Builder disputeCategories(String... disputeCategories) {
            return disputeCategories(List.of(disputeCategories));
        }
        @CustomType.Setter
        public Builder status(@Nullable String status) {

            this.status = status;
            return this;
        }
        public ChargePaymentMethodDetailsPaypalSellerProtection build() {
            final var _resultValue = new ChargePaymentMethodDetailsPaypalSellerProtection();
            _resultValue.disputeCategories = disputeCategories;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
