// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.stripe.outputs.ClimateOrderDeliveryDetailLocation;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ClimateOrderDeliveryDetail {
    /**
     * @return Time at which the delivery occurred. Measured in seconds since the Unix epoch.
     * 
     */
    private @Nullable Double deliveredAt;
    /**
     * @return Specific location of this delivery.
     * 
     */
    private @Nullable ClimateOrderDeliveryDetailLocation location;
    /**
     * @return Quantity of carbon removal supplied by this delivery.
     * 
     */
    private @Nullable String metricTons;
    /**
     * @return Once retired, a URL to the registry entry for the tons from this delivery.
     * 
     */
    private @Nullable String registryUrl;
    /**
     * @return A supplier of carbon removal.
     * 
     */
    private @Nullable String supplier;

    private ClimateOrderDeliveryDetail() {}
    /**
     * @return Time at which the delivery occurred. Measured in seconds since the Unix epoch.
     * 
     */
    public Optional<Double> deliveredAt() {
        return Optional.ofNullable(this.deliveredAt);
    }
    /**
     * @return Specific location of this delivery.
     * 
     */
    public Optional<ClimateOrderDeliveryDetailLocation> location() {
        return Optional.ofNullable(this.location);
    }
    /**
     * @return Quantity of carbon removal supplied by this delivery.
     * 
     */
    public Optional<String> metricTons() {
        return Optional.ofNullable(this.metricTons);
    }
    /**
     * @return Once retired, a URL to the registry entry for the tons from this delivery.
     * 
     */
    public Optional<String> registryUrl() {
        return Optional.ofNullable(this.registryUrl);
    }
    /**
     * @return A supplier of carbon removal.
     * 
     */
    public Optional<String> supplier() {
        return Optional.ofNullable(this.supplier);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClimateOrderDeliveryDetail defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Double deliveredAt;
        private @Nullable ClimateOrderDeliveryDetailLocation location;
        private @Nullable String metricTons;
        private @Nullable String registryUrl;
        private @Nullable String supplier;
        public Builder() {}
        public Builder(ClimateOrderDeliveryDetail defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.deliveredAt = defaults.deliveredAt;
    	      this.location = defaults.location;
    	      this.metricTons = defaults.metricTons;
    	      this.registryUrl = defaults.registryUrl;
    	      this.supplier = defaults.supplier;
        }

        @CustomType.Setter
        public Builder deliveredAt(@Nullable Double deliveredAt) {

            this.deliveredAt = deliveredAt;
            return this;
        }
        @CustomType.Setter
        public Builder location(@Nullable ClimateOrderDeliveryDetailLocation location) {

            this.location = location;
            return this;
        }
        @CustomType.Setter
        public Builder metricTons(@Nullable String metricTons) {

            this.metricTons = metricTons;
            return this;
        }
        @CustomType.Setter
        public Builder registryUrl(@Nullable String registryUrl) {

            this.registryUrl = registryUrl;
            return this;
        }
        @CustomType.Setter
        public Builder supplier(@Nullable String supplier) {

            this.supplier = supplier;
            return this;
        }
        public ClimateOrderDeliveryDetail build() {
            final var _resultValue = new ClimateOrderDeliveryDetail();
            _resultValue.deliveredAt = deliveredAt;
            _resultValue.location = location;
            _resultValue.metricTons = metricTons;
            _resultValue.registryUrl = registryUrl;
            _resultValue.supplier = supplier;
            return _resultValue;
        }
    }
}
