// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class InvoiceItemProrationDetailsCreditedItemsInvoiceLineItemDetails {
    /**
     * @return The invoice id for the debited line item(s).
     * 
     */
    private @Nullable String invoice;
    /**
     * @return IDs of the debited invoice line item(s) on the invoice that correspond to the credit proration.
     * 
     */
    private @Nullable List<String> invoiceLineItems;

    private InvoiceItemProrationDetailsCreditedItemsInvoiceLineItemDetails() {}
    /**
     * @return The invoice id for the debited line item(s).
     * 
     */
    public Optional<String> invoice() {
        return Optional.ofNullable(this.invoice);
    }
    /**
     * @return IDs of the debited invoice line item(s) on the invoice that correspond to the credit proration.
     * 
     */
    public List<String> invoiceLineItems() {
        return this.invoiceLineItems == null ? List.of() : this.invoiceLineItems;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(InvoiceItemProrationDetailsCreditedItemsInvoiceLineItemDetails defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String invoice;
        private @Nullable List<String> invoiceLineItems;
        public Builder() {}
        public Builder(InvoiceItemProrationDetailsCreditedItemsInvoiceLineItemDetails defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.invoice = defaults.invoice;
    	      this.invoiceLineItems = defaults.invoiceLineItems;
        }

        @CustomType.Setter
        public Builder invoice(@Nullable String invoice) {

            this.invoice = invoice;
            return this;
        }
        @CustomType.Setter
        public Builder invoiceLineItems(@Nullable List<String> invoiceLineItems) {

            this.invoiceLineItems = invoiceLineItems;
            return this;
        }
        public Builder invoiceLineItems(String... invoiceLineItems) {
            return invoiceLineItems(List.of(invoiceLineItems));
        }
        public InvoiceItemProrationDetailsCreditedItemsInvoiceLineItemDetails build() {
            final var _resultValue = new InvoiceItemProrationDetailsCreditedItemsInvoiceLineItemDetails();
            _resultValue.invoice = invoice;
            _resultValue.invoiceLineItems = invoiceLineItems;
            return _resultValue;
        }
    }
}
