// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class IssuingDisputeEvidenceDuplicate {
    /**
     * @return (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Additional documentation supporting the dispute.
     * 
     */
    private @Nullable String additionalDocumentation;
    /**
     * @return (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Copy of the card statement showing that the product had already been paid for.
     * 
     */
    private @Nullable String cardStatement;
    /**
     * @return (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Copy of the receipt showing that the product had been paid for in cash.
     * 
     */
    private @Nullable String cashReceipt;
    /**
     * @return (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Image of the front and back of the check that was used to pay for the product.
     * 
     */
    private @Nullable String checkImage;
    /**
     * @return Explanation of why the cardholder is disputing this transaction.
     * 
     */
    private @Nullable String explanation;
    /**
     * @return Transaction (e.g., ipi_...) that the disputed transaction is a duplicate of. Of the two or more transactions that are copies of each other, this is original undisputed one.
     * 
     */
    private @Nullable String originalTransaction;

    private IssuingDisputeEvidenceDuplicate() {}
    /**
     * @return (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Additional documentation supporting the dispute.
     * 
     */
    public Optional<String> additionalDocumentation() {
        return Optional.ofNullable(this.additionalDocumentation);
    }
    /**
     * @return (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Copy of the card statement showing that the product had already been paid for.
     * 
     */
    public Optional<String> cardStatement() {
        return Optional.ofNullable(this.cardStatement);
    }
    /**
     * @return (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Copy of the receipt showing that the product had been paid for in cash.
     * 
     */
    public Optional<String> cashReceipt() {
        return Optional.ofNullable(this.cashReceipt);
    }
    /**
     * @return (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Image of the front and back of the check that was used to pay for the product.
     * 
     */
    public Optional<String> checkImage() {
        return Optional.ofNullable(this.checkImage);
    }
    /**
     * @return Explanation of why the cardholder is disputing this transaction.
     * 
     */
    public Optional<String> explanation() {
        return Optional.ofNullable(this.explanation);
    }
    /**
     * @return Transaction (e.g., ipi_...) that the disputed transaction is a duplicate of. Of the two or more transactions that are copies of each other, this is original undisputed one.
     * 
     */
    public Optional<String> originalTransaction() {
        return Optional.ofNullable(this.originalTransaction);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(IssuingDisputeEvidenceDuplicate defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String additionalDocumentation;
        private @Nullable String cardStatement;
        private @Nullable String cashReceipt;
        private @Nullable String checkImage;
        private @Nullable String explanation;
        private @Nullable String originalTransaction;
        public Builder() {}
        public Builder(IssuingDisputeEvidenceDuplicate defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.additionalDocumentation = defaults.additionalDocumentation;
    	      this.cardStatement = defaults.cardStatement;
    	      this.cashReceipt = defaults.cashReceipt;
    	      this.checkImage = defaults.checkImage;
    	      this.explanation = defaults.explanation;
    	      this.originalTransaction = defaults.originalTransaction;
        }

        @CustomType.Setter
        public Builder additionalDocumentation(@Nullable String additionalDocumentation) {

            this.additionalDocumentation = additionalDocumentation;
            return this;
        }
        @CustomType.Setter
        public Builder cardStatement(@Nullable String cardStatement) {

            this.cardStatement = cardStatement;
            return this;
        }
        @CustomType.Setter
        public Builder cashReceipt(@Nullable String cashReceipt) {

            this.cashReceipt = cashReceipt;
            return this;
        }
        @CustomType.Setter
        public Builder checkImage(@Nullable String checkImage) {

            this.checkImage = checkImage;
            return this;
        }
        @CustomType.Setter
        public Builder explanation(@Nullable String explanation) {

            this.explanation = explanation;
            return this;
        }
        @CustomType.Setter
        public Builder originalTransaction(@Nullable String originalTransaction) {

            this.originalTransaction = originalTransaction;
            return this;
        }
        public IssuingDisputeEvidenceDuplicate build() {
            final var _resultValue = new IssuingDisputeEvidenceDuplicate();
            _resultValue.additionalDocumentation = additionalDocumentation;
            _resultValue.cardStatement = cardStatement;
            _resultValue.cashReceipt = cashReceipt;
            _resultValue.checkImage = checkImage;
            _resultValue.explanation = explanation;
            _resultValue.originalTransaction = originalTransaction;
            return _resultValue;
        }
    }
}
