// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class IssuingPersonalizationDesignRejectionReasons {
    /**
     * @return The reason(s) the card logo was rejected.
     * 
     */
    private @Nullable List<String> cardLogos;
    /**
     * @return The reason(s) the carrier text was rejected.
     * 
     */
    private @Nullable List<String> carrierTexts;

    private IssuingPersonalizationDesignRejectionReasons() {}
    /**
     * @return The reason(s) the card logo was rejected.
     * 
     */
    public List<String> cardLogos() {
        return this.cardLogos == null ? List.of() : this.cardLogos;
    }
    /**
     * @return The reason(s) the carrier text was rejected.
     * 
     */
    public List<String> carrierTexts() {
        return this.carrierTexts == null ? List.of() : this.carrierTexts;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(IssuingPersonalizationDesignRejectionReasons defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> cardLogos;
        private @Nullable List<String> carrierTexts;
        public Builder() {}
        public Builder(IssuingPersonalizationDesignRejectionReasons defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cardLogos = defaults.cardLogos;
    	      this.carrierTexts = defaults.carrierTexts;
        }

        @CustomType.Setter
        public Builder cardLogos(@Nullable List<String> cardLogos) {

            this.cardLogos = cardLogos;
            return this;
        }
        public Builder cardLogos(String... cardLogos) {
            return cardLogos(List.of(cardLogos));
        }
        @CustomType.Setter
        public Builder carrierTexts(@Nullable List<String> carrierTexts) {

            this.carrierTexts = carrierTexts;
            return this;
        }
        public Builder carrierTexts(String... carrierTexts) {
            return carrierTexts(List.of(carrierTexts));
        }
        public IssuingPersonalizationDesignRejectionReasons build() {
            final var _resultValue = new IssuingPersonalizationDesignRejectionReasons();
            _resultValue.cardLogos = cardLogos;
            _resultValue.carrierTexts = carrierTexts;
            return _resultValue;
        }
    }
}
