// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class PaymentLinkAfterCompletionHostedConfirmation {
    /**
     * @return The custom message that is displayed to the customer after the purchase is complete.
     * 
     */
    private @Nullable String customMessage;

    private PaymentLinkAfterCompletionHostedConfirmation() {}
    /**
     * @return The custom message that is displayed to the customer after the purchase is complete.
     * 
     */
    public Optional<String> customMessage() {
        return Optional.ofNullable(this.customMessage);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PaymentLinkAfterCompletionHostedConfirmation defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String customMessage;
        public Builder() {}
        public Builder(PaymentLinkAfterCompletionHostedConfirmation defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.customMessage = defaults.customMessage;
        }

        @CustomType.Setter
        public Builder customMessage(@Nullable String customMessage) {

            this.customMessage = customMessage;
            return this;
        }
        public PaymentLinkAfterCompletionHostedConfirmation build() {
            final var _resultValue = new PaymentLinkAfterCompletionHostedConfirmation();
            _resultValue.customMessage = customMessage;
            return _resultValue;
        }
    }
}
