// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SourceCodeVerification {
    /**
     * @return The number of attempts remaining to authenticate the source object with a verification code.
     * 
     */
    private @Nullable Double attemptsRemaining;
    /**
     * @return The status of the code verification, either &lt;span pulumi-lang-nodejs=&#34;`pending`&#34; pulumi-lang-dotnet=&#34;`Pending`&#34; pulumi-lang-go=&#34;`pending`&#34; pulumi-lang-python=&#34;`pending`&#34; pulumi-lang-yaml=&#34;`pending`&#34; pulumi-lang-java=&#34;`pending`&#34; pulumi-lang-hcl=&#34;`pending`&#34;&gt;`pending`&lt;/span&gt; (awaiting verification, &lt;span pulumi-lang-nodejs=&#34;`attemptsRemaining`&#34; pulumi-lang-dotnet=&#34;`AttemptsRemaining`&#34; pulumi-lang-go=&#34;`attemptsRemaining`&#34; pulumi-lang-python=&#34;`attempts_remaining`&#34; pulumi-lang-yaml=&#34;`attemptsRemaining`&#34; pulumi-lang-java=&#34;`attemptsRemaining`&#34; pulumi-lang-hcl=&#34;`attempts_remaining`&#34;&gt;`attemptsRemaining`&lt;/span&gt; should be greater than 0), &lt;span pulumi-lang-nodejs=&#34;`succeeded`&#34; pulumi-lang-dotnet=&#34;`Succeeded`&#34; pulumi-lang-go=&#34;`succeeded`&#34; pulumi-lang-python=&#34;`succeeded`&#34; pulumi-lang-yaml=&#34;`succeeded`&#34; pulumi-lang-java=&#34;`succeeded`&#34; pulumi-lang-hcl=&#34;`succeeded`&#34;&gt;`succeeded`&lt;/span&gt; (successful verification) or &lt;span pulumi-lang-nodejs=&#34;`failed`&#34; pulumi-lang-dotnet=&#34;`Failed`&#34; pulumi-lang-go=&#34;`failed`&#34; pulumi-lang-python=&#34;`failed`&#34; pulumi-lang-yaml=&#34;`failed`&#34; pulumi-lang-java=&#34;`failed`&#34; pulumi-lang-hcl=&#34;`failed`&#34;&gt;`failed`&lt;/span&gt; (failed verification, cannot be verified anymore as &lt;span pulumi-lang-nodejs=&#34;`attemptsRemaining`&#34; pulumi-lang-dotnet=&#34;`AttemptsRemaining`&#34; pulumi-lang-go=&#34;`attemptsRemaining`&#34; pulumi-lang-python=&#34;`attempts_remaining`&#34; pulumi-lang-yaml=&#34;`attemptsRemaining`&#34; pulumi-lang-java=&#34;`attemptsRemaining`&#34; pulumi-lang-hcl=&#34;`attempts_remaining`&#34;&gt;`attemptsRemaining`&lt;/span&gt; should be 0).
     * 
     */
    private @Nullable String status;

    private SourceCodeVerification() {}
    /**
     * @return The number of attempts remaining to authenticate the source object with a verification code.
     * 
     */
    public Optional<Double> attemptsRemaining() {
        return Optional.ofNullable(this.attemptsRemaining);
    }
    /**
     * @return The status of the code verification, either &lt;span pulumi-lang-nodejs=&#34;`pending`&#34; pulumi-lang-dotnet=&#34;`Pending`&#34; pulumi-lang-go=&#34;`pending`&#34; pulumi-lang-python=&#34;`pending`&#34; pulumi-lang-yaml=&#34;`pending`&#34; pulumi-lang-java=&#34;`pending`&#34; pulumi-lang-hcl=&#34;`pending`&#34;&gt;`pending`&lt;/span&gt; (awaiting verification, &lt;span pulumi-lang-nodejs=&#34;`attemptsRemaining`&#34; pulumi-lang-dotnet=&#34;`AttemptsRemaining`&#34; pulumi-lang-go=&#34;`attemptsRemaining`&#34; pulumi-lang-python=&#34;`attempts_remaining`&#34; pulumi-lang-yaml=&#34;`attemptsRemaining`&#34; pulumi-lang-java=&#34;`attemptsRemaining`&#34; pulumi-lang-hcl=&#34;`attempts_remaining`&#34;&gt;`attemptsRemaining`&lt;/span&gt; should be greater than 0), &lt;span pulumi-lang-nodejs=&#34;`succeeded`&#34; pulumi-lang-dotnet=&#34;`Succeeded`&#34; pulumi-lang-go=&#34;`succeeded`&#34; pulumi-lang-python=&#34;`succeeded`&#34; pulumi-lang-yaml=&#34;`succeeded`&#34; pulumi-lang-java=&#34;`succeeded`&#34; pulumi-lang-hcl=&#34;`succeeded`&#34;&gt;`succeeded`&lt;/span&gt; (successful verification) or &lt;span pulumi-lang-nodejs=&#34;`failed`&#34; pulumi-lang-dotnet=&#34;`Failed`&#34; pulumi-lang-go=&#34;`failed`&#34; pulumi-lang-python=&#34;`failed`&#34; pulumi-lang-yaml=&#34;`failed`&#34; pulumi-lang-java=&#34;`failed`&#34; pulumi-lang-hcl=&#34;`failed`&#34;&gt;`failed`&lt;/span&gt; (failed verification, cannot be verified anymore as &lt;span pulumi-lang-nodejs=&#34;`attemptsRemaining`&#34; pulumi-lang-dotnet=&#34;`AttemptsRemaining`&#34; pulumi-lang-go=&#34;`attemptsRemaining`&#34; pulumi-lang-python=&#34;`attempts_remaining`&#34; pulumi-lang-yaml=&#34;`attemptsRemaining`&#34; pulumi-lang-java=&#34;`attemptsRemaining`&#34; pulumi-lang-hcl=&#34;`attempts_remaining`&#34;&gt;`attemptsRemaining`&lt;/span&gt; should be 0).
     * 
     */
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SourceCodeVerification defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Double attemptsRemaining;
        private @Nullable String status;
        public Builder() {}
        public Builder(SourceCodeVerification defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.attemptsRemaining = defaults.attemptsRemaining;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder attemptsRemaining(@Nullable Double attemptsRemaining) {

            this.attemptsRemaining = attemptsRemaining;
            return this;
        }
        @CustomType.Setter
        public Builder status(@Nullable String status) {

            this.status = status;
            return this;
        }
        public SourceCodeVerification build() {
            final var _resultValue = new SourceCodeVerification();
            _resultValue.attemptsRemaining = attemptsRemaining;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
