// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.stripe.outputs.SubscriptionPaymentSettingsPaymentMethodOptionsUpiMandateOptions;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SubscriptionPaymentSettingsPaymentMethodOptionsUpi {
    private @Nullable SubscriptionPaymentSettingsPaymentMethodOptionsUpiMandateOptions mandateOptions;

    private SubscriptionPaymentSettingsPaymentMethodOptionsUpi() {}
    public Optional<SubscriptionPaymentSettingsPaymentMethodOptionsUpiMandateOptions> mandateOptions() {
        return Optional.ofNullable(this.mandateOptions);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SubscriptionPaymentSettingsPaymentMethodOptionsUpi defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable SubscriptionPaymentSettingsPaymentMethodOptionsUpiMandateOptions mandateOptions;
        public Builder() {}
        public Builder(SubscriptionPaymentSettingsPaymentMethodOptionsUpi defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.mandateOptions = defaults.mandateOptions;
        }

        @CustomType.Setter
        public Builder mandateOptions(@Nullable SubscriptionPaymentSettingsPaymentMethodOptionsUpiMandateOptions mandateOptions) {

            this.mandateOptions = mandateOptions;
            return this;
        }
        public SubscriptionPaymentSettingsPaymentMethodOptionsUpi build() {
            final var _resultValue = new SubscriptionPaymentSettingsPaymentMethodOptionsUpi();
            _resultValue.mandateOptions = mandateOptions;
            return _resultValue;
        }
    }
}
