// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.stripe.outputs.TaxRegistrationCountryOptionsHrStandard;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class TaxRegistrationCountryOptionsHr {
    private @Nullable TaxRegistrationCountryOptionsHrStandard standard;
    /**
     * @return Type of registration in an EU country.
     * 
     */
    private String type;

    private TaxRegistrationCountryOptionsHr() {}
    public Optional<TaxRegistrationCountryOptionsHrStandard> standard() {
        return Optional.ofNullable(this.standard);
    }
    /**
     * @return Type of registration in an EU country.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TaxRegistrationCountryOptionsHr defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable TaxRegistrationCountryOptionsHrStandard standard;
        private String type;
        public Builder() {}
        public Builder(TaxRegistrationCountryOptionsHr defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.standard = defaults.standard;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder standard(@Nullable TaxRegistrationCountryOptionsHrStandard standard) {

            this.standard = standard;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("TaxRegistrationCountryOptionsHr", "type");
            }
            this.type = type;
            return this;
        }
        public TaxRegistrationCountryOptionsHr build() {
            final var _resultValue = new TaxRegistrationCountryOptionsHr();
            _resultValue.standard = standard;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
