// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class BillingPortalConfigurationFeatures
    {
        public readonly Outputs.BillingPortalConfigurationFeaturesCustomerUpdate? CustomerUpdate;
        public readonly Outputs.BillingPortalConfigurationFeaturesInvoiceHistory? InvoiceHistory;
        public readonly Outputs.BillingPortalConfigurationFeaturesPaymentMethodUpdate? PaymentMethodUpdate;
        public readonly Outputs.BillingPortalConfigurationFeaturesSubscriptionCancel? SubscriptionCancel;
        public readonly Outputs.BillingPortalConfigurationFeaturesSubscriptionUpdate? SubscriptionUpdate;

        [OutputConstructor]
        private BillingPortalConfigurationFeatures(
            Outputs.BillingPortalConfigurationFeaturesCustomerUpdate? customerUpdate,

            Outputs.BillingPortalConfigurationFeaturesInvoiceHistory? invoiceHistory,

            Outputs.BillingPortalConfigurationFeaturesPaymentMethodUpdate? paymentMethodUpdate,

            Outputs.BillingPortalConfigurationFeaturesSubscriptionCancel? subscriptionCancel,

            Outputs.BillingPortalConfigurationFeaturesSubscriptionUpdate? subscriptionUpdate)
        {
            CustomerUpdate = customerUpdate;
            InvoiceHistory = invoiceHistory;
            PaymentMethodUpdate = paymentMethodUpdate;
            SubscriptionCancel = subscriptionCancel;
            SubscriptionUpdate = subscriptionUpdate;
        }
    }
}
