// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class ChargeLevel3
    {
        public readonly string? CustomerReference;
        public readonly ImmutableArray<Outputs.ChargeLevel3LineItem> LineItems;
        public readonly string? MerchantReference;
        public readonly string? ShippingAddressZip;
        public readonly double? ShippingAmount;
        public readonly string? ShippingFromZip;

        [OutputConstructor]
        private ChargeLevel3(
            string? customerReference,

            ImmutableArray<Outputs.ChargeLevel3LineItem> lineItems,

            string? merchantReference,

            string? shippingAddressZip,

            double? shippingAmount,

            string? shippingFromZip)
        {
            CustomerReference = customerReference;
            LineItems = lineItems;
            MerchantReference = merchantReference;
            ShippingAddressZip = shippingAddressZip;
            ShippingAmount = shippingAmount;
            ShippingFromZip = shippingFromZip;
        }
    }
}
