// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class InvoiceItemProrationDetailsCreditedItems
    {
        /// <summary>
        /// When &lt;span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`" pulumi-lang-hcl="`type`"&gt;`type`&lt;/span&gt; is &lt;span pulumi-lang-nodejs="`invoiceItem`" pulumi-lang-dotnet="`InvoiceItem`" pulumi-lang-go="`invoiceItem`" pulumi-lang-python="`invoice_item`" pulumi-lang-yaml="`invoiceItem`" pulumi-lang-java="`invoiceItem`" pulumi-lang-hcl="`invoice_item`"&gt;`invoiceItem`&lt;/span&gt;, the invoice item id for the debited invoice item corresponding to this credit proration.
        /// </summary>
        public readonly string? InvoiceItem;
        public readonly Outputs.InvoiceItemProrationDetailsCreditedItemsInvoiceLineItemDetails? InvoiceLineItemDetails;
        /// <summary>
        /// Whether the credit references a pending invoice item or one or more invoice line items on an invoice.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private InvoiceItemProrationDetailsCreditedItems(
            string? invoiceItem,

            Outputs.InvoiceItemProrationDetailsCreditedItemsInvoiceLineItemDetails? invoiceLineItemDetails,

            string? type)
        {
            InvoiceItem = invoiceItem;
            InvoiceLineItemDetails = invoiceLineItemDetails;
            Type = type;
        }
    }
}
