// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class PaymentIntentPaymentMethodDataBacsDebit
    {
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Account number of the bank account that the funds will be debited from.
        /// </summary>
        public readonly string? AccountNumber;
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Sort code of the bank account. (e.g., `10-20-30`)
        /// </summary>
        public readonly string? SortCode;

        [OutputConstructor]
        private PaymentIntentPaymentMethodDataBacsDebit(
            string? accountNumber,

            string? sortCode)
        {
            AccountNumber = accountNumber;
            SortCode = sortCode;
        }
    }
}
