// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class PaymentMethodKlarna
    {
        /// <summary>
        /// The customer's date of birth, if provided.
        /// </summary>
        public readonly Outputs.PaymentMethodKlarnaDob? Dob;

        [OutputConstructor]
        private PaymentMethodKlarna(Outputs.PaymentMethodKlarnaDob? dob)
        {
            Dob = dob;
        }
    }
}
