// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class PaymentLinkRestrictionsCompletedSessions
    {
        /// <summary>
        /// The current number of checkout sessions that have been completed on the payment link which count towards the &lt;span pulumi-lang-nodejs="`completedSessions`" pulumi-lang-dotnet="`CompletedSessions`" pulumi-lang-go="`completedSessions`" pulumi-lang-python="`completed_sessions`" pulumi-lang-yaml="`completedSessions`" pulumi-lang-java="`completedSessions`" pulumi-lang-hcl="`completed_sessions`"&gt;`completedSessions`&lt;/span&gt; restriction to be met.
        /// </summary>
        public readonly double? Count;
        /// <summary>
        /// The maximum number of checkout sessions that can be completed for the &lt;span pulumi-lang-nodejs="`completedSessions`" pulumi-lang-dotnet="`CompletedSessions`" pulumi-lang-go="`completedSessions`" pulumi-lang-python="`completed_sessions`" pulumi-lang-yaml="`completedSessions`" pulumi-lang-java="`completedSessions`" pulumi-lang-hcl="`completed_sessions`"&gt;`completedSessions`&lt;/span&gt; restriction to be met.
        /// </summary>
        public readonly double Limit;

        [OutputConstructor]
        private PaymentLinkRestrictionsCompletedSessions(
            double? count,

            double limit)
        {
            Count = count;
            Limit = limit;
        }
    }
}
