// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class PaymentIntentPaymentMethodOptionsSepaDebitMandateOptions
    {
        /// <summary>
        /// Prefix used to generate the Mandate reference. Must be at most 12 characters long. Must consist of only uppercase letters, numbers, spaces, or the following special characters: '/', '_', '-', '&amp;', '.'. Cannot begin with 'STRIPE'.
        /// </summary>
        public readonly string? ReferencePrefix;

        [OutputConstructor]
        private PaymentIntentPaymentMethodOptionsSepaDebitMandateOptions(string? referencePrefix)
        {
            ReferencePrefix = referencePrefix;
        }
    }
}
