// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class PersonAddressKanji
    {
        /// <summary>
        /// City/Ward.
        /// </summary>
        public readonly string? City;
        /// <summary>
        /// Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
        /// </summary>
        public readonly string? Country;
        /// <summary>
        /// Block/Building number.
        /// </summary>
        public readonly string? Line1;
        /// <summary>
        /// Building details.
        /// </summary>
        public readonly string? Line2;
        /// <summary>
        /// ZIP or postal code.
        /// </summary>
        public readonly string? PostalCode;
        /// <summary>
        /// Prefecture.
        /// </summary>
        public readonly string? State;
        /// <summary>
        /// Town/cho-me.
        /// </summary>
        public readonly string? Town;

        [OutputConstructor]
        private PersonAddressKanji(
            string? city,

            string? country,

            string? line1,

            string? line2,

            string? postalCode,

            string? state,

            string? town)
        {
            City = city;
            Country = country;
            Line1 = line1;
            Line2 = line2;
            PostalCode = postalCode;
            State = state;
            Town = town;
        }
    }
}
