// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class SetupIntentPaymentMethodOptions
    {
        public readonly Outputs.SetupIntentPaymentMethodOptionsAcssDebit? AcssDebit;
        public readonly Outputs.SetupIntentPaymentMethodOptionsBacsDebit? BacsDebit;
        public readonly Outputs.SetupIntentPaymentMethodOptionsCard? Card;
        public readonly Outputs.SetupIntentPaymentMethodOptionsKlarna? Klarna;
        public readonly Outputs.SetupIntentPaymentMethodOptionsLink? Link;
        public readonly Outputs.SetupIntentPaymentMethodOptionsPaypal? Paypal;
        public readonly Outputs.SetupIntentPaymentMethodOptionsPayto? Payto;
        public readonly Outputs.SetupIntentPaymentMethodOptionsPix? Pix;
        public readonly Outputs.SetupIntentPaymentMethodOptionsSepaDebit? SepaDebit;
        public readonly Outputs.SetupIntentPaymentMethodOptionsUpi? Upi;
        public readonly Outputs.SetupIntentPaymentMethodOptionsUsBankAccount? UsBankAccount;

        [OutputConstructor]
        private SetupIntentPaymentMethodOptions(
            Outputs.SetupIntentPaymentMethodOptionsAcssDebit? acssDebit,

            Outputs.SetupIntentPaymentMethodOptionsBacsDebit? bacsDebit,

            Outputs.SetupIntentPaymentMethodOptionsCard? card,

            Outputs.SetupIntentPaymentMethodOptionsKlarna? klarna,

            Outputs.SetupIntentPaymentMethodOptionsLink? link,

            Outputs.SetupIntentPaymentMethodOptionsPaypal? paypal,

            Outputs.SetupIntentPaymentMethodOptionsPayto? payto,

            Outputs.SetupIntentPaymentMethodOptionsPix? pix,

            Outputs.SetupIntentPaymentMethodOptionsSepaDebit? sepaDebit,

            Outputs.SetupIntentPaymentMethodOptionsUpi? upi,

            Outputs.SetupIntentPaymentMethodOptionsUsBankAccount? usBankAccount)
        {
            AcssDebit = acssDebit;
            BacsDebit = bacsDebit;
            Card = card;
            Klarna = klarna;
            Link = link;
            Paypal = paypal;
            Payto = payto;
            Pix = pix;
            SepaDebit = sepaDebit;
            Upi = upi;
            UsBankAccount = usBankAccount;
        }
    }
}
