// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class SubscriptionAddInvoiceItem
    {
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Controls whether discounts apply to this invoice item. Defaults to true if no value is provided.
        /// </summary>
        public readonly bool? Discountable;
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// The coupons to redeem into discounts for the item.
        /// </summary>
        public readonly ImmutableArray<Outputs.SubscriptionAddInvoiceItemDiscount> Discounts;
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to &lt;span pulumi-lang-nodejs="`metadata`" pulumi-lang-dotnet="`Metadata`" pulumi-lang-go="`metadata`" pulumi-lang-python="`metadata`" pulumi-lang-yaml="`metadata`" pulumi-lang-java="`metadata`" pulumi-lang-hcl="`metadata`"&gt;`metadata`&lt;/span&gt;.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Metadata;
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// The period associated with this invoice item. If not set, `period.start.type` defaults to &lt;span pulumi-lang-nodejs="`maxItemPeriodStart`" pulumi-lang-dotnet="`MaxItemPeriodStart`" pulumi-lang-go="`maxItemPeriodStart`" pulumi-lang-python="`max_item_period_start`" pulumi-lang-yaml="`maxItemPeriodStart`" pulumi-lang-java="`maxItemPeriodStart`" pulumi-lang-hcl="`max_item_period_start`"&gt;`maxItemPeriodStart`&lt;/span&gt; and `period.end.type` defaults to &lt;span pulumi-lang-nodejs="`minItemPeriodEnd`" pulumi-lang-dotnet="`MinItemPeriodEnd`" pulumi-lang-go="`minItemPeriodEnd`" pulumi-lang-python="`min_item_period_end`" pulumi-lang-yaml="`minItemPeriodEnd`" pulumi-lang-java="`minItemPeriodEnd`" pulumi-lang-hcl="`min_item_period_end`"&gt;`minItemPeriodEnd`&lt;/span&gt;.
        /// </summary>
        public readonly Outputs.SubscriptionAddInvoiceItemPeriod? Period;
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// The ID of the price object. One of &lt;span pulumi-lang-nodejs="`price`" pulumi-lang-dotnet="`Price`" pulumi-lang-go="`price`" pulumi-lang-python="`price`" pulumi-lang-yaml="`price`" pulumi-lang-java="`price`" pulumi-lang-hcl="`price`"&gt;`price`&lt;/span&gt; or &lt;span pulumi-lang-nodejs="`priceData`" pulumi-lang-dotnet="`PriceData`" pulumi-lang-go="`priceData`" pulumi-lang-python="`price_data`" pulumi-lang-yaml="`priceData`" pulumi-lang-java="`priceData`" pulumi-lang-hcl="`price_data`"&gt;`priceData`&lt;/span&gt; is required.
        /// </summary>
        public readonly string? Price;
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Data used to generate a new [Price](https://docs.stripe.com/api/prices) object inline. One of &lt;span pulumi-lang-nodejs="`price`" pulumi-lang-dotnet="`Price`" pulumi-lang-go="`price`" pulumi-lang-python="`price`" pulumi-lang-yaml="`price`" pulumi-lang-java="`price`" pulumi-lang-hcl="`price`"&gt;`price`&lt;/span&gt; or &lt;span pulumi-lang-nodejs="`priceData`" pulumi-lang-dotnet="`PriceData`" pulumi-lang-go="`priceData`" pulumi-lang-python="`price_data`" pulumi-lang-yaml="`priceData`" pulumi-lang-java="`priceData`" pulumi-lang-hcl="`price_data`"&gt;`priceData`&lt;/span&gt; is required.
        /// </summary>
        public readonly Outputs.SubscriptionAddInvoiceItemPriceData? PriceData;
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Quantity for this item. Defaults to 1.
        /// </summary>
        public readonly double? Quantity;
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// The tax rates which apply to the item. When set, the &lt;span pulumi-lang-nodejs="`defaultTaxRates`" pulumi-lang-dotnet="`DefaultTaxRates`" pulumi-lang-go="`defaultTaxRates`" pulumi-lang-python="`default_tax_rates`" pulumi-lang-yaml="`defaultTaxRates`" pulumi-lang-java="`defaultTaxRates`" pulumi-lang-hcl="`default_tax_rates`"&gt;`defaultTaxRates`&lt;/span&gt; do not apply to this item.
        /// </summary>
        public readonly ImmutableArray<string> TaxRates;

        [OutputConstructor]
        private SubscriptionAddInvoiceItem(
            bool? discountable,

            ImmutableArray<Outputs.SubscriptionAddInvoiceItemDiscount> discounts,

            ImmutableDictionary<string, string>? metadata,

            Outputs.SubscriptionAddInvoiceItemPeriod? period,

            string? price,

            Outputs.SubscriptionAddInvoiceItemPriceData? priceData,

            double? quantity,

            ImmutableArray<string> taxRates)
        {
            Discountable = discountable;
            Discounts = discounts;
            Metadata = metadata;
            Period = period;
            Price = price;
            PriceData = priceData;
            Quantity = quantity;
            TaxRates = taxRates;
        }
    }
}
