// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class SubscriptionPaymentSettingsPaymentMethodOptionsCard
    {
        public readonly Outputs.SubscriptionPaymentSettingsPaymentMethodOptionsCardMandateOptions? MandateOptions;
        /// <summary>
        /// Selected network to process this Subscription on. Depends on the available networks of the card attached to the Subscription. Can be only set confirm-time.
        /// </summary>
        public readonly string? Network;
        /// <summary>
        /// We strongly recommend that you rely on our SCA Engine to automatically prompt your customers for authentication based on risk level and [other requirements](https://docs.stripe.com/strong-customer-authentication). However, if you wish to request 3D Secure based on logic from your own fraud engine, provide this option. Read our guide on [manually requesting 3D Secure](https://docs.stripe.com/payments/3d-secure/authentication-flow#manual-three-ds) for more information on how this configuration interacts with Radar and our SCA Engine.
        /// </summary>
        public readonly string? RequestThreeDSecure;

        [OutputConstructor]
        private SubscriptionPaymentSettingsPaymentMethodOptionsCard(
            Outputs.SubscriptionPaymentSettingsPaymentMethodOptionsCardMandateOptions? mandateOptions,

            string? network,

            string? requestThreeDSecure)
        {
            MandateOptions = mandateOptions;
            Network = network;
            RequestThreeDSecure = requestThreeDSecure;
        }
    }
}
