// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class TaxIdOwner
    {
        /// <summary>
        /// The account being referenced when &lt;span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`" pulumi-lang-hcl="`type`"&gt;`type`&lt;/span&gt; is &lt;span pulumi-lang-nodejs="`account`" pulumi-lang-dotnet="`Account`" pulumi-lang-go="`account`" pulumi-lang-python="`account`" pulumi-lang-yaml="`account`" pulumi-lang-java="`account`" pulumi-lang-hcl="`account`"&gt;`account`&lt;/span&gt;.
        /// </summary>
        public readonly string? Account;
        /// <summary>
        /// The Connect Application being referenced when &lt;span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`" pulumi-lang-hcl="`type`"&gt;`type`&lt;/span&gt; is &lt;span pulumi-lang-nodejs="`application`" pulumi-lang-dotnet="`Application`" pulumi-lang-go="`application`" pulumi-lang-python="`application`" pulumi-lang-yaml="`application`" pulumi-lang-java="`application`" pulumi-lang-hcl="`application`"&gt;`application`&lt;/span&gt;.
        /// </summary>
        public readonly string? Application;
        /// <summary>
        /// The customer being referenced when &lt;span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`" pulumi-lang-hcl="`type`"&gt;`type`&lt;/span&gt; is &lt;span pulumi-lang-nodejs="`customer`" pulumi-lang-dotnet="`Customer`" pulumi-lang-go="`customer`" pulumi-lang-python="`customer`" pulumi-lang-yaml="`customer`" pulumi-lang-java="`customer`" pulumi-lang-hcl="`customer`"&gt;`customer`&lt;/span&gt;.
        /// </summary>
        public readonly string? Customer;
        /// <summary>
        /// The Account representing the customer being referenced when &lt;span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`" pulumi-lang-hcl="`type`"&gt;`type`&lt;/span&gt; is &lt;span pulumi-lang-nodejs="`customer`" pulumi-lang-dotnet="`Customer`" pulumi-lang-go="`customer`" pulumi-lang-python="`customer`" pulumi-lang-yaml="`customer`" pulumi-lang-java="`customer`" pulumi-lang-hcl="`customer`"&gt;`customer`&lt;/span&gt;.
        /// </summary>
        public readonly string? CustomerAccount;
        /// <summary>
        /// Type of owner referenced.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private TaxIdOwner(
            string? account,

            string? application,

            string? customer,

            string? customerAccount,

            string? type)
        {
            Account = account;
            Application = application;
            Customer = customer;
            CustomerAccount = customerAccount;
            Type = type;
        }
    }
}
