// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class TerminalReaderActionCollectInputsInput
    {
        /// <summary>
        /// Default text of input being collected.
        /// </summary>
        public readonly Outputs.TerminalReaderActionCollectInputsInputCustomText? CustomText;
        /// <summary>
        /// Information about a email being collected using a reader
        /// </summary>
        public readonly Outputs.TerminalReaderActionCollectInputsInputEmail? Email;
        /// <summary>
        /// Information about a number being collected using a reader
        /// </summary>
        public readonly Outputs.TerminalReaderActionCollectInputsInputNumeric? Numeric;
        /// <summary>
        /// Information about a phone number being collected using a reader
        /// </summary>
        public readonly Outputs.TerminalReaderActionCollectInputsInputPhone? Phone;
        /// <summary>
        /// Indicate that this input is required, disabling the skip button.
        /// </summary>
        public readonly bool? Required;
        /// <summary>
        /// Information about a selection being collected using a reader
        /// </summary>
        public readonly Outputs.TerminalReaderActionCollectInputsInputSelection? Selection;
        /// <summary>
        /// Information about a signature being collected using a reader
        /// </summary>
        public readonly Outputs.TerminalReaderActionCollectInputsInputSignature? Signature;
        /// <summary>
        /// Indicate that this input was skipped by the user.
        /// </summary>
        public readonly bool? Skipped;
        /// <summary>
        /// Information about text being collected using a reader
        /// </summary>
        public readonly Outputs.TerminalReaderActionCollectInputsInputText? Text;
        /// <summary>
        /// List of toggles being collected. Values are present if collection is complete.
        /// </summary>
        public readonly ImmutableArray<Outputs.TerminalReaderActionCollectInputsInputToggle> Toggles;
        /// <summary>
        /// Type of input being collected.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private TerminalReaderActionCollectInputsInput(
            Outputs.TerminalReaderActionCollectInputsInputCustomText? customText,

            Outputs.TerminalReaderActionCollectInputsInputEmail? email,

            Outputs.TerminalReaderActionCollectInputsInputNumeric? numeric,

            Outputs.TerminalReaderActionCollectInputsInputPhone? phone,

            bool? required,

            Outputs.TerminalReaderActionCollectInputsInputSelection? selection,

            Outputs.TerminalReaderActionCollectInputsInputSignature? signature,

            bool? skipped,

            Outputs.TerminalReaderActionCollectInputsInputText? text,

            ImmutableArray<Outputs.TerminalReaderActionCollectInputsInputToggle> toggles,

            string? type)
        {
            CustomText = customText;
            Email = email;
            Numeric = numeric;
            Phone = phone;
            Required = required;
            Selection = selection;
            Signature = signature;
            Skipped = skipped;
            Text = text;
            Toggles = toggles;
            Type = type;
        }
    }
}
