// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class TerminalReaderActionCollectInputsInputCustomText
    {
        /// <summary>
        /// Customize the default description for this input
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// Customize the default label for this input's skip button
        /// </summary>
        public readonly string? SkipButton;
        /// <summary>
        /// Customize the default label for this input's submit button
        /// </summary>
        public readonly string? SubmitButton;
        /// <summary>
        /// Customize the default title for this input
        /// </summary>
        public readonly string? Title;

        [OutputConstructor]
        private TerminalReaderActionCollectInputsInputCustomText(
            string? description,

            string? skipButton,

            string? submitButton,

            string? title)
        {
            Description = description;
            SkipButton = skipButton;
            SubmitButton = submitButton;
            Title = title;
        }
    }
}
