// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.stripe.inputs.BillingMeterCustomerMappingArgs;
import com.pulumi.stripe.inputs.BillingMeterDefaultAggregationArgs;
import com.pulumi.stripe.inputs.BillingMeterValueSettingsArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BillingMeterState extends com.pulumi.resources.ResourceArgs {

    public static final BillingMeterState Empty = new BillingMeterState();

    /**
     * Fields that specify how to map a meter event to a customer.
     * 
     */
    @Import(name="customerMapping")
    private @Nullable Output<BillingMeterCustomerMappingArgs> customerMapping;

    /**
     * @return Fields that specify how to map a meter event to a customer.
     * 
     */
    public Optional<Output<BillingMeterCustomerMappingArgs>> customerMapping() {
        return Optional.ofNullable(this.customerMapping);
    }

    /**
     * The default settings to aggregate a meter&#39;s events with.
     * 
     */
    @Import(name="defaultAggregation")
    private @Nullable Output<BillingMeterDefaultAggregationArgs> defaultAggregation;

    /**
     * @return The default settings to aggregate a meter&#39;s events with.
     * 
     */
    public Optional<Output<BillingMeterDefaultAggregationArgs>> defaultAggregation() {
        return Optional.ofNullable(this.defaultAggregation);
    }

    /**
     * Set of keys that will be used to group meter events by. Each key must be present in the event payload.
     * 
     */
    @Import(name="dimensionPayloadKeys")
    private @Nullable Output<List<String>> dimensionPayloadKeys;

    /**
     * @return Set of keys that will be used to group meter events by. Each key must be present in the event payload.
     * 
     */
    public Optional<Output<List<String>>> dimensionPayloadKeys() {
        return Optional.ofNullable(this.dimensionPayloadKeys);
    }

    /**
     * The meter’s name. Not visible to the customer.
     * 
     */
    @Import(name="displayName")
    private @Nullable Output<String> displayName;

    /**
     * @return The meter’s name. Not visible to the customer.
     * 
     */
    public Optional<Output<String>> displayName() {
        return Optional.ofNullable(this.displayName);
    }

    /**
     * The name of the meter event to record usage for. Corresponds with the &lt;span pulumi-lang-nodejs=&#34;`eventName`&#34; pulumi-lang-dotnet=&#34;`EventName`&#34; pulumi-lang-go=&#34;`eventName`&#34; pulumi-lang-python=&#34;`event_name`&#34; pulumi-lang-yaml=&#34;`eventName`&#34; pulumi-lang-java=&#34;`eventName`&#34; pulumi-lang-hcl=&#34;`event_name`&#34;&gt;`eventName`&lt;/span&gt; field on meter events.
     * 
     */
    @Import(name="eventName")
    private @Nullable Output<String> eventName;

    /**
     * @return The name of the meter event to record usage for. Corresponds with the &lt;span pulumi-lang-nodejs=&#34;`eventName`&#34; pulumi-lang-dotnet=&#34;`EventName`&#34; pulumi-lang-go=&#34;`eventName`&#34; pulumi-lang-python=&#34;`event_name`&#34; pulumi-lang-yaml=&#34;`eventName`&#34; pulumi-lang-java=&#34;`eventName`&#34; pulumi-lang-hcl=&#34;`event_name`&#34;&gt;`eventName`&lt;/span&gt; field on meter events.
     * 
     */
    public Optional<Output<String>> eventName() {
        return Optional.ofNullable(this.eventName);
    }

    /**
     * The time window which meter events have been pre-aggregated for, if any.
     * 
     */
    @Import(name="eventTimeWindow")
    private @Nullable Output<String> eventTimeWindow;

    /**
     * @return The time window which meter events have been pre-aggregated for, if any.
     * 
     */
    public Optional<Output<String>> eventTimeWindow() {
        return Optional.ofNullable(this.eventTimeWindow);
    }

    /**
     * The meter&#39;s status.
     * 
     */
    @Import(name="status")
    private @Nullable Output<String> status;

    /**
     * @return The meter&#39;s status.
     * 
     */
    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * Fields that specify how to calculate a meter event&#39;s value.
     * 
     */
    @Import(name="valueSettings")
    private @Nullable Output<BillingMeterValueSettingsArgs> valueSettings;

    /**
     * @return Fields that specify how to calculate a meter event&#39;s value.
     * 
     */
    public Optional<Output<BillingMeterValueSettingsArgs>> valueSettings() {
        return Optional.ofNullable(this.valueSettings);
    }

    private BillingMeterState() {}

    private BillingMeterState(BillingMeterState $) {
        this.customerMapping = $.customerMapping;
        this.defaultAggregation = $.defaultAggregation;
        this.dimensionPayloadKeys = $.dimensionPayloadKeys;
        this.displayName = $.displayName;
        this.eventName = $.eventName;
        this.eventTimeWindow = $.eventTimeWindow;
        this.status = $.status;
        this.valueSettings = $.valueSettings;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BillingMeterState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BillingMeterState $;

        public Builder() {
            $ = new BillingMeterState();
        }

        public Builder(BillingMeterState defaults) {
            $ = new BillingMeterState(Objects.requireNonNull(defaults));
        }

        /**
         * @param customerMapping Fields that specify how to map a meter event to a customer.
         * 
         * @return builder
         * 
         */
        public Builder customerMapping(@Nullable Output<BillingMeterCustomerMappingArgs> customerMapping) {
            $.customerMapping = customerMapping;
            return this;
        }

        /**
         * @param customerMapping Fields that specify how to map a meter event to a customer.
         * 
         * @return builder
         * 
         */
        public Builder customerMapping(BillingMeterCustomerMappingArgs customerMapping) {
            return customerMapping(Output.of(customerMapping));
        }

        /**
         * @param defaultAggregation The default settings to aggregate a meter&#39;s events with.
         * 
         * @return builder
         * 
         */
        public Builder defaultAggregation(@Nullable Output<BillingMeterDefaultAggregationArgs> defaultAggregation) {
            $.defaultAggregation = defaultAggregation;
            return this;
        }

        /**
         * @param defaultAggregation The default settings to aggregate a meter&#39;s events with.
         * 
         * @return builder
         * 
         */
        public Builder defaultAggregation(BillingMeterDefaultAggregationArgs defaultAggregation) {
            return defaultAggregation(Output.of(defaultAggregation));
        }

        /**
         * @param dimensionPayloadKeys Set of keys that will be used to group meter events by. Each key must be present in the event payload.
         * 
         * @return builder
         * 
         */
        public Builder dimensionPayloadKeys(@Nullable Output<List<String>> dimensionPayloadKeys) {
            $.dimensionPayloadKeys = dimensionPayloadKeys;
            return this;
        }

        /**
         * @param dimensionPayloadKeys Set of keys that will be used to group meter events by. Each key must be present in the event payload.
         * 
         * @return builder
         * 
         */
        public Builder dimensionPayloadKeys(List<String> dimensionPayloadKeys) {
            return dimensionPayloadKeys(Output.of(dimensionPayloadKeys));
        }

        /**
         * @param dimensionPayloadKeys Set of keys that will be used to group meter events by. Each key must be present in the event payload.
         * 
         * @return builder
         * 
         */
        public Builder dimensionPayloadKeys(String... dimensionPayloadKeys) {
            return dimensionPayloadKeys(List.of(dimensionPayloadKeys));
        }

        /**
         * @param displayName The meter’s name. Not visible to the customer.
         * 
         * @return builder
         * 
         */
        public Builder displayName(@Nullable Output<String> displayName) {
            $.displayName = displayName;
            return this;
        }

        /**
         * @param displayName The meter’s name. Not visible to the customer.
         * 
         * @return builder
         * 
         */
        public Builder displayName(String displayName) {
            return displayName(Output.of(displayName));
        }

        /**
         * @param eventName The name of the meter event to record usage for. Corresponds with the &lt;span pulumi-lang-nodejs=&#34;`eventName`&#34; pulumi-lang-dotnet=&#34;`EventName`&#34; pulumi-lang-go=&#34;`eventName`&#34; pulumi-lang-python=&#34;`event_name`&#34; pulumi-lang-yaml=&#34;`eventName`&#34; pulumi-lang-java=&#34;`eventName`&#34; pulumi-lang-hcl=&#34;`event_name`&#34;&gt;`eventName`&lt;/span&gt; field on meter events.
         * 
         * @return builder
         * 
         */
        public Builder eventName(@Nullable Output<String> eventName) {
            $.eventName = eventName;
            return this;
        }

        /**
         * @param eventName The name of the meter event to record usage for. Corresponds with the &lt;span pulumi-lang-nodejs=&#34;`eventName`&#34; pulumi-lang-dotnet=&#34;`EventName`&#34; pulumi-lang-go=&#34;`eventName`&#34; pulumi-lang-python=&#34;`event_name`&#34; pulumi-lang-yaml=&#34;`eventName`&#34; pulumi-lang-java=&#34;`eventName`&#34; pulumi-lang-hcl=&#34;`event_name`&#34;&gt;`eventName`&lt;/span&gt; field on meter events.
         * 
         * @return builder
         * 
         */
        public Builder eventName(String eventName) {
            return eventName(Output.of(eventName));
        }

        /**
         * @param eventTimeWindow The time window which meter events have been pre-aggregated for, if any.
         * 
         * @return builder
         * 
         */
        public Builder eventTimeWindow(@Nullable Output<String> eventTimeWindow) {
            $.eventTimeWindow = eventTimeWindow;
            return this;
        }

        /**
         * @param eventTimeWindow The time window which meter events have been pre-aggregated for, if any.
         * 
         * @return builder
         * 
         */
        public Builder eventTimeWindow(String eventTimeWindow) {
            return eventTimeWindow(Output.of(eventTimeWindow));
        }

        /**
         * @param status The meter&#39;s status.
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        /**
         * @param status The meter&#39;s status.
         * 
         * @return builder
         * 
         */
        public Builder status(String status) {
            return status(Output.of(status));
        }

        /**
         * @param valueSettings Fields that specify how to calculate a meter event&#39;s value.
         * 
         * @return builder
         * 
         */
        public Builder valueSettings(@Nullable Output<BillingMeterValueSettingsArgs> valueSettings) {
            $.valueSettings = valueSettings;
            return this;
        }

        /**
         * @param valueSettings Fields that specify how to calculate a meter event&#39;s value.
         * 
         * @return builder
         * 
         */
        public Builder valueSettings(BillingMeterValueSettingsArgs valueSettings) {
            return valueSettings(Output.of(valueSettings));
        }

        public BillingMeterState build() {
            return $;
        }
    }

}
