// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;


public final class CouponCurrencyOptionArgs extends com.pulumi.resources.ResourceArgs {

    public static final CouponCurrencyOptionArgs Empty = new CouponCurrencyOptionArgs();

    /**
     * A positive integer representing the amount to subtract from an invoice total.
     * 
     */
    @Import(name="amountOff", required=true)
    private Output<Double> amountOff;

    /**
     * @return A positive integer representing the amount to subtract from an invoice total.
     * 
     */
    public Output<Double> amountOff() {
        return this.amountOff;
    }

    @Import(name="key", required=true)
    private Output<String> key;

    public Output<String> key() {
        return this.key;
    }

    private CouponCurrencyOptionArgs() {}

    private CouponCurrencyOptionArgs(CouponCurrencyOptionArgs $) {
        this.amountOff = $.amountOff;
        this.key = $.key;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CouponCurrencyOptionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CouponCurrencyOptionArgs $;

        public Builder() {
            $ = new CouponCurrencyOptionArgs();
        }

        public Builder(CouponCurrencyOptionArgs defaults) {
            $ = new CouponCurrencyOptionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param amountOff A positive integer representing the amount to subtract from an invoice total.
         * 
         * @return builder
         * 
         */
        public Builder amountOff(Output<Double> amountOff) {
            $.amountOff = amountOff;
            return this;
        }

        /**
         * @param amountOff A positive integer representing the amount to subtract from an invoice total.
         * 
         * @return builder
         * 
         */
        public Builder amountOff(Double amountOff) {
            return amountOff(Output.of(amountOff));
        }

        public Builder key(Output<String> key) {
            $.key = key;
            return this;
        }

        public Builder key(String key) {
            return key(Output.of(key));
        }

        public CouponCurrencyOptionArgs build() {
            if ($.amountOff == null) {
                throw new MissingRequiredPropertyException("CouponCurrencyOptionArgs", "amountOff");
            }
            if ($.key == null) {
                throw new MissingRequiredPropertyException("CouponCurrencyOptionArgs", "key");
            }
            return $;
        }
    }

}
