// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CustomerTaxLocationArgs extends com.pulumi.resources.ResourceArgs {

    public static final CustomerTaxLocationArgs Empty = new CustomerTaxLocationArgs();

    /**
     * The identified tax country of the customer.
     * 
     */
    @Import(name="country")
    private @Nullable Output<String> country;

    /**
     * @return The identified tax country of the customer.
     * 
     */
    public Optional<Output<String>> country() {
        return Optional.ofNullable(this.country);
    }

    /**
     * The data source used to infer the customer&#39;s location.
     * 
     */
    @Import(name="source")
    private @Nullable Output<String> source;

    /**
     * @return The data source used to infer the customer&#39;s location.
     * 
     */
    public Optional<Output<String>> source() {
        return Optional.ofNullable(this.source);
    }

    /**
     * The identified tax state, county, province, or region of the customer.
     * 
     */
    @Import(name="state")
    private @Nullable Output<String> state;

    /**
     * @return The identified tax state, county, province, or region of the customer.
     * 
     */
    public Optional<Output<String>> state() {
        return Optional.ofNullable(this.state);
    }

    private CustomerTaxLocationArgs() {}

    private CustomerTaxLocationArgs(CustomerTaxLocationArgs $) {
        this.country = $.country;
        this.source = $.source;
        this.state = $.state;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CustomerTaxLocationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CustomerTaxLocationArgs $;

        public Builder() {
            $ = new CustomerTaxLocationArgs();
        }

        public Builder(CustomerTaxLocationArgs defaults) {
            $ = new CustomerTaxLocationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param country The identified tax country of the customer.
         * 
         * @return builder
         * 
         */
        public Builder country(@Nullable Output<String> country) {
            $.country = country;
            return this;
        }

        /**
         * @param country The identified tax country of the customer.
         * 
         * @return builder
         * 
         */
        public Builder country(String country) {
            return country(Output.of(country));
        }

        /**
         * @param source The data source used to infer the customer&#39;s location.
         * 
         * @return builder
         * 
         */
        public Builder source(@Nullable Output<String> source) {
            $.source = source;
            return this;
        }

        /**
         * @param source The data source used to infer the customer&#39;s location.
         * 
         * @return builder
         * 
         */
        public Builder source(String source) {
            return source(Output.of(source));
        }

        /**
         * @param state The identified tax state, county, province, or region of the customer.
         * 
         * @return builder
         * 
         */
        public Builder state(@Nullable Output<String> state) {
            $.state = state;
            return this;
        }

        /**
         * @param state The identified tax state, county, province, or region of the customer.
         * 
         * @return builder
         * 
         */
        public Builder state(String state) {
            return state(Output.of(state));
        }

        public CustomerTaxLocationArgs build() {
            return $;
        }
    }

}
