// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CustomerInvoiceSettingRenderingOptionArgs extends com.pulumi.resources.ResourceArgs {

    public static final CustomerInvoiceSettingRenderingOptionArgs Empty = new CustomerInvoiceSettingRenderingOptionArgs();

    /**
     * How line-item prices and amounts will be displayed with respect to tax on invoice PDFs.
     * 
     */
    @Import(name="amountTaxDisplay")
    private @Nullable Output<String> amountTaxDisplay;

    /**
     * @return How line-item prices and amounts will be displayed with respect to tax on invoice PDFs.
     * 
     */
    public Optional<Output<String>> amountTaxDisplay() {
        return Optional.ofNullable(this.amountTaxDisplay);
    }

    /**
     * ID of the invoice rendering template to be used for this customer&#39;s invoices. If set, the template will be used on all invoices for this customer unless a template is set directly on the invoice.
     * 
     */
    @Import(name="template")
    private @Nullable Output<String> template;

    /**
     * @return ID of the invoice rendering template to be used for this customer&#39;s invoices. If set, the template will be used on all invoices for this customer unless a template is set directly on the invoice.
     * 
     */
    public Optional<Output<String>> template() {
        return Optional.ofNullable(this.template);
    }

    private CustomerInvoiceSettingRenderingOptionArgs() {}

    private CustomerInvoiceSettingRenderingOptionArgs(CustomerInvoiceSettingRenderingOptionArgs $) {
        this.amountTaxDisplay = $.amountTaxDisplay;
        this.template = $.template;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CustomerInvoiceSettingRenderingOptionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CustomerInvoiceSettingRenderingOptionArgs $;

        public Builder() {
            $ = new CustomerInvoiceSettingRenderingOptionArgs();
        }

        public Builder(CustomerInvoiceSettingRenderingOptionArgs defaults) {
            $ = new CustomerInvoiceSettingRenderingOptionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param amountTaxDisplay How line-item prices and amounts will be displayed with respect to tax on invoice PDFs.
         * 
         * @return builder
         * 
         */
        public Builder amountTaxDisplay(@Nullable Output<String> amountTaxDisplay) {
            $.amountTaxDisplay = amountTaxDisplay;
            return this;
        }

        /**
         * @param amountTaxDisplay How line-item prices and amounts will be displayed with respect to tax on invoice PDFs.
         * 
         * @return builder
         * 
         */
        public Builder amountTaxDisplay(String amountTaxDisplay) {
            return amountTaxDisplay(Output.of(amountTaxDisplay));
        }

        /**
         * @param template ID of the invoice rendering template to be used for this customer&#39;s invoices. If set, the template will be used on all invoices for this customer unless a template is set directly on the invoice.
         * 
         * @return builder
         * 
         */
        public Builder template(@Nullable Output<String> template) {
            $.template = template;
            return this;
        }

        /**
         * @param template ID of the invoice rendering template to be used for this customer&#39;s invoices. If set, the template will be used on all invoices for this customer unless a template is set directly on the invoice.
         * 
         * @return builder
         * 
         */
        public Builder template(String template) {
            return template(Output.of(template));
        }

        public CustomerInvoiceSettingRenderingOptionArgs build() {
            return $;
        }
    }

}
