// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.stripe.inputs.InvoiceItemParentSubscriptionDetailsArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class InvoiceItemParentArgs extends com.pulumi.resources.ResourceArgs {

    public static final InvoiceItemParentArgs Empty = new InvoiceItemParentArgs();

    /**
     * Details about the subscription that generated this invoice item
     * 
     */
    @Import(name="subscriptionDetails")
    private @Nullable Output<InvoiceItemParentSubscriptionDetailsArgs> subscriptionDetails;

    /**
     * @return Details about the subscription that generated this invoice item
     * 
     */
    public Optional<Output<InvoiceItemParentSubscriptionDetailsArgs>> subscriptionDetails() {
        return Optional.ofNullable(this.subscriptionDetails);
    }

    /**
     * The type of parent that generated this invoice item
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return The type of parent that generated this invoice item
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private InvoiceItemParentArgs() {}

    private InvoiceItemParentArgs(InvoiceItemParentArgs $) {
        this.subscriptionDetails = $.subscriptionDetails;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(InvoiceItemParentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private InvoiceItemParentArgs $;

        public Builder() {
            $ = new InvoiceItemParentArgs();
        }

        public Builder(InvoiceItemParentArgs defaults) {
            $ = new InvoiceItemParentArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param subscriptionDetails Details about the subscription that generated this invoice item
         * 
         * @return builder
         * 
         */
        public Builder subscriptionDetails(@Nullable Output<InvoiceItemParentSubscriptionDetailsArgs> subscriptionDetails) {
            $.subscriptionDetails = subscriptionDetails;
            return this;
        }

        /**
         * @param subscriptionDetails Details about the subscription that generated this invoice item
         * 
         * @return builder
         * 
         */
        public Builder subscriptionDetails(InvoiceItemParentSubscriptionDetailsArgs subscriptionDetails) {
            return subscriptionDetails(Output.of(subscriptionDetails));
        }

        /**
         * @param type The type of parent that generated this invoice item
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The type of parent that generated this invoice item
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public InvoiceItemParentArgs build() {
            return $;
        }
    }

}
