// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IssuingCardWalletsGooglePayArgs extends com.pulumi.resources.ResourceArgs {

    public static final IssuingCardWalletsGooglePayArgs Empty = new IssuingCardWalletsGooglePayArgs();

    /**
     * Google Pay Eligibility
     * 
     */
    @Import(name="eligible")
    private @Nullable Output<Boolean> eligible;

    /**
     * @return Google Pay Eligibility
     * 
     */
    public Optional<Output<Boolean>> eligible() {
        return Optional.ofNullable(this.eligible);
    }

    /**
     * Reason the card is ineligible for Google Pay
     * 
     */
    @Import(name="ineligibleReason")
    private @Nullable Output<String> ineligibleReason;

    /**
     * @return Reason the card is ineligible for Google Pay
     * 
     */
    public Optional<Output<String>> ineligibleReason() {
        return Optional.ofNullable(this.ineligibleReason);
    }

    private IssuingCardWalletsGooglePayArgs() {}

    private IssuingCardWalletsGooglePayArgs(IssuingCardWalletsGooglePayArgs $) {
        this.eligible = $.eligible;
        this.ineligibleReason = $.ineligibleReason;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IssuingCardWalletsGooglePayArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IssuingCardWalletsGooglePayArgs $;

        public Builder() {
            $ = new IssuingCardWalletsGooglePayArgs();
        }

        public Builder(IssuingCardWalletsGooglePayArgs defaults) {
            $ = new IssuingCardWalletsGooglePayArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param eligible Google Pay Eligibility
         * 
         * @return builder
         * 
         */
        public Builder eligible(@Nullable Output<Boolean> eligible) {
            $.eligible = eligible;
            return this;
        }

        /**
         * @param eligible Google Pay Eligibility
         * 
         * @return builder
         * 
         */
        public Builder eligible(Boolean eligible) {
            return eligible(Output.of(eligible));
        }

        /**
         * @param ineligibleReason Reason the card is ineligible for Google Pay
         * 
         * @return builder
         * 
         */
        public Builder ineligibleReason(@Nullable Output<String> ineligibleReason) {
            $.ineligibleReason = ineligibleReason;
            return this;
        }

        /**
         * @param ineligibleReason Reason the card is ineligible for Google Pay
         * 
         * @return builder
         * 
         */
        public Builder ineligibleReason(String ineligibleReason) {
            return ineligibleReason(Output.of(ineligibleReason));
        }

        public IssuingCardWalletsGooglePayArgs build() {
            return $;
        }
    }

}
