// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.stripe.inputs.PaymentLinkAfterCompletionHostedConfirmationArgs;
import com.pulumi.stripe.inputs.PaymentLinkAfterCompletionRedirectArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PaymentLinkAfterCompletionArgs extends com.pulumi.resources.ResourceArgs {

    public static final PaymentLinkAfterCompletionArgs Empty = new PaymentLinkAfterCompletionArgs();

    @Import(name="hostedConfirmation")
    private @Nullable Output<PaymentLinkAfterCompletionHostedConfirmationArgs> hostedConfirmation;

    public Optional<Output<PaymentLinkAfterCompletionHostedConfirmationArgs>> hostedConfirmation() {
        return Optional.ofNullable(this.hostedConfirmation);
    }

    @Import(name="redirect")
    private @Nullable Output<PaymentLinkAfterCompletionRedirectArgs> redirect;

    public Optional<Output<PaymentLinkAfterCompletionRedirectArgs>> redirect() {
        return Optional.ofNullable(this.redirect);
    }

    /**
     * The specified behavior after the purchase is complete.
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return The specified behavior after the purchase is complete.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private PaymentLinkAfterCompletionArgs() {}

    private PaymentLinkAfterCompletionArgs(PaymentLinkAfterCompletionArgs $) {
        this.hostedConfirmation = $.hostedConfirmation;
        this.redirect = $.redirect;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PaymentLinkAfterCompletionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PaymentLinkAfterCompletionArgs $;

        public Builder() {
            $ = new PaymentLinkAfterCompletionArgs();
        }

        public Builder(PaymentLinkAfterCompletionArgs defaults) {
            $ = new PaymentLinkAfterCompletionArgs(Objects.requireNonNull(defaults));
        }

        public Builder hostedConfirmation(@Nullable Output<PaymentLinkAfterCompletionHostedConfirmationArgs> hostedConfirmation) {
            $.hostedConfirmation = hostedConfirmation;
            return this;
        }

        public Builder hostedConfirmation(PaymentLinkAfterCompletionHostedConfirmationArgs hostedConfirmation) {
            return hostedConfirmation(Output.of(hostedConfirmation));
        }

        public Builder redirect(@Nullable Output<PaymentLinkAfterCompletionRedirectArgs> redirect) {
            $.redirect = redirect;
            return this;
        }

        public Builder redirect(PaymentLinkAfterCompletionRedirectArgs redirect) {
            return redirect(Output.of(redirect));
        }

        /**
         * @param type The specified behavior after the purchase is complete.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The specified behavior after the purchase is complete.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public PaymentLinkAfterCompletionArgs build() {
            if ($.type == null) {
                throw new MissingRequiredPropertyException("PaymentLinkAfterCompletionArgs", "type");
            }
            return $;
        }
    }

}
