// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataAcssDebitArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataAuBecsDebitArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataBacsDebitArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataBillingDetailsArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataBoletoArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataEpsArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataFpxArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataIdealArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataKlarnaArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataNaverPayArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataNzBankAccountArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataP24Args;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataPaytoArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataRadarOptionsArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataSepaDebitArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataSofortArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataUpiArgs;
import com.pulumi.stripe.inputs.PaymentIntentPaymentMethodDataUsBankAccountArgs;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PaymentIntentPaymentMethodDataArgs extends com.pulumi.resources.ResourceArgs {

    public static final PaymentIntentPaymentMethodDataArgs Empty = new PaymentIntentPaymentMethodDataArgs();

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an &lt;span pulumi-lang-nodejs=&#34;`acssDebit`&#34; pulumi-lang-dotnet=&#34;`AcssDebit`&#34; pulumi-lang-go=&#34;`acssDebit`&#34; pulumi-lang-python=&#34;`acss_debit`&#34; pulumi-lang-yaml=&#34;`acssDebit`&#34; pulumi-lang-java=&#34;`acssDebit`&#34; pulumi-lang-hcl=&#34;`acss_debit`&#34;&gt;`acssDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the ACSS Debit payment method.
     * 
     */
    @Import(name="acssDebit")
    private @Nullable Output<PaymentIntentPaymentMethodDataAcssDebitArgs> acssDebit;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an &lt;span pulumi-lang-nodejs=&#34;`acssDebit`&#34; pulumi-lang-dotnet=&#34;`AcssDebit`&#34; pulumi-lang-go=&#34;`acssDebit`&#34; pulumi-lang-python=&#34;`acss_debit`&#34; pulumi-lang-yaml=&#34;`acssDebit`&#34; pulumi-lang-java=&#34;`acssDebit`&#34; pulumi-lang-hcl=&#34;`acss_debit`&#34;&gt;`acssDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the ACSS Debit payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataAcssDebitArgs>> acssDebit() {
        return Optional.ofNullable(this.acssDebit);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to &lt;span pulumi-lang-nodejs=&#34;`unspecified`&#34; pulumi-lang-dotnet=&#34;`Unspecified`&#34; pulumi-lang-go=&#34;`unspecified`&#34; pulumi-lang-python=&#34;`unspecified`&#34; pulumi-lang-yaml=&#34;`unspecified`&#34; pulumi-lang-java=&#34;`unspecified`&#34; pulumi-lang-hcl=&#34;`unspecified`&#34;&gt;`unspecified`&lt;/span&gt;.
     * 
     */
    @Import(name="allowRedisplay")
    private @Nullable Output<String> allowRedisplay;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to &lt;span pulumi-lang-nodejs=&#34;`unspecified`&#34; pulumi-lang-dotnet=&#34;`Unspecified`&#34; pulumi-lang-go=&#34;`unspecified`&#34; pulumi-lang-python=&#34;`unspecified`&#34; pulumi-lang-yaml=&#34;`unspecified`&#34; pulumi-lang-java=&#34;`unspecified`&#34; pulumi-lang-hcl=&#34;`unspecified`&#34;&gt;`unspecified`&lt;/span&gt;.
     * 
     */
    public Optional<Output<String>> allowRedisplay() {
        return Optional.ofNullable(this.allowRedisplay);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an &lt;span pulumi-lang-nodejs=&#34;`auBecsDebit`&#34; pulumi-lang-dotnet=&#34;`AuBecsDebit`&#34; pulumi-lang-go=&#34;`auBecsDebit`&#34; pulumi-lang-python=&#34;`au_becs_debit`&#34; pulumi-lang-yaml=&#34;`auBecsDebit`&#34; pulumi-lang-java=&#34;`auBecsDebit`&#34; pulumi-lang-hcl=&#34;`au_becs_debit`&#34;&gt;`auBecsDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the bank account.
     * 
     */
    @Import(name="auBecsDebit")
    private @Nullable Output<PaymentIntentPaymentMethodDataAuBecsDebitArgs> auBecsDebit;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an &lt;span pulumi-lang-nodejs=&#34;`auBecsDebit`&#34; pulumi-lang-dotnet=&#34;`AuBecsDebit`&#34; pulumi-lang-go=&#34;`auBecsDebit`&#34; pulumi-lang-python=&#34;`au_becs_debit`&#34; pulumi-lang-yaml=&#34;`auBecsDebit`&#34; pulumi-lang-java=&#34;`auBecsDebit`&#34; pulumi-lang-hcl=&#34;`au_becs_debit`&#34;&gt;`auBecsDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the bank account.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataAuBecsDebitArgs>> auBecsDebit() {
        return Optional.ofNullable(this.auBecsDebit);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`bacsDebit`&#34; pulumi-lang-dotnet=&#34;`BacsDebit`&#34; pulumi-lang-go=&#34;`bacsDebit`&#34; pulumi-lang-python=&#34;`bacs_debit`&#34; pulumi-lang-yaml=&#34;`bacsDebit`&#34; pulumi-lang-java=&#34;`bacsDebit`&#34; pulumi-lang-hcl=&#34;`bacs_debit`&#34;&gt;`bacsDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the Bacs Direct Debit bank account.
     * 
     */
    @Import(name="bacsDebit")
    private @Nullable Output<PaymentIntentPaymentMethodDataBacsDebitArgs> bacsDebit;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`bacsDebit`&#34; pulumi-lang-dotnet=&#34;`BacsDebit`&#34; pulumi-lang-go=&#34;`bacsDebit`&#34; pulumi-lang-python=&#34;`bacs_debit`&#34; pulumi-lang-yaml=&#34;`bacsDebit`&#34; pulumi-lang-java=&#34;`bacsDebit`&#34; pulumi-lang-hcl=&#34;`bacs_debit`&#34;&gt;`bacsDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the Bacs Direct Debit bank account.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataBacsDebitArgs>> bacsDebit() {
        return Optional.ofNullable(this.bacsDebit);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Billing information associated with the PaymentMethod that may be used or required by particular types of payment methods.
     * 
     */
    @Import(name="billingDetails")
    private @Nullable Output<PaymentIntentPaymentMethodDataBillingDetailsArgs> billingDetails;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Billing information associated with the PaymentMethod that may be used or required by particular types of payment methods.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataBillingDetailsArgs>> billingDetails() {
        return Optional.ofNullable(this.billingDetails);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`boleto`&#34; pulumi-lang-dotnet=&#34;`Boleto`&#34; pulumi-lang-go=&#34;`boleto`&#34; pulumi-lang-python=&#34;`boleto`&#34; pulumi-lang-yaml=&#34;`boleto`&#34; pulumi-lang-java=&#34;`boleto`&#34; pulumi-lang-hcl=&#34;`boleto`&#34;&gt;`boleto`&lt;/span&gt; PaymentMethod, this hash contains details about the Boleto payment method.
     * 
     */
    @Import(name="boleto")
    private @Nullable Output<PaymentIntentPaymentMethodDataBoletoArgs> boleto;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`boleto`&#34; pulumi-lang-dotnet=&#34;`Boleto`&#34; pulumi-lang-go=&#34;`boleto`&#34; pulumi-lang-python=&#34;`boleto`&#34; pulumi-lang-yaml=&#34;`boleto`&#34; pulumi-lang-java=&#34;`boleto`&#34; pulumi-lang-hcl=&#34;`boleto`&#34;&gt;`boleto`&lt;/span&gt; PaymentMethod, this hash contains details about the Boleto payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataBoletoArgs>> boleto() {
        return Optional.ofNullable(this.boleto);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an &lt;span pulumi-lang-nodejs=&#34;`eps`&#34; pulumi-lang-dotnet=&#34;`Eps`&#34; pulumi-lang-go=&#34;`eps`&#34; pulumi-lang-python=&#34;`eps`&#34; pulumi-lang-yaml=&#34;`eps`&#34; pulumi-lang-java=&#34;`eps`&#34; pulumi-lang-hcl=&#34;`eps`&#34;&gt;`eps`&lt;/span&gt; PaymentMethod, this hash contains details about the EPS payment method.
     * 
     */
    @Import(name="eps")
    private @Nullable Output<PaymentIntentPaymentMethodDataEpsArgs> eps;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an &lt;span pulumi-lang-nodejs=&#34;`eps`&#34; pulumi-lang-dotnet=&#34;`Eps`&#34; pulumi-lang-go=&#34;`eps`&#34; pulumi-lang-python=&#34;`eps`&#34; pulumi-lang-yaml=&#34;`eps`&#34; pulumi-lang-java=&#34;`eps`&#34; pulumi-lang-hcl=&#34;`eps`&#34;&gt;`eps`&lt;/span&gt; PaymentMethod, this hash contains details about the EPS payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataEpsArgs>> eps() {
        return Optional.ofNullable(this.eps);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an &lt;span pulumi-lang-nodejs=&#34;`fpx`&#34; pulumi-lang-dotnet=&#34;`Fpx`&#34; pulumi-lang-go=&#34;`fpx`&#34; pulumi-lang-python=&#34;`fpx`&#34; pulumi-lang-yaml=&#34;`fpx`&#34; pulumi-lang-java=&#34;`fpx`&#34; pulumi-lang-hcl=&#34;`fpx`&#34;&gt;`fpx`&lt;/span&gt; PaymentMethod, this hash contains details about the FPX payment method.
     * 
     */
    @Import(name="fpx")
    private @Nullable Output<PaymentIntentPaymentMethodDataFpxArgs> fpx;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an &lt;span pulumi-lang-nodejs=&#34;`fpx`&#34; pulumi-lang-dotnet=&#34;`Fpx`&#34; pulumi-lang-go=&#34;`fpx`&#34; pulumi-lang-python=&#34;`fpx`&#34; pulumi-lang-yaml=&#34;`fpx`&#34; pulumi-lang-java=&#34;`fpx`&#34; pulumi-lang-hcl=&#34;`fpx`&#34;&gt;`fpx`&lt;/span&gt; PaymentMethod, this hash contains details about the FPX payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataFpxArgs>> fpx() {
        return Optional.ofNullable(this.fpx);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an &lt;span pulumi-lang-nodejs=&#34;`ideal`&#34; pulumi-lang-dotnet=&#34;`Ideal`&#34; pulumi-lang-go=&#34;`ideal`&#34; pulumi-lang-python=&#34;`ideal`&#34; pulumi-lang-yaml=&#34;`ideal`&#34; pulumi-lang-java=&#34;`ideal`&#34; pulumi-lang-hcl=&#34;`ideal`&#34;&gt;`ideal`&lt;/span&gt; PaymentMethod, this hash contains details about the iDEAL payment method.
     * 
     */
    @Import(name="ideal")
    private @Nullable Output<PaymentIntentPaymentMethodDataIdealArgs> ideal;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an &lt;span pulumi-lang-nodejs=&#34;`ideal`&#34; pulumi-lang-dotnet=&#34;`Ideal`&#34; pulumi-lang-go=&#34;`ideal`&#34; pulumi-lang-python=&#34;`ideal`&#34; pulumi-lang-yaml=&#34;`ideal`&#34; pulumi-lang-java=&#34;`ideal`&#34; pulumi-lang-hcl=&#34;`ideal`&#34;&gt;`ideal`&lt;/span&gt; PaymentMethod, this hash contains details about the iDEAL payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataIdealArgs>> ideal() {
        return Optional.ofNullable(this.ideal);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`klarna`&#34; pulumi-lang-dotnet=&#34;`Klarna`&#34; pulumi-lang-go=&#34;`klarna`&#34; pulumi-lang-python=&#34;`klarna`&#34; pulumi-lang-yaml=&#34;`klarna`&#34; pulumi-lang-java=&#34;`klarna`&#34; pulumi-lang-hcl=&#34;`klarna`&#34;&gt;`klarna`&lt;/span&gt; PaymentMethod, this hash contains details about the Klarna payment method.
     * 
     */
    @Import(name="klarna")
    private @Nullable Output<PaymentIntentPaymentMethodDataKlarnaArgs> klarna;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`klarna`&#34; pulumi-lang-dotnet=&#34;`Klarna`&#34; pulumi-lang-go=&#34;`klarna`&#34; pulumi-lang-python=&#34;`klarna`&#34; pulumi-lang-yaml=&#34;`klarna`&#34; pulumi-lang-java=&#34;`klarna`&#34; pulumi-lang-hcl=&#34;`klarna`&#34;&gt;`klarna`&lt;/span&gt; PaymentMethod, this hash contains details about the Klarna payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataKlarnaArgs>> klarna() {
        return Optional.ofNullable(this.klarna);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to &lt;span pulumi-lang-nodejs=&#34;`metadata`&#34; pulumi-lang-dotnet=&#34;`Metadata`&#34; pulumi-lang-go=&#34;`metadata`&#34; pulumi-lang-python=&#34;`metadata`&#34; pulumi-lang-yaml=&#34;`metadata`&#34; pulumi-lang-java=&#34;`metadata`&#34; pulumi-lang-hcl=&#34;`metadata`&#34;&gt;`metadata`&lt;/span&gt;.
     * 
     */
    @Import(name="metadata")
    private @Nullable Output<Map<String,String>> metadata;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to &lt;span pulumi-lang-nodejs=&#34;`metadata`&#34; pulumi-lang-dotnet=&#34;`Metadata`&#34; pulumi-lang-go=&#34;`metadata`&#34; pulumi-lang-python=&#34;`metadata`&#34; pulumi-lang-yaml=&#34;`metadata`&#34; pulumi-lang-java=&#34;`metadata`&#34; pulumi-lang-hcl=&#34;`metadata`&#34;&gt;`metadata`&lt;/span&gt;.
     * 
     */
    public Optional<Output<Map<String,String>>> metadata() {
        return Optional.ofNullable(this.metadata);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`naverPay`&#34; pulumi-lang-dotnet=&#34;`NaverPay`&#34; pulumi-lang-go=&#34;`naverPay`&#34; pulumi-lang-python=&#34;`naver_pay`&#34; pulumi-lang-yaml=&#34;`naverPay`&#34; pulumi-lang-java=&#34;`naverPay`&#34; pulumi-lang-hcl=&#34;`naver_pay`&#34;&gt;`naverPay`&lt;/span&gt; PaymentMethod, this hash contains details about the Naver Pay payment method.
     * 
     */
    @Import(name="naverPay")
    private @Nullable Output<PaymentIntentPaymentMethodDataNaverPayArgs> naverPay;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`naverPay`&#34; pulumi-lang-dotnet=&#34;`NaverPay`&#34; pulumi-lang-go=&#34;`naverPay`&#34; pulumi-lang-python=&#34;`naver_pay`&#34; pulumi-lang-yaml=&#34;`naverPay`&#34; pulumi-lang-java=&#34;`naverPay`&#34; pulumi-lang-hcl=&#34;`naver_pay`&#34;&gt;`naverPay`&lt;/span&gt; PaymentMethod, this hash contains details about the Naver Pay payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataNaverPayArgs>> naverPay() {
        return Optional.ofNullable(this.naverPay);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an&lt;span pulumi-lang-nodejs=&#34; nzBankAccount &#34; pulumi-lang-dotnet=&#34; NzBankAccount &#34; pulumi-lang-go=&#34; nzBankAccount &#34; pulumi-lang-python=&#34; nz_bank_account &#34; pulumi-lang-yaml=&#34; nzBankAccount &#34; pulumi-lang-java=&#34; nzBankAccount &#34; pulumi-lang-hcl=&#34; nz_bank_account &#34;&gt; nzBankAccount &lt;/span&gt;PaymentMethod, this hash contains details about the&lt;span pulumi-lang-nodejs=&#34; nzBankAccount &#34; pulumi-lang-dotnet=&#34; NzBankAccount &#34; pulumi-lang-go=&#34; nzBankAccount &#34; pulumi-lang-python=&#34; nz_bank_account &#34; pulumi-lang-yaml=&#34; nzBankAccount &#34; pulumi-lang-java=&#34; nzBankAccount &#34; pulumi-lang-hcl=&#34; nz_bank_account &#34;&gt; nzBankAccount &lt;/span&gt;payment method.
     * 
     */
    @Import(name="nzBankAccount")
    private @Nullable Output<PaymentIntentPaymentMethodDataNzBankAccountArgs> nzBankAccount;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an&lt;span pulumi-lang-nodejs=&#34; nzBankAccount &#34; pulumi-lang-dotnet=&#34; NzBankAccount &#34; pulumi-lang-go=&#34; nzBankAccount &#34; pulumi-lang-python=&#34; nz_bank_account &#34; pulumi-lang-yaml=&#34; nzBankAccount &#34; pulumi-lang-java=&#34; nzBankAccount &#34; pulumi-lang-hcl=&#34; nz_bank_account &#34;&gt; nzBankAccount &lt;/span&gt;PaymentMethod, this hash contains details about the&lt;span pulumi-lang-nodejs=&#34; nzBankAccount &#34; pulumi-lang-dotnet=&#34; NzBankAccount &#34; pulumi-lang-go=&#34; nzBankAccount &#34; pulumi-lang-python=&#34; nz_bank_account &#34; pulumi-lang-yaml=&#34; nzBankAccount &#34; pulumi-lang-java=&#34; nzBankAccount &#34; pulumi-lang-hcl=&#34; nz_bank_account &#34;&gt; nzBankAccount &lt;/span&gt;payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataNzBankAccountArgs>> nzBankAccount() {
        return Optional.ofNullable(this.nzBankAccount);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`p24`&#34; pulumi-lang-dotnet=&#34;`P24`&#34; pulumi-lang-go=&#34;`p24`&#34; pulumi-lang-python=&#34;`p24`&#34; pulumi-lang-yaml=&#34;`p24`&#34; pulumi-lang-java=&#34;`p24`&#34; pulumi-lang-hcl=&#34;`p24`&#34;&gt;`p24`&lt;/span&gt; PaymentMethod, this hash contains details about the P24 payment method.
     * 
     */
    @Import(name="p24")
    private @Nullable Output<PaymentIntentPaymentMethodDataP24Args> p24;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`p24`&#34; pulumi-lang-dotnet=&#34;`P24`&#34; pulumi-lang-go=&#34;`p24`&#34; pulumi-lang-python=&#34;`p24`&#34; pulumi-lang-yaml=&#34;`p24`&#34; pulumi-lang-java=&#34;`p24`&#34; pulumi-lang-hcl=&#34;`p24`&#34;&gt;`p24`&lt;/span&gt; PaymentMethod, this hash contains details about the P24 payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataP24Args>> p24() {
        return Optional.ofNullable(this.p24);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`payto`&#34; pulumi-lang-dotnet=&#34;`Payto`&#34; pulumi-lang-go=&#34;`payto`&#34; pulumi-lang-python=&#34;`payto`&#34; pulumi-lang-yaml=&#34;`payto`&#34; pulumi-lang-java=&#34;`payto`&#34; pulumi-lang-hcl=&#34;`payto`&#34;&gt;`payto`&lt;/span&gt; PaymentMethod, this hash contains details about the PayTo payment method.
     * 
     */
    @Import(name="payto")
    private @Nullable Output<PaymentIntentPaymentMethodDataPaytoArgs> payto;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`payto`&#34; pulumi-lang-dotnet=&#34;`Payto`&#34; pulumi-lang-go=&#34;`payto`&#34; pulumi-lang-python=&#34;`payto`&#34; pulumi-lang-yaml=&#34;`payto`&#34; pulumi-lang-java=&#34;`payto`&#34; pulumi-lang-hcl=&#34;`payto`&#34;&gt;`payto`&lt;/span&gt; PaymentMethod, this hash contains details about the PayTo payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataPaytoArgs>> payto() {
        return Optional.ofNullable(this.payto);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Options to configure Radar. See [Radar Session](https://docs.stripe.com/radar/radar-session) for more information.
     * 
     */
    @Import(name="radarOptions")
    private @Nullable Output<PaymentIntentPaymentMethodDataRadarOptionsArgs> radarOptions;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Options to configure Radar. See [Radar Session](https://docs.stripe.com/radar/radar-session) for more information.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataRadarOptionsArgs>> radarOptions() {
        return Optional.ofNullable(this.radarOptions);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`sepaDebit`&#34; pulumi-lang-dotnet=&#34;`SepaDebit`&#34; pulumi-lang-go=&#34;`sepaDebit`&#34; pulumi-lang-python=&#34;`sepa_debit`&#34; pulumi-lang-yaml=&#34;`sepaDebit`&#34; pulumi-lang-java=&#34;`sepaDebit`&#34; pulumi-lang-hcl=&#34;`sepa_debit`&#34;&gt;`sepaDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the SEPA debit bank account.
     * 
     */
    @Import(name="sepaDebit")
    private @Nullable Output<PaymentIntentPaymentMethodDataSepaDebitArgs> sepaDebit;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`sepaDebit`&#34; pulumi-lang-dotnet=&#34;`SepaDebit`&#34; pulumi-lang-go=&#34;`sepaDebit`&#34; pulumi-lang-python=&#34;`sepa_debit`&#34; pulumi-lang-yaml=&#34;`sepaDebit`&#34; pulumi-lang-java=&#34;`sepaDebit`&#34; pulumi-lang-hcl=&#34;`sepa_debit`&#34;&gt;`sepaDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the SEPA debit bank account.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataSepaDebitArgs>> sepaDebit() {
        return Optional.ofNullable(this.sepaDebit);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`sofort`&#34; pulumi-lang-dotnet=&#34;`Sofort`&#34; pulumi-lang-go=&#34;`sofort`&#34; pulumi-lang-python=&#34;`sofort`&#34; pulumi-lang-yaml=&#34;`sofort`&#34; pulumi-lang-java=&#34;`sofort`&#34; pulumi-lang-hcl=&#34;`sofort`&#34;&gt;`sofort`&lt;/span&gt; PaymentMethod, this hash contains details about the SOFORT payment method.
     * 
     */
    @Import(name="sofort")
    private @Nullable Output<PaymentIntentPaymentMethodDataSofortArgs> sofort;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`sofort`&#34; pulumi-lang-dotnet=&#34;`Sofort`&#34; pulumi-lang-go=&#34;`sofort`&#34; pulumi-lang-python=&#34;`sofort`&#34; pulumi-lang-yaml=&#34;`sofort`&#34; pulumi-lang-java=&#34;`sofort`&#34; pulumi-lang-hcl=&#34;`sofort`&#34;&gt;`sofort`&lt;/span&gt; PaymentMethod, this hash contains details about the SOFORT payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataSofortArgs>> sofort() {
        return Optional.ofNullable(this.sofort);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`upi`&#34; pulumi-lang-dotnet=&#34;`Upi`&#34; pulumi-lang-go=&#34;`upi`&#34; pulumi-lang-python=&#34;`upi`&#34; pulumi-lang-yaml=&#34;`upi`&#34; pulumi-lang-java=&#34;`upi`&#34; pulumi-lang-hcl=&#34;`upi`&#34;&gt;`upi`&lt;/span&gt; PaymentMethod, this hash contains details about the UPI payment method.
     * 
     */
    @Import(name="upi")
    private @Nullable Output<PaymentIntentPaymentMethodDataUpiArgs> upi;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is a &lt;span pulumi-lang-nodejs=&#34;`upi`&#34; pulumi-lang-dotnet=&#34;`Upi`&#34; pulumi-lang-go=&#34;`upi`&#34; pulumi-lang-python=&#34;`upi`&#34; pulumi-lang-yaml=&#34;`upi`&#34; pulumi-lang-java=&#34;`upi`&#34; pulumi-lang-hcl=&#34;`upi`&#34;&gt;`upi`&lt;/span&gt; PaymentMethod, this hash contains details about the UPI payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataUpiArgs>> upi() {
        return Optional.ofNullable(this.upi);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an &lt;span pulumi-lang-nodejs=&#34;`usBankAccount`&#34; pulumi-lang-dotnet=&#34;`UsBankAccount`&#34; pulumi-lang-go=&#34;`usBankAccount`&#34; pulumi-lang-python=&#34;`us_bank_account`&#34; pulumi-lang-yaml=&#34;`usBankAccount`&#34; pulumi-lang-java=&#34;`usBankAccount`&#34; pulumi-lang-hcl=&#34;`us_bank_account`&#34;&gt;`usBankAccount`&lt;/span&gt; PaymentMethod, this hash contains details about the US bank account payment method.
     * 
     */
    @Import(name="usBankAccount")
    private @Nullable Output<PaymentIntentPaymentMethodDataUsBankAccountArgs> usBankAccount;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If this is an &lt;span pulumi-lang-nodejs=&#34;`usBankAccount`&#34; pulumi-lang-dotnet=&#34;`UsBankAccount`&#34; pulumi-lang-go=&#34;`usBankAccount`&#34; pulumi-lang-python=&#34;`us_bank_account`&#34; pulumi-lang-yaml=&#34;`usBankAccount`&#34; pulumi-lang-java=&#34;`usBankAccount`&#34; pulumi-lang-hcl=&#34;`us_bank_account`&#34;&gt;`usBankAccount`&lt;/span&gt; PaymentMethod, this hash contains details about the US bank account payment method.
     * 
     */
    public Optional<Output<PaymentIntentPaymentMethodDataUsBankAccountArgs>> usBankAccount() {
        return Optional.ofNullable(this.usBankAccount);
    }

    private PaymentIntentPaymentMethodDataArgs() {}

    private PaymentIntentPaymentMethodDataArgs(PaymentIntentPaymentMethodDataArgs $) {
        this.acssDebit = $.acssDebit;
        this.allowRedisplay = $.allowRedisplay;
        this.auBecsDebit = $.auBecsDebit;
        this.bacsDebit = $.bacsDebit;
        this.billingDetails = $.billingDetails;
        this.boleto = $.boleto;
        this.eps = $.eps;
        this.fpx = $.fpx;
        this.ideal = $.ideal;
        this.klarna = $.klarna;
        this.metadata = $.metadata;
        this.naverPay = $.naverPay;
        this.nzBankAccount = $.nzBankAccount;
        this.p24 = $.p24;
        this.payto = $.payto;
        this.radarOptions = $.radarOptions;
        this.sepaDebit = $.sepaDebit;
        this.sofort = $.sofort;
        this.type = $.type;
        this.upi = $.upi;
        this.usBankAccount = $.usBankAccount;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PaymentIntentPaymentMethodDataArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PaymentIntentPaymentMethodDataArgs $;

        public Builder() {
            $ = new PaymentIntentPaymentMethodDataArgs();
        }

        public Builder(PaymentIntentPaymentMethodDataArgs defaults) {
            $ = new PaymentIntentPaymentMethodDataArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param acssDebit **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an &lt;span pulumi-lang-nodejs=&#34;`acssDebit`&#34; pulumi-lang-dotnet=&#34;`AcssDebit`&#34; pulumi-lang-go=&#34;`acssDebit`&#34; pulumi-lang-python=&#34;`acss_debit`&#34; pulumi-lang-yaml=&#34;`acssDebit`&#34; pulumi-lang-java=&#34;`acssDebit`&#34; pulumi-lang-hcl=&#34;`acss_debit`&#34;&gt;`acssDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the ACSS Debit payment method.
         * 
         * @return builder
         * 
         */
        public Builder acssDebit(@Nullable Output<PaymentIntentPaymentMethodDataAcssDebitArgs> acssDebit) {
            $.acssDebit = acssDebit;
            return this;
        }

        /**
         * @param acssDebit **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an &lt;span pulumi-lang-nodejs=&#34;`acssDebit`&#34; pulumi-lang-dotnet=&#34;`AcssDebit`&#34; pulumi-lang-go=&#34;`acssDebit`&#34; pulumi-lang-python=&#34;`acss_debit`&#34; pulumi-lang-yaml=&#34;`acssDebit`&#34; pulumi-lang-java=&#34;`acssDebit`&#34; pulumi-lang-hcl=&#34;`acss_debit`&#34;&gt;`acssDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the ACSS Debit payment method.
         * 
         * @return builder
         * 
         */
        public Builder acssDebit(PaymentIntentPaymentMethodDataAcssDebitArgs acssDebit) {
            return acssDebit(Output.of(acssDebit));
        }

        /**
         * @param allowRedisplay **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to &lt;span pulumi-lang-nodejs=&#34;`unspecified`&#34; pulumi-lang-dotnet=&#34;`Unspecified`&#34; pulumi-lang-go=&#34;`unspecified`&#34; pulumi-lang-python=&#34;`unspecified`&#34; pulumi-lang-yaml=&#34;`unspecified`&#34; pulumi-lang-java=&#34;`unspecified`&#34; pulumi-lang-hcl=&#34;`unspecified`&#34;&gt;`unspecified`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder allowRedisplay(@Nullable Output<String> allowRedisplay) {
            $.allowRedisplay = allowRedisplay;
            return this;
        }

        /**
         * @param allowRedisplay **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to &lt;span pulumi-lang-nodejs=&#34;`unspecified`&#34; pulumi-lang-dotnet=&#34;`Unspecified`&#34; pulumi-lang-go=&#34;`unspecified`&#34; pulumi-lang-python=&#34;`unspecified`&#34; pulumi-lang-yaml=&#34;`unspecified`&#34; pulumi-lang-java=&#34;`unspecified`&#34; pulumi-lang-hcl=&#34;`unspecified`&#34;&gt;`unspecified`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder allowRedisplay(String allowRedisplay) {
            return allowRedisplay(Output.of(allowRedisplay));
        }

        /**
         * @param auBecsDebit **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an &lt;span pulumi-lang-nodejs=&#34;`auBecsDebit`&#34; pulumi-lang-dotnet=&#34;`AuBecsDebit`&#34; pulumi-lang-go=&#34;`auBecsDebit`&#34; pulumi-lang-python=&#34;`au_becs_debit`&#34; pulumi-lang-yaml=&#34;`auBecsDebit`&#34; pulumi-lang-java=&#34;`auBecsDebit`&#34; pulumi-lang-hcl=&#34;`au_becs_debit`&#34;&gt;`auBecsDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the bank account.
         * 
         * @return builder
         * 
         */
        public Builder auBecsDebit(@Nullable Output<PaymentIntentPaymentMethodDataAuBecsDebitArgs> auBecsDebit) {
            $.auBecsDebit = auBecsDebit;
            return this;
        }

        /**
         * @param auBecsDebit **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an &lt;span pulumi-lang-nodejs=&#34;`auBecsDebit`&#34; pulumi-lang-dotnet=&#34;`AuBecsDebit`&#34; pulumi-lang-go=&#34;`auBecsDebit`&#34; pulumi-lang-python=&#34;`au_becs_debit`&#34; pulumi-lang-yaml=&#34;`auBecsDebit`&#34; pulumi-lang-java=&#34;`auBecsDebit`&#34; pulumi-lang-hcl=&#34;`au_becs_debit`&#34;&gt;`auBecsDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the bank account.
         * 
         * @return builder
         * 
         */
        public Builder auBecsDebit(PaymentIntentPaymentMethodDataAuBecsDebitArgs auBecsDebit) {
            return auBecsDebit(Output.of(auBecsDebit));
        }

        /**
         * @param bacsDebit **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`bacsDebit`&#34; pulumi-lang-dotnet=&#34;`BacsDebit`&#34; pulumi-lang-go=&#34;`bacsDebit`&#34; pulumi-lang-python=&#34;`bacs_debit`&#34; pulumi-lang-yaml=&#34;`bacsDebit`&#34; pulumi-lang-java=&#34;`bacsDebit`&#34; pulumi-lang-hcl=&#34;`bacs_debit`&#34;&gt;`bacsDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the Bacs Direct Debit bank account.
         * 
         * @return builder
         * 
         */
        public Builder bacsDebit(@Nullable Output<PaymentIntentPaymentMethodDataBacsDebitArgs> bacsDebit) {
            $.bacsDebit = bacsDebit;
            return this;
        }

        /**
         * @param bacsDebit **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`bacsDebit`&#34; pulumi-lang-dotnet=&#34;`BacsDebit`&#34; pulumi-lang-go=&#34;`bacsDebit`&#34; pulumi-lang-python=&#34;`bacs_debit`&#34; pulumi-lang-yaml=&#34;`bacsDebit`&#34; pulumi-lang-java=&#34;`bacsDebit`&#34; pulumi-lang-hcl=&#34;`bacs_debit`&#34;&gt;`bacsDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the Bacs Direct Debit bank account.
         * 
         * @return builder
         * 
         */
        public Builder bacsDebit(PaymentIntentPaymentMethodDataBacsDebitArgs bacsDebit) {
            return bacsDebit(Output.of(bacsDebit));
        }

        /**
         * @param billingDetails **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * Billing information associated with the PaymentMethod that may be used or required by particular types of payment methods.
         * 
         * @return builder
         * 
         */
        public Builder billingDetails(@Nullable Output<PaymentIntentPaymentMethodDataBillingDetailsArgs> billingDetails) {
            $.billingDetails = billingDetails;
            return this;
        }

        /**
         * @param billingDetails **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * Billing information associated with the PaymentMethod that may be used or required by particular types of payment methods.
         * 
         * @return builder
         * 
         */
        public Builder billingDetails(PaymentIntentPaymentMethodDataBillingDetailsArgs billingDetails) {
            return billingDetails(Output.of(billingDetails));
        }

        /**
         * @param boleto **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`boleto`&#34; pulumi-lang-dotnet=&#34;`Boleto`&#34; pulumi-lang-go=&#34;`boleto`&#34; pulumi-lang-python=&#34;`boleto`&#34; pulumi-lang-yaml=&#34;`boleto`&#34; pulumi-lang-java=&#34;`boleto`&#34; pulumi-lang-hcl=&#34;`boleto`&#34;&gt;`boleto`&lt;/span&gt; PaymentMethod, this hash contains details about the Boleto payment method.
         * 
         * @return builder
         * 
         */
        public Builder boleto(@Nullable Output<PaymentIntentPaymentMethodDataBoletoArgs> boleto) {
            $.boleto = boleto;
            return this;
        }

        /**
         * @param boleto **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`boleto`&#34; pulumi-lang-dotnet=&#34;`Boleto`&#34; pulumi-lang-go=&#34;`boleto`&#34; pulumi-lang-python=&#34;`boleto`&#34; pulumi-lang-yaml=&#34;`boleto`&#34; pulumi-lang-java=&#34;`boleto`&#34; pulumi-lang-hcl=&#34;`boleto`&#34;&gt;`boleto`&lt;/span&gt; PaymentMethod, this hash contains details about the Boleto payment method.
         * 
         * @return builder
         * 
         */
        public Builder boleto(PaymentIntentPaymentMethodDataBoletoArgs boleto) {
            return boleto(Output.of(boleto));
        }

        /**
         * @param eps **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an &lt;span pulumi-lang-nodejs=&#34;`eps`&#34; pulumi-lang-dotnet=&#34;`Eps`&#34; pulumi-lang-go=&#34;`eps`&#34; pulumi-lang-python=&#34;`eps`&#34; pulumi-lang-yaml=&#34;`eps`&#34; pulumi-lang-java=&#34;`eps`&#34; pulumi-lang-hcl=&#34;`eps`&#34;&gt;`eps`&lt;/span&gt; PaymentMethod, this hash contains details about the EPS payment method.
         * 
         * @return builder
         * 
         */
        public Builder eps(@Nullable Output<PaymentIntentPaymentMethodDataEpsArgs> eps) {
            $.eps = eps;
            return this;
        }

        /**
         * @param eps **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an &lt;span pulumi-lang-nodejs=&#34;`eps`&#34; pulumi-lang-dotnet=&#34;`Eps`&#34; pulumi-lang-go=&#34;`eps`&#34; pulumi-lang-python=&#34;`eps`&#34; pulumi-lang-yaml=&#34;`eps`&#34; pulumi-lang-java=&#34;`eps`&#34; pulumi-lang-hcl=&#34;`eps`&#34;&gt;`eps`&lt;/span&gt; PaymentMethod, this hash contains details about the EPS payment method.
         * 
         * @return builder
         * 
         */
        public Builder eps(PaymentIntentPaymentMethodDataEpsArgs eps) {
            return eps(Output.of(eps));
        }

        /**
         * @param fpx **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an &lt;span pulumi-lang-nodejs=&#34;`fpx`&#34; pulumi-lang-dotnet=&#34;`Fpx`&#34; pulumi-lang-go=&#34;`fpx`&#34; pulumi-lang-python=&#34;`fpx`&#34; pulumi-lang-yaml=&#34;`fpx`&#34; pulumi-lang-java=&#34;`fpx`&#34; pulumi-lang-hcl=&#34;`fpx`&#34;&gt;`fpx`&lt;/span&gt; PaymentMethod, this hash contains details about the FPX payment method.
         * 
         * @return builder
         * 
         */
        public Builder fpx(@Nullable Output<PaymentIntentPaymentMethodDataFpxArgs> fpx) {
            $.fpx = fpx;
            return this;
        }

        /**
         * @param fpx **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an &lt;span pulumi-lang-nodejs=&#34;`fpx`&#34; pulumi-lang-dotnet=&#34;`Fpx`&#34; pulumi-lang-go=&#34;`fpx`&#34; pulumi-lang-python=&#34;`fpx`&#34; pulumi-lang-yaml=&#34;`fpx`&#34; pulumi-lang-java=&#34;`fpx`&#34; pulumi-lang-hcl=&#34;`fpx`&#34;&gt;`fpx`&lt;/span&gt; PaymentMethod, this hash contains details about the FPX payment method.
         * 
         * @return builder
         * 
         */
        public Builder fpx(PaymentIntentPaymentMethodDataFpxArgs fpx) {
            return fpx(Output.of(fpx));
        }

        /**
         * @param ideal **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an &lt;span pulumi-lang-nodejs=&#34;`ideal`&#34; pulumi-lang-dotnet=&#34;`Ideal`&#34; pulumi-lang-go=&#34;`ideal`&#34; pulumi-lang-python=&#34;`ideal`&#34; pulumi-lang-yaml=&#34;`ideal`&#34; pulumi-lang-java=&#34;`ideal`&#34; pulumi-lang-hcl=&#34;`ideal`&#34;&gt;`ideal`&lt;/span&gt; PaymentMethod, this hash contains details about the iDEAL payment method.
         * 
         * @return builder
         * 
         */
        public Builder ideal(@Nullable Output<PaymentIntentPaymentMethodDataIdealArgs> ideal) {
            $.ideal = ideal;
            return this;
        }

        /**
         * @param ideal **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an &lt;span pulumi-lang-nodejs=&#34;`ideal`&#34; pulumi-lang-dotnet=&#34;`Ideal`&#34; pulumi-lang-go=&#34;`ideal`&#34; pulumi-lang-python=&#34;`ideal`&#34; pulumi-lang-yaml=&#34;`ideal`&#34; pulumi-lang-java=&#34;`ideal`&#34; pulumi-lang-hcl=&#34;`ideal`&#34;&gt;`ideal`&lt;/span&gt; PaymentMethod, this hash contains details about the iDEAL payment method.
         * 
         * @return builder
         * 
         */
        public Builder ideal(PaymentIntentPaymentMethodDataIdealArgs ideal) {
            return ideal(Output.of(ideal));
        }

        /**
         * @param klarna **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`klarna`&#34; pulumi-lang-dotnet=&#34;`Klarna`&#34; pulumi-lang-go=&#34;`klarna`&#34; pulumi-lang-python=&#34;`klarna`&#34; pulumi-lang-yaml=&#34;`klarna`&#34; pulumi-lang-java=&#34;`klarna`&#34; pulumi-lang-hcl=&#34;`klarna`&#34;&gt;`klarna`&lt;/span&gt; PaymentMethod, this hash contains details about the Klarna payment method.
         * 
         * @return builder
         * 
         */
        public Builder klarna(@Nullable Output<PaymentIntentPaymentMethodDataKlarnaArgs> klarna) {
            $.klarna = klarna;
            return this;
        }

        /**
         * @param klarna **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`klarna`&#34; pulumi-lang-dotnet=&#34;`Klarna`&#34; pulumi-lang-go=&#34;`klarna`&#34; pulumi-lang-python=&#34;`klarna`&#34; pulumi-lang-yaml=&#34;`klarna`&#34; pulumi-lang-java=&#34;`klarna`&#34; pulumi-lang-hcl=&#34;`klarna`&#34;&gt;`klarna`&lt;/span&gt; PaymentMethod, this hash contains details about the Klarna payment method.
         * 
         * @return builder
         * 
         */
        public Builder klarna(PaymentIntentPaymentMethodDataKlarnaArgs klarna) {
            return klarna(Output.of(klarna));
        }

        /**
         * @param metadata **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to &lt;span pulumi-lang-nodejs=&#34;`metadata`&#34; pulumi-lang-dotnet=&#34;`Metadata`&#34; pulumi-lang-go=&#34;`metadata`&#34; pulumi-lang-python=&#34;`metadata`&#34; pulumi-lang-yaml=&#34;`metadata`&#34; pulumi-lang-java=&#34;`metadata`&#34; pulumi-lang-hcl=&#34;`metadata`&#34;&gt;`metadata`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder metadata(@Nullable Output<Map<String,String>> metadata) {
            $.metadata = metadata;
            return this;
        }

        /**
         * @param metadata **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to &lt;span pulumi-lang-nodejs=&#34;`metadata`&#34; pulumi-lang-dotnet=&#34;`Metadata`&#34; pulumi-lang-go=&#34;`metadata`&#34; pulumi-lang-python=&#34;`metadata`&#34; pulumi-lang-yaml=&#34;`metadata`&#34; pulumi-lang-java=&#34;`metadata`&#34; pulumi-lang-hcl=&#34;`metadata`&#34;&gt;`metadata`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder metadata(Map<String,String> metadata) {
            return metadata(Output.of(metadata));
        }

        /**
         * @param naverPay **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`naverPay`&#34; pulumi-lang-dotnet=&#34;`NaverPay`&#34; pulumi-lang-go=&#34;`naverPay`&#34; pulumi-lang-python=&#34;`naver_pay`&#34; pulumi-lang-yaml=&#34;`naverPay`&#34; pulumi-lang-java=&#34;`naverPay`&#34; pulumi-lang-hcl=&#34;`naver_pay`&#34;&gt;`naverPay`&lt;/span&gt; PaymentMethod, this hash contains details about the Naver Pay payment method.
         * 
         * @return builder
         * 
         */
        public Builder naverPay(@Nullable Output<PaymentIntentPaymentMethodDataNaverPayArgs> naverPay) {
            $.naverPay = naverPay;
            return this;
        }

        /**
         * @param naverPay **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`naverPay`&#34; pulumi-lang-dotnet=&#34;`NaverPay`&#34; pulumi-lang-go=&#34;`naverPay`&#34; pulumi-lang-python=&#34;`naver_pay`&#34; pulumi-lang-yaml=&#34;`naverPay`&#34; pulumi-lang-java=&#34;`naverPay`&#34; pulumi-lang-hcl=&#34;`naver_pay`&#34;&gt;`naverPay`&lt;/span&gt; PaymentMethod, this hash contains details about the Naver Pay payment method.
         * 
         * @return builder
         * 
         */
        public Builder naverPay(PaymentIntentPaymentMethodDataNaverPayArgs naverPay) {
            return naverPay(Output.of(naverPay));
        }

        /**
         * @param nzBankAccount **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an&lt;span pulumi-lang-nodejs=&#34; nzBankAccount &#34; pulumi-lang-dotnet=&#34; NzBankAccount &#34; pulumi-lang-go=&#34; nzBankAccount &#34; pulumi-lang-python=&#34; nz_bank_account &#34; pulumi-lang-yaml=&#34; nzBankAccount &#34; pulumi-lang-java=&#34; nzBankAccount &#34; pulumi-lang-hcl=&#34; nz_bank_account &#34;&gt; nzBankAccount &lt;/span&gt;PaymentMethod, this hash contains details about the&lt;span pulumi-lang-nodejs=&#34; nzBankAccount &#34; pulumi-lang-dotnet=&#34; NzBankAccount &#34; pulumi-lang-go=&#34; nzBankAccount &#34; pulumi-lang-python=&#34; nz_bank_account &#34; pulumi-lang-yaml=&#34; nzBankAccount &#34; pulumi-lang-java=&#34; nzBankAccount &#34; pulumi-lang-hcl=&#34; nz_bank_account &#34;&gt; nzBankAccount &lt;/span&gt;payment method.
         * 
         * @return builder
         * 
         */
        public Builder nzBankAccount(@Nullable Output<PaymentIntentPaymentMethodDataNzBankAccountArgs> nzBankAccount) {
            $.nzBankAccount = nzBankAccount;
            return this;
        }

        /**
         * @param nzBankAccount **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an&lt;span pulumi-lang-nodejs=&#34; nzBankAccount &#34; pulumi-lang-dotnet=&#34; NzBankAccount &#34; pulumi-lang-go=&#34; nzBankAccount &#34; pulumi-lang-python=&#34; nz_bank_account &#34; pulumi-lang-yaml=&#34; nzBankAccount &#34; pulumi-lang-java=&#34; nzBankAccount &#34; pulumi-lang-hcl=&#34; nz_bank_account &#34;&gt; nzBankAccount &lt;/span&gt;PaymentMethod, this hash contains details about the&lt;span pulumi-lang-nodejs=&#34; nzBankAccount &#34; pulumi-lang-dotnet=&#34; NzBankAccount &#34; pulumi-lang-go=&#34; nzBankAccount &#34; pulumi-lang-python=&#34; nz_bank_account &#34; pulumi-lang-yaml=&#34; nzBankAccount &#34; pulumi-lang-java=&#34; nzBankAccount &#34; pulumi-lang-hcl=&#34; nz_bank_account &#34;&gt; nzBankAccount &lt;/span&gt;payment method.
         * 
         * @return builder
         * 
         */
        public Builder nzBankAccount(PaymentIntentPaymentMethodDataNzBankAccountArgs nzBankAccount) {
            return nzBankAccount(Output.of(nzBankAccount));
        }

        /**
         * @param p24 **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`p24`&#34; pulumi-lang-dotnet=&#34;`P24`&#34; pulumi-lang-go=&#34;`p24`&#34; pulumi-lang-python=&#34;`p24`&#34; pulumi-lang-yaml=&#34;`p24`&#34; pulumi-lang-java=&#34;`p24`&#34; pulumi-lang-hcl=&#34;`p24`&#34;&gt;`p24`&lt;/span&gt; PaymentMethod, this hash contains details about the P24 payment method.
         * 
         * @return builder
         * 
         */
        public Builder p24(@Nullable Output<PaymentIntentPaymentMethodDataP24Args> p24) {
            $.p24 = p24;
            return this;
        }

        /**
         * @param p24 **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`p24`&#34; pulumi-lang-dotnet=&#34;`P24`&#34; pulumi-lang-go=&#34;`p24`&#34; pulumi-lang-python=&#34;`p24`&#34; pulumi-lang-yaml=&#34;`p24`&#34; pulumi-lang-java=&#34;`p24`&#34; pulumi-lang-hcl=&#34;`p24`&#34;&gt;`p24`&lt;/span&gt; PaymentMethod, this hash contains details about the P24 payment method.
         * 
         * @return builder
         * 
         */
        public Builder p24(PaymentIntentPaymentMethodDataP24Args p24) {
            return p24(Output.of(p24));
        }

        /**
         * @param payto **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`payto`&#34; pulumi-lang-dotnet=&#34;`Payto`&#34; pulumi-lang-go=&#34;`payto`&#34; pulumi-lang-python=&#34;`payto`&#34; pulumi-lang-yaml=&#34;`payto`&#34; pulumi-lang-java=&#34;`payto`&#34; pulumi-lang-hcl=&#34;`payto`&#34;&gt;`payto`&lt;/span&gt; PaymentMethod, this hash contains details about the PayTo payment method.
         * 
         * @return builder
         * 
         */
        public Builder payto(@Nullable Output<PaymentIntentPaymentMethodDataPaytoArgs> payto) {
            $.payto = payto;
            return this;
        }

        /**
         * @param payto **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`payto`&#34; pulumi-lang-dotnet=&#34;`Payto`&#34; pulumi-lang-go=&#34;`payto`&#34; pulumi-lang-python=&#34;`payto`&#34; pulumi-lang-yaml=&#34;`payto`&#34; pulumi-lang-java=&#34;`payto`&#34; pulumi-lang-hcl=&#34;`payto`&#34;&gt;`payto`&lt;/span&gt; PaymentMethod, this hash contains details about the PayTo payment method.
         * 
         * @return builder
         * 
         */
        public Builder payto(PaymentIntentPaymentMethodDataPaytoArgs payto) {
            return payto(Output.of(payto));
        }

        /**
         * @param radarOptions **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * Options to configure Radar. See [Radar Session](https://docs.stripe.com/radar/radar-session) for more information.
         * 
         * @return builder
         * 
         */
        public Builder radarOptions(@Nullable Output<PaymentIntentPaymentMethodDataRadarOptionsArgs> radarOptions) {
            $.radarOptions = radarOptions;
            return this;
        }

        /**
         * @param radarOptions **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * Options to configure Radar. See [Radar Session](https://docs.stripe.com/radar/radar-session) for more information.
         * 
         * @return builder
         * 
         */
        public Builder radarOptions(PaymentIntentPaymentMethodDataRadarOptionsArgs radarOptions) {
            return radarOptions(Output.of(radarOptions));
        }

        /**
         * @param sepaDebit **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`sepaDebit`&#34; pulumi-lang-dotnet=&#34;`SepaDebit`&#34; pulumi-lang-go=&#34;`sepaDebit`&#34; pulumi-lang-python=&#34;`sepa_debit`&#34; pulumi-lang-yaml=&#34;`sepaDebit`&#34; pulumi-lang-java=&#34;`sepaDebit`&#34; pulumi-lang-hcl=&#34;`sepa_debit`&#34;&gt;`sepaDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the SEPA debit bank account.
         * 
         * @return builder
         * 
         */
        public Builder sepaDebit(@Nullable Output<PaymentIntentPaymentMethodDataSepaDebitArgs> sepaDebit) {
            $.sepaDebit = sepaDebit;
            return this;
        }

        /**
         * @param sepaDebit **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`sepaDebit`&#34; pulumi-lang-dotnet=&#34;`SepaDebit`&#34; pulumi-lang-go=&#34;`sepaDebit`&#34; pulumi-lang-python=&#34;`sepa_debit`&#34; pulumi-lang-yaml=&#34;`sepaDebit`&#34; pulumi-lang-java=&#34;`sepaDebit`&#34; pulumi-lang-hcl=&#34;`sepa_debit`&#34;&gt;`sepaDebit`&lt;/span&gt; PaymentMethod, this hash contains details about the SEPA debit bank account.
         * 
         * @return builder
         * 
         */
        public Builder sepaDebit(PaymentIntentPaymentMethodDataSepaDebitArgs sepaDebit) {
            return sepaDebit(Output.of(sepaDebit));
        }

        /**
         * @param sofort **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`sofort`&#34; pulumi-lang-dotnet=&#34;`Sofort`&#34; pulumi-lang-go=&#34;`sofort`&#34; pulumi-lang-python=&#34;`sofort`&#34; pulumi-lang-yaml=&#34;`sofort`&#34; pulumi-lang-java=&#34;`sofort`&#34; pulumi-lang-hcl=&#34;`sofort`&#34;&gt;`sofort`&lt;/span&gt; PaymentMethod, this hash contains details about the SOFORT payment method.
         * 
         * @return builder
         * 
         */
        public Builder sofort(@Nullable Output<PaymentIntentPaymentMethodDataSofortArgs> sofort) {
            $.sofort = sofort;
            return this;
        }

        /**
         * @param sofort **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`sofort`&#34; pulumi-lang-dotnet=&#34;`Sofort`&#34; pulumi-lang-go=&#34;`sofort`&#34; pulumi-lang-python=&#34;`sofort`&#34; pulumi-lang-yaml=&#34;`sofort`&#34; pulumi-lang-java=&#34;`sofort`&#34; pulumi-lang-hcl=&#34;`sofort`&#34;&gt;`sofort`&lt;/span&gt; PaymentMethod, this hash contains details about the SOFORT payment method.
         * 
         * @return builder
         * 
         */
        public Builder sofort(PaymentIntentPaymentMethodDataSofortArgs sofort) {
            return sofort(Output.of(sofort));
        }

        /**
         * @param type **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param upi **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`upi`&#34; pulumi-lang-dotnet=&#34;`Upi`&#34; pulumi-lang-go=&#34;`upi`&#34; pulumi-lang-python=&#34;`upi`&#34; pulumi-lang-yaml=&#34;`upi`&#34; pulumi-lang-java=&#34;`upi`&#34; pulumi-lang-hcl=&#34;`upi`&#34;&gt;`upi`&lt;/span&gt; PaymentMethod, this hash contains details about the UPI payment method.
         * 
         * @return builder
         * 
         */
        public Builder upi(@Nullable Output<PaymentIntentPaymentMethodDataUpiArgs> upi) {
            $.upi = upi;
            return this;
        }

        /**
         * @param upi **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is a &lt;span pulumi-lang-nodejs=&#34;`upi`&#34; pulumi-lang-dotnet=&#34;`Upi`&#34; pulumi-lang-go=&#34;`upi`&#34; pulumi-lang-python=&#34;`upi`&#34; pulumi-lang-yaml=&#34;`upi`&#34; pulumi-lang-java=&#34;`upi`&#34; pulumi-lang-hcl=&#34;`upi`&#34;&gt;`upi`&lt;/span&gt; PaymentMethod, this hash contains details about the UPI payment method.
         * 
         * @return builder
         * 
         */
        public Builder upi(PaymentIntentPaymentMethodDataUpiArgs upi) {
            return upi(Output.of(upi));
        }

        /**
         * @param usBankAccount **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an &lt;span pulumi-lang-nodejs=&#34;`usBankAccount`&#34; pulumi-lang-dotnet=&#34;`UsBankAccount`&#34; pulumi-lang-go=&#34;`usBankAccount`&#34; pulumi-lang-python=&#34;`us_bank_account`&#34; pulumi-lang-yaml=&#34;`usBankAccount`&#34; pulumi-lang-java=&#34;`usBankAccount`&#34; pulumi-lang-hcl=&#34;`us_bank_account`&#34;&gt;`usBankAccount`&lt;/span&gt; PaymentMethod, this hash contains details about the US bank account payment method.
         * 
         * @return builder
         * 
         */
        public Builder usBankAccount(@Nullable Output<PaymentIntentPaymentMethodDataUsBankAccountArgs> usBankAccount) {
            $.usBankAccount = usBankAccount;
            return this;
        }

        /**
         * @param usBankAccount **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * If this is an &lt;span pulumi-lang-nodejs=&#34;`usBankAccount`&#34; pulumi-lang-dotnet=&#34;`UsBankAccount`&#34; pulumi-lang-go=&#34;`usBankAccount`&#34; pulumi-lang-python=&#34;`us_bank_account`&#34; pulumi-lang-yaml=&#34;`usBankAccount`&#34; pulumi-lang-java=&#34;`usBankAccount`&#34; pulumi-lang-hcl=&#34;`us_bank_account`&#34;&gt;`usBankAccount`&lt;/span&gt; PaymentMethod, this hash contains details about the US bank account payment method.
         * 
         * @return builder
         * 
         */
        public Builder usBankAccount(PaymentIntentPaymentMethodDataUsBankAccountArgs usBankAccount) {
            return usBankAccount(Output.of(usBankAccount));
        }

        public PaymentIntentPaymentMethodDataArgs build() {
            if ($.type == null) {
                throw new MissingRequiredPropertyException("PaymentIntentPaymentMethodDataArgs", "type");
            }
            return $;
        }
    }

}
