// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PaymentIntentPaymentMethodOptionsAlmaArgs extends com.pulumi.resources.ResourceArgs {

    public static final PaymentIntentPaymentMethodOptionsAlmaArgs Empty = new PaymentIntentPaymentMethodOptionsAlmaArgs();

    /**
     * Controls when the funds will be captured from the customer&#39;s account.
     * 
     */
    @Import(name="captureMethod")
    private @Nullable Output<String> captureMethod;

    /**
     * @return Controls when the funds will be captured from the customer&#39;s account.
     * 
     */
    public Optional<Output<String>> captureMethod() {
        return Optional.ofNullable(this.captureMethod);
    }

    private PaymentIntentPaymentMethodOptionsAlmaArgs() {}

    private PaymentIntentPaymentMethodOptionsAlmaArgs(PaymentIntentPaymentMethodOptionsAlmaArgs $) {
        this.captureMethod = $.captureMethod;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PaymentIntentPaymentMethodOptionsAlmaArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PaymentIntentPaymentMethodOptionsAlmaArgs $;

        public Builder() {
            $ = new PaymentIntentPaymentMethodOptionsAlmaArgs();
        }

        public Builder(PaymentIntentPaymentMethodOptionsAlmaArgs defaults) {
            $ = new PaymentIntentPaymentMethodOptionsAlmaArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param captureMethod Controls when the funds will be captured from the customer&#39;s account.
         * 
         * @return builder
         * 
         */
        public Builder captureMethod(@Nullable Output<String> captureMethod) {
            $.captureMethod = captureMethod;
            return this;
        }

        /**
         * @param captureMethod Controls when the funds will be captured from the customer&#39;s account.
         * 
         * @return builder
         * 
         */
        public Builder captureMethod(String captureMethod) {
            return captureMethod(Output.of(captureMethod));
        }

        public PaymentIntentPaymentMethodOptionsAlmaArgs build() {
            return $;
        }
    }

}
