// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PaymentMethodKrCardArgs extends com.pulumi.resources.ResourceArgs {

    public static final PaymentMethodKrCardArgs Empty = new PaymentMethodKrCardArgs();

    /**
     * The local credit or debit card brand.
     * 
     */
    @Import(name="brand")
    private @Nullable Output<String> brand;

    /**
     * @return The local credit or debit card brand.
     * 
     */
    public Optional<Output<String>> brand() {
        return Optional.ofNullable(this.brand);
    }

    /**
     * The last four digits of the card. This may not be present for American Express cards.
     * 
     */
    @Import(name="last4")
    private @Nullable Output<String> last4;

    /**
     * @return The last four digits of the card. This may not be present for American Express cards.
     * 
     */
    public Optional<Output<String>> last4() {
        return Optional.ofNullable(this.last4);
    }

    private PaymentMethodKrCardArgs() {}

    private PaymentMethodKrCardArgs(PaymentMethodKrCardArgs $) {
        this.brand = $.brand;
        this.last4 = $.last4;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PaymentMethodKrCardArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PaymentMethodKrCardArgs $;

        public Builder() {
            $ = new PaymentMethodKrCardArgs();
        }

        public Builder(PaymentMethodKrCardArgs defaults) {
            $ = new PaymentMethodKrCardArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param brand The local credit or debit card brand.
         * 
         * @return builder
         * 
         */
        public Builder brand(@Nullable Output<String> brand) {
            $.brand = brand;
            return this;
        }

        /**
         * @param brand The local credit or debit card brand.
         * 
         * @return builder
         * 
         */
        public Builder brand(String brand) {
            return brand(Output.of(brand));
        }

        /**
         * @param last4 The last four digits of the card. This may not be present for American Express cards.
         * 
         * @return builder
         * 
         */
        public Builder last4(@Nullable Output<String> last4) {
            $.last4 = last4;
            return this;
        }

        /**
         * @param last4 The last four digits of the card. This may not be present for American Express cards.
         * 
         * @return builder
         * 
         */
        public Builder last4(String last4) {
            return last4(Output.of(last4));
        }

        public PaymentMethodKrCardArgs build() {
            return $;
        }
    }

}
