// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PaymentIntentRadarOptionsArgs extends com.pulumi.resources.ResourceArgs {

    public static final PaymentIntentRadarOptionsArgs Empty = new PaymentIntentRadarOptionsArgs();

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A [Radar Session](https://docs.stripe.com/radar/radar-session) is a snapshot of the browser metadata and device details that help Radar make more accurate predictions on your payments.
     * 
     */
    @Import(name="session")
    private @Nullable Output<String> session;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A [Radar Session](https://docs.stripe.com/radar/radar-session) is a snapshot of the browser metadata and device details that help Radar make more accurate predictions on your payments.
     * 
     */
    public Optional<Output<String>> session() {
        return Optional.ofNullable(this.session);
    }

    private PaymentIntentRadarOptionsArgs() {}

    private PaymentIntentRadarOptionsArgs(PaymentIntentRadarOptionsArgs $) {
        this.session = $.session;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PaymentIntentRadarOptionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PaymentIntentRadarOptionsArgs $;

        public Builder() {
            $ = new PaymentIntentRadarOptionsArgs();
        }

        public Builder(PaymentIntentRadarOptionsArgs defaults) {
            $ = new PaymentIntentRadarOptionsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param session **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * A [Radar Session](https://docs.stripe.com/radar/radar-session) is a snapshot of the browser metadata and device details that help Radar make more accurate predictions on your payments.
         * 
         * @return builder
         * 
         */
        public Builder session(@Nullable Output<String> session) {
            $.session = session;
            return this;
        }

        /**
         * @param session **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * A [Radar Session](https://docs.stripe.com/radar/radar-session) is a snapshot of the browser metadata and device details that help Radar make more accurate predictions on your payments.
         * 
         * @return builder
         * 
         */
        public Builder session(String session) {
            return session(Output.of(session));
        }

        public PaymentIntentRadarOptionsArgs build() {
            return $;
        }
    }

}
