// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PaymentLinkPaymentMethodOptionsCardRestrictionsArgs extends com.pulumi.resources.ResourceArgs {

    public static final PaymentLinkPaymentMethodOptionsCardRestrictionsArgs Empty = new PaymentLinkPaymentMethodOptionsCardRestrictionsArgs();

    /**
     * The card brands to block. If a customer enters or selects a card belonging to a blocked brand, they can&#39;t complete the payment.
     * 
     */
    @Import(name="brandsBlockeds")
    private @Nullable Output<List<String>> brandsBlockeds;

    /**
     * @return The card brands to block. If a customer enters or selects a card belonging to a blocked brand, they can&#39;t complete the payment.
     * 
     */
    public Optional<Output<List<String>>> brandsBlockeds() {
        return Optional.ofNullable(this.brandsBlockeds);
    }

    private PaymentLinkPaymentMethodOptionsCardRestrictionsArgs() {}

    private PaymentLinkPaymentMethodOptionsCardRestrictionsArgs(PaymentLinkPaymentMethodOptionsCardRestrictionsArgs $) {
        this.brandsBlockeds = $.brandsBlockeds;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PaymentLinkPaymentMethodOptionsCardRestrictionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PaymentLinkPaymentMethodOptionsCardRestrictionsArgs $;

        public Builder() {
            $ = new PaymentLinkPaymentMethodOptionsCardRestrictionsArgs();
        }

        public Builder(PaymentLinkPaymentMethodOptionsCardRestrictionsArgs defaults) {
            $ = new PaymentLinkPaymentMethodOptionsCardRestrictionsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param brandsBlockeds The card brands to block. If a customer enters or selects a card belonging to a blocked brand, they can&#39;t complete the payment.
         * 
         * @return builder
         * 
         */
        public Builder brandsBlockeds(@Nullable Output<List<String>> brandsBlockeds) {
            $.brandsBlockeds = brandsBlockeds;
            return this;
        }

        /**
         * @param brandsBlockeds The card brands to block. If a customer enters or selects a card belonging to a blocked brand, they can&#39;t complete the payment.
         * 
         * @return builder
         * 
         */
        public Builder brandsBlockeds(List<String> brandsBlockeds) {
            return brandsBlockeds(Output.of(brandsBlockeds));
        }

        /**
         * @param brandsBlockeds The card brands to block. If a customer enters or selects a card belonging to a blocked brand, they can&#39;t complete the payment.
         * 
         * @return builder
         * 
         */
        public Builder brandsBlockeds(String... brandsBlockeds) {
            return brandsBlockeds(List.of(brandsBlockeds));
        }

        public PaymentLinkPaymentMethodOptionsCardRestrictionsArgs build() {
            return $;
        }
    }

}
