// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.util.Objects;


public final class PersonDobArgs extends com.pulumi.resources.ResourceArgs {

    public static final PersonDobArgs Empty = new PersonDobArgs();

    /**
     * The day of birth, between 1 and 31.
     * 
     */
    @Import(name="day", required=true)
    private Output<Double> day;

    /**
     * @return The day of birth, between 1 and 31.
     * 
     */
    public Output<Double> day() {
        return this.day;
    }

    /**
     * The month of birth, between 1 and 12.
     * 
     */
    @Import(name="month", required=true)
    private Output<Double> month;

    /**
     * @return The month of birth, between 1 and 12.
     * 
     */
    public Output<Double> month() {
        return this.month;
    }

    /**
     * The four-digit year of birth.
     * 
     */
    @Import(name="year", required=true)
    private Output<Double> year;

    /**
     * @return The four-digit year of birth.
     * 
     */
    public Output<Double> year() {
        return this.year;
    }

    private PersonDobArgs() {}

    private PersonDobArgs(PersonDobArgs $) {
        this.day = $.day;
        this.month = $.month;
        this.year = $.year;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PersonDobArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PersonDobArgs $;

        public Builder() {
            $ = new PersonDobArgs();
        }

        public Builder(PersonDobArgs defaults) {
            $ = new PersonDobArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param day The day of birth, between 1 and 31.
         * 
         * @return builder
         * 
         */
        public Builder day(Output<Double> day) {
            $.day = day;
            return this;
        }

        /**
         * @param day The day of birth, between 1 and 31.
         * 
         * @return builder
         * 
         */
        public Builder day(Double day) {
            return day(Output.of(day));
        }

        /**
         * @param month The month of birth, between 1 and 12.
         * 
         * @return builder
         * 
         */
        public Builder month(Output<Double> month) {
            $.month = month;
            return this;
        }

        /**
         * @param month The month of birth, between 1 and 12.
         * 
         * @return builder
         * 
         */
        public Builder month(Double month) {
            return month(Output.of(month));
        }

        /**
         * @param year The four-digit year of birth.
         * 
         * @return builder
         * 
         */
        public Builder year(Output<Double> year) {
            $.year = year;
            return this;
        }

        /**
         * @param year The four-digit year of birth.
         * 
         * @return builder
         * 
         */
        public Builder year(Double year) {
            return year(Output.of(year));
        }

        public PersonDobArgs build() {
            if ($.day == null) {
                throw new MissingRequiredPropertyException("PersonDobArgs", "day");
            }
            if ($.month == null) {
                throw new MissingRequiredPropertyException("PersonDobArgs", "month");
            }
            if ($.year == null) {
                throw new MissingRequiredPropertyException("PersonDobArgs", "year");
            }
            return $;
        }
    }

}
