// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PersonUsCfpbDataEthnicityDetailsArgs extends com.pulumi.resources.ResourceArgs {

    public static final PersonUsCfpbDataEthnicityDetailsArgs Empty = new PersonUsCfpbDataEthnicityDetailsArgs();

    /**
     * The persons ethnicity
     * 
     */
    @Import(name="ethnicities")
    private @Nullable Output<List<String>> ethnicities;

    /**
     * @return The persons ethnicity
     * 
     */
    public Optional<Output<List<String>>> ethnicities() {
        return Optional.ofNullable(this.ethnicities);
    }

    /**
     * Please specify your origin, when other is selected.
     * 
     */
    @Import(name="ethnicityOther")
    private @Nullable Output<String> ethnicityOther;

    /**
     * @return Please specify your origin, when other is selected.
     * 
     */
    public Optional<Output<String>> ethnicityOther() {
        return Optional.ofNullable(this.ethnicityOther);
    }

    private PersonUsCfpbDataEthnicityDetailsArgs() {}

    private PersonUsCfpbDataEthnicityDetailsArgs(PersonUsCfpbDataEthnicityDetailsArgs $) {
        this.ethnicities = $.ethnicities;
        this.ethnicityOther = $.ethnicityOther;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PersonUsCfpbDataEthnicityDetailsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PersonUsCfpbDataEthnicityDetailsArgs $;

        public Builder() {
            $ = new PersonUsCfpbDataEthnicityDetailsArgs();
        }

        public Builder(PersonUsCfpbDataEthnicityDetailsArgs defaults) {
            $ = new PersonUsCfpbDataEthnicityDetailsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param ethnicities The persons ethnicity
         * 
         * @return builder
         * 
         */
        public Builder ethnicities(@Nullable Output<List<String>> ethnicities) {
            $.ethnicities = ethnicities;
            return this;
        }

        /**
         * @param ethnicities The persons ethnicity
         * 
         * @return builder
         * 
         */
        public Builder ethnicities(List<String> ethnicities) {
            return ethnicities(Output.of(ethnicities));
        }

        /**
         * @param ethnicities The persons ethnicity
         * 
         * @return builder
         * 
         */
        public Builder ethnicities(String... ethnicities) {
            return ethnicities(List.of(ethnicities));
        }

        /**
         * @param ethnicityOther Please specify your origin, when other is selected.
         * 
         * @return builder
         * 
         */
        public Builder ethnicityOther(@Nullable Output<String> ethnicityOther) {
            $.ethnicityOther = ethnicityOther;
            return this;
        }

        /**
         * @param ethnicityOther Please specify your origin, when other is selected.
         * 
         * @return builder
         * 
         */
        public Builder ethnicityOther(String ethnicityOther) {
            return ethnicityOther(Output.of(ethnicityOther));
        }

        public PersonUsCfpbDataEthnicityDetailsArgs build() {
            return $;
        }
    }

}
