// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PromotionCodePromotionArgs extends com.pulumi.resources.ResourceArgs {

    public static final PromotionCodePromotionArgs Empty = new PromotionCodePromotionArgs();

    /**
     * If promotion &lt;span pulumi-lang-nodejs=&#34;`type`&#34; pulumi-lang-dotnet=&#34;`Type`&#34; pulumi-lang-go=&#34;`type`&#34; pulumi-lang-python=&#34;`type`&#34; pulumi-lang-yaml=&#34;`type`&#34; pulumi-lang-java=&#34;`type`&#34; pulumi-lang-hcl=&#34;`type`&#34;&gt;`type`&lt;/span&gt; is &lt;span pulumi-lang-nodejs=&#34;`coupon`&#34; pulumi-lang-dotnet=&#34;`Coupon`&#34; pulumi-lang-go=&#34;`coupon`&#34; pulumi-lang-python=&#34;`coupon`&#34; pulumi-lang-yaml=&#34;`coupon`&#34; pulumi-lang-java=&#34;`coupon`&#34; pulumi-lang-hcl=&#34;`coupon`&#34;&gt;`coupon`&lt;/span&gt;, the coupon for this promotion.
     * 
     */
    @Import(name="coupon")
    private @Nullable Output<String> coupon;

    /**
     * @return If promotion &lt;span pulumi-lang-nodejs=&#34;`type`&#34; pulumi-lang-dotnet=&#34;`Type`&#34; pulumi-lang-go=&#34;`type`&#34; pulumi-lang-python=&#34;`type`&#34; pulumi-lang-yaml=&#34;`type`&#34; pulumi-lang-java=&#34;`type`&#34; pulumi-lang-hcl=&#34;`type`&#34;&gt;`type`&lt;/span&gt; is &lt;span pulumi-lang-nodejs=&#34;`coupon`&#34; pulumi-lang-dotnet=&#34;`Coupon`&#34; pulumi-lang-go=&#34;`coupon`&#34; pulumi-lang-python=&#34;`coupon`&#34; pulumi-lang-yaml=&#34;`coupon`&#34; pulumi-lang-java=&#34;`coupon`&#34; pulumi-lang-hcl=&#34;`coupon`&#34;&gt;`coupon`&lt;/span&gt;, the coupon for this promotion.
     * 
     */
    public Optional<Output<String>> coupon() {
        return Optional.ofNullable(this.coupon);
    }

    /**
     * The type of promotion.
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return The type of promotion.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private PromotionCodePromotionArgs() {}

    private PromotionCodePromotionArgs(PromotionCodePromotionArgs $) {
        this.coupon = $.coupon;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PromotionCodePromotionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PromotionCodePromotionArgs $;

        public Builder() {
            $ = new PromotionCodePromotionArgs();
        }

        public Builder(PromotionCodePromotionArgs defaults) {
            $ = new PromotionCodePromotionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param coupon If promotion &lt;span pulumi-lang-nodejs=&#34;`type`&#34; pulumi-lang-dotnet=&#34;`Type`&#34; pulumi-lang-go=&#34;`type`&#34; pulumi-lang-python=&#34;`type`&#34; pulumi-lang-yaml=&#34;`type`&#34; pulumi-lang-java=&#34;`type`&#34; pulumi-lang-hcl=&#34;`type`&#34;&gt;`type`&lt;/span&gt; is &lt;span pulumi-lang-nodejs=&#34;`coupon`&#34; pulumi-lang-dotnet=&#34;`Coupon`&#34; pulumi-lang-go=&#34;`coupon`&#34; pulumi-lang-python=&#34;`coupon`&#34; pulumi-lang-yaml=&#34;`coupon`&#34; pulumi-lang-java=&#34;`coupon`&#34; pulumi-lang-hcl=&#34;`coupon`&#34;&gt;`coupon`&lt;/span&gt;, the coupon for this promotion.
         * 
         * @return builder
         * 
         */
        public Builder coupon(@Nullable Output<String> coupon) {
            $.coupon = coupon;
            return this;
        }

        /**
         * @param coupon If promotion &lt;span pulumi-lang-nodejs=&#34;`type`&#34; pulumi-lang-dotnet=&#34;`Type`&#34; pulumi-lang-go=&#34;`type`&#34; pulumi-lang-python=&#34;`type`&#34; pulumi-lang-yaml=&#34;`type`&#34; pulumi-lang-java=&#34;`type`&#34; pulumi-lang-hcl=&#34;`type`&#34;&gt;`type`&lt;/span&gt; is &lt;span pulumi-lang-nodejs=&#34;`coupon`&#34; pulumi-lang-dotnet=&#34;`Coupon`&#34; pulumi-lang-go=&#34;`coupon`&#34; pulumi-lang-python=&#34;`coupon`&#34; pulumi-lang-yaml=&#34;`coupon`&#34; pulumi-lang-java=&#34;`coupon`&#34; pulumi-lang-hcl=&#34;`coupon`&#34;&gt;`coupon`&lt;/span&gt;, the coupon for this promotion.
         * 
         * @return builder
         * 
         */
        public Builder coupon(String coupon) {
            return coupon(Output.of(coupon));
        }

        /**
         * @param type The type of promotion.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The type of promotion.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public PromotionCodePromotionArgs build() {
            if ($.type == null) {
                throw new MissingRequiredPropertyException("PromotionCodePromotionArgs", "type");
            }
            return $;
        }
    }

}
