// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.stripe.inputs.ShippingRateDeliveryEstimateMaximumArgs;
import com.pulumi.stripe.inputs.ShippingRateDeliveryEstimateMinimumArgs;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ShippingRateDeliveryEstimateArgs extends com.pulumi.resources.ResourceArgs {

    public static final ShippingRateDeliveryEstimateArgs Empty = new ShippingRateDeliveryEstimateArgs();

    /**
     * The upper bound of the estimated range. If empty, represents no upper bound i.e., infinite.
     * 
     */
    @Import(name="maximums")
    private @Nullable Output<List<ShippingRateDeliveryEstimateMaximumArgs>> maximums;

    /**
     * @return The upper bound of the estimated range. If empty, represents no upper bound i.e., infinite.
     * 
     */
    public Optional<Output<List<ShippingRateDeliveryEstimateMaximumArgs>>> maximums() {
        return Optional.ofNullable(this.maximums);
    }

    /**
     * The lower bound of the estimated range. If empty, represents no lower bound.
     * 
     */
    @Import(name="minimums")
    private @Nullable Output<List<ShippingRateDeliveryEstimateMinimumArgs>> minimums;

    /**
     * @return The lower bound of the estimated range. If empty, represents no lower bound.
     * 
     */
    public Optional<Output<List<ShippingRateDeliveryEstimateMinimumArgs>>> minimums() {
        return Optional.ofNullable(this.minimums);
    }

    private ShippingRateDeliveryEstimateArgs() {}

    private ShippingRateDeliveryEstimateArgs(ShippingRateDeliveryEstimateArgs $) {
        this.maximums = $.maximums;
        this.minimums = $.minimums;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ShippingRateDeliveryEstimateArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ShippingRateDeliveryEstimateArgs $;

        public Builder() {
            $ = new ShippingRateDeliveryEstimateArgs();
        }

        public Builder(ShippingRateDeliveryEstimateArgs defaults) {
            $ = new ShippingRateDeliveryEstimateArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param maximums The upper bound of the estimated range. If empty, represents no upper bound i.e., infinite.
         * 
         * @return builder
         * 
         */
        public Builder maximums(@Nullable Output<List<ShippingRateDeliveryEstimateMaximumArgs>> maximums) {
            $.maximums = maximums;
            return this;
        }

        /**
         * @param maximums The upper bound of the estimated range. If empty, represents no upper bound i.e., infinite.
         * 
         * @return builder
         * 
         */
        public Builder maximums(List<ShippingRateDeliveryEstimateMaximumArgs> maximums) {
            return maximums(Output.of(maximums));
        }

        /**
         * @param maximums The upper bound of the estimated range. If empty, represents no upper bound i.e., infinite.
         * 
         * @return builder
         * 
         */
        public Builder maximums(ShippingRateDeliveryEstimateMaximumArgs... maximums) {
            return maximums(List.of(maximums));
        }

        /**
         * @param minimums The lower bound of the estimated range. If empty, represents no lower bound.
         * 
         * @return builder
         * 
         */
        public Builder minimums(@Nullable Output<List<ShippingRateDeliveryEstimateMinimumArgs>> minimums) {
            $.minimums = minimums;
            return this;
        }

        /**
         * @param minimums The lower bound of the estimated range. If empty, represents no lower bound.
         * 
         * @return builder
         * 
         */
        public Builder minimums(List<ShippingRateDeliveryEstimateMinimumArgs> minimums) {
            return minimums(Output.of(minimums));
        }

        /**
         * @param minimums The lower bound of the estimated range. If empty, represents no lower bound.
         * 
         * @return builder
         * 
         */
        public Builder minimums(ShippingRateDeliveryEstimateMinimumArgs... minimums) {
            return minimums(List.of(minimums));
        }

        public ShippingRateDeliveryEstimateArgs build() {
            return $;
        }
    }

}
