// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SourceGiropayArgs extends com.pulumi.resources.ResourceArgs {

    public static final SourceGiropayArgs Empty = new SourceGiropayArgs();

    @Import(name="bankCode")
    private @Nullable Output<String> bankCode;

    public Optional<Output<String>> bankCode() {
        return Optional.ofNullable(this.bankCode);
    }

    @Import(name="bankName")
    private @Nullable Output<String> bankName;

    public Optional<Output<String>> bankName() {
        return Optional.ofNullable(this.bankName);
    }

    @Import(name="bic")
    private @Nullable Output<String> bic;

    public Optional<Output<String>> bic() {
        return Optional.ofNullable(this.bic);
    }

    @Import(name="statementDescriptor")
    private @Nullable Output<String> statementDescriptor;

    public Optional<Output<String>> statementDescriptor() {
        return Optional.ofNullable(this.statementDescriptor);
    }

    private SourceGiropayArgs() {}

    private SourceGiropayArgs(SourceGiropayArgs $) {
        this.bankCode = $.bankCode;
        this.bankName = $.bankName;
        this.bic = $.bic;
        this.statementDescriptor = $.statementDescriptor;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SourceGiropayArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SourceGiropayArgs $;

        public Builder() {
            $ = new SourceGiropayArgs();
        }

        public Builder(SourceGiropayArgs defaults) {
            $ = new SourceGiropayArgs(Objects.requireNonNull(defaults));
        }

        public Builder bankCode(@Nullable Output<String> bankCode) {
            $.bankCode = bankCode;
            return this;
        }

        public Builder bankCode(String bankCode) {
            return bankCode(Output.of(bankCode));
        }

        public Builder bankName(@Nullable Output<String> bankName) {
            $.bankName = bankName;
            return this;
        }

        public Builder bankName(String bankName) {
            return bankName(Output.of(bankName));
        }

        public Builder bic(@Nullable Output<String> bic) {
            $.bic = bic;
            return this;
        }

        public Builder bic(String bic) {
            return bic(Output.of(bic));
        }

        public Builder statementDescriptor(@Nullable Output<String> statementDescriptor) {
            $.statementDescriptor = statementDescriptor;
            return this;
        }

        public Builder statementDescriptor(String statementDescriptor) {
            return statementDescriptor(Output.of(statementDescriptor));
        }

        public SourceGiropayArgs build() {
            return $;
        }
    }

}
