// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SourceAcssDebitArgs extends com.pulumi.resources.ResourceArgs {

    public static final SourceAcssDebitArgs Empty = new SourceAcssDebitArgs();

    @Import(name="bankAddressCity")
    private @Nullable Output<String> bankAddressCity;

    public Optional<Output<String>> bankAddressCity() {
        return Optional.ofNullable(this.bankAddressCity);
    }

    @Import(name="bankAddressLine1")
    private @Nullable Output<String> bankAddressLine1;

    public Optional<Output<String>> bankAddressLine1() {
        return Optional.ofNullable(this.bankAddressLine1);
    }

    @Import(name="bankAddressLine2")
    private @Nullable Output<String> bankAddressLine2;

    public Optional<Output<String>> bankAddressLine2() {
        return Optional.ofNullable(this.bankAddressLine2);
    }

    @Import(name="bankAddressPostalCode")
    private @Nullable Output<String> bankAddressPostalCode;

    public Optional<Output<String>> bankAddressPostalCode() {
        return Optional.ofNullable(this.bankAddressPostalCode);
    }

    @Import(name="bankName")
    private @Nullable Output<String> bankName;

    public Optional<Output<String>> bankName() {
        return Optional.ofNullable(this.bankName);
    }

    @Import(name="category")
    private @Nullable Output<String> category;

    public Optional<Output<String>> category() {
        return Optional.ofNullable(this.category);
    }

    @Import(name="country")
    private @Nullable Output<String> country;

    public Optional<Output<String>> country() {
        return Optional.ofNullable(this.country);
    }

    @Import(name="fingerprint")
    private @Nullable Output<String> fingerprint;

    public Optional<Output<String>> fingerprint() {
        return Optional.ofNullable(this.fingerprint);
    }

    @Import(name="last4")
    private @Nullable Output<String> last4;

    public Optional<Output<String>> last4() {
        return Optional.ofNullable(this.last4);
    }

    @Import(name="routingNumber")
    private @Nullable Output<String> routingNumber;

    public Optional<Output<String>> routingNumber() {
        return Optional.ofNullable(this.routingNumber);
    }

    private SourceAcssDebitArgs() {}

    private SourceAcssDebitArgs(SourceAcssDebitArgs $) {
        this.bankAddressCity = $.bankAddressCity;
        this.bankAddressLine1 = $.bankAddressLine1;
        this.bankAddressLine2 = $.bankAddressLine2;
        this.bankAddressPostalCode = $.bankAddressPostalCode;
        this.bankName = $.bankName;
        this.category = $.category;
        this.country = $.country;
        this.fingerprint = $.fingerprint;
        this.last4 = $.last4;
        this.routingNumber = $.routingNumber;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SourceAcssDebitArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SourceAcssDebitArgs $;

        public Builder() {
            $ = new SourceAcssDebitArgs();
        }

        public Builder(SourceAcssDebitArgs defaults) {
            $ = new SourceAcssDebitArgs(Objects.requireNonNull(defaults));
        }

        public Builder bankAddressCity(@Nullable Output<String> bankAddressCity) {
            $.bankAddressCity = bankAddressCity;
            return this;
        }

        public Builder bankAddressCity(String bankAddressCity) {
            return bankAddressCity(Output.of(bankAddressCity));
        }

        public Builder bankAddressLine1(@Nullable Output<String> bankAddressLine1) {
            $.bankAddressLine1 = bankAddressLine1;
            return this;
        }

        public Builder bankAddressLine1(String bankAddressLine1) {
            return bankAddressLine1(Output.of(bankAddressLine1));
        }

        public Builder bankAddressLine2(@Nullable Output<String> bankAddressLine2) {
            $.bankAddressLine2 = bankAddressLine2;
            return this;
        }

        public Builder bankAddressLine2(String bankAddressLine2) {
            return bankAddressLine2(Output.of(bankAddressLine2));
        }

        public Builder bankAddressPostalCode(@Nullable Output<String> bankAddressPostalCode) {
            $.bankAddressPostalCode = bankAddressPostalCode;
            return this;
        }

        public Builder bankAddressPostalCode(String bankAddressPostalCode) {
            return bankAddressPostalCode(Output.of(bankAddressPostalCode));
        }

        public Builder bankName(@Nullable Output<String> bankName) {
            $.bankName = bankName;
            return this;
        }

        public Builder bankName(String bankName) {
            return bankName(Output.of(bankName));
        }

        public Builder category(@Nullable Output<String> category) {
            $.category = category;
            return this;
        }

        public Builder category(String category) {
            return category(Output.of(category));
        }

        public Builder country(@Nullable Output<String> country) {
            $.country = country;
            return this;
        }

        public Builder country(String country) {
            return country(Output.of(country));
        }

        public Builder fingerprint(@Nullable Output<String> fingerprint) {
            $.fingerprint = fingerprint;
            return this;
        }

        public Builder fingerprint(String fingerprint) {
            return fingerprint(Output.of(fingerprint));
        }

        public Builder last4(@Nullable Output<String> last4) {
            $.last4 = last4;
            return this;
        }

        public Builder last4(String last4) {
            return last4(Output.of(last4));
        }

        public Builder routingNumber(@Nullable Output<String> routingNumber) {
            $.routingNumber = routingNumber;
            return this;
        }

        public Builder routingNumber(String routingNumber) {
            return routingNumber(Output.of(routingNumber));
        }

        public SourceAcssDebitArgs build() {
            return $;
        }
    }

}
