// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SourceEpsArgs extends com.pulumi.resources.ResourceArgs {

    public static final SourceEpsArgs Empty = new SourceEpsArgs();

    @Import(name="reference")
    private @Nullable Output<String> reference;

    public Optional<Output<String>> reference() {
        return Optional.ofNullable(this.reference);
    }

    @Import(name="statementDescriptor")
    private @Nullable Output<String> statementDescriptor;

    public Optional<Output<String>> statementDescriptor() {
        return Optional.ofNullable(this.statementDescriptor);
    }

    private SourceEpsArgs() {}

    private SourceEpsArgs(SourceEpsArgs $) {
        this.reference = $.reference;
        this.statementDescriptor = $.statementDescriptor;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SourceEpsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SourceEpsArgs $;

        public Builder() {
            $ = new SourceEpsArgs();
        }

        public Builder(SourceEpsArgs defaults) {
            $ = new SourceEpsArgs(Objects.requireNonNull(defaults));
        }

        public Builder reference(@Nullable Output<String> reference) {
            $.reference = reference;
            return this;
        }

        public Builder reference(String reference) {
            return reference(Output.of(reference));
        }

        public Builder statementDescriptor(@Nullable Output<String> statementDescriptor) {
            $.statementDescriptor = statementDescriptor;
            return this;
        }

        public Builder statementDescriptor(String statementDescriptor) {
            return statementDescriptor(Output.of(statementDescriptor));
        }

        public SourceEpsArgs build() {
            return $;
        }
    }

}
