// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.stripe.inputs.SubscriptionPaymentSettingsPaymentMethodOptionsUpiMandateOptionsArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SubscriptionPaymentSettingsPaymentMethodOptionsUpiArgs extends com.pulumi.resources.ResourceArgs {

    public static final SubscriptionPaymentSettingsPaymentMethodOptionsUpiArgs Empty = new SubscriptionPaymentSettingsPaymentMethodOptionsUpiArgs();

    @Import(name="mandateOptions")
    private @Nullable Output<SubscriptionPaymentSettingsPaymentMethodOptionsUpiMandateOptionsArgs> mandateOptions;

    public Optional<Output<SubscriptionPaymentSettingsPaymentMethodOptionsUpiMandateOptionsArgs>> mandateOptions() {
        return Optional.ofNullable(this.mandateOptions);
    }

    private SubscriptionPaymentSettingsPaymentMethodOptionsUpiArgs() {}

    private SubscriptionPaymentSettingsPaymentMethodOptionsUpiArgs(SubscriptionPaymentSettingsPaymentMethodOptionsUpiArgs $) {
        this.mandateOptions = $.mandateOptions;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SubscriptionPaymentSettingsPaymentMethodOptionsUpiArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SubscriptionPaymentSettingsPaymentMethodOptionsUpiArgs $;

        public Builder() {
            $ = new SubscriptionPaymentSettingsPaymentMethodOptionsUpiArgs();
        }

        public Builder(SubscriptionPaymentSettingsPaymentMethodOptionsUpiArgs defaults) {
            $ = new SubscriptionPaymentSettingsPaymentMethodOptionsUpiArgs(Objects.requireNonNull(defaults));
        }

        public Builder mandateOptions(@Nullable Output<SubscriptionPaymentSettingsPaymentMethodOptionsUpiMandateOptionsArgs> mandateOptions) {
            $.mandateOptions = mandateOptions;
            return this;
        }

        public Builder mandateOptions(SubscriptionPaymentSettingsPaymentMethodOptionsUpiMandateOptionsArgs mandateOptions) {
            return mandateOptions(Output.of(mandateOptions));
        }

        public SubscriptionPaymentSettingsPaymentMethodOptionsUpiArgs build() {
            return $;
        }
    }

}
