// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.stripe.inputs.TaxRegistrationCountryOptionsMeStandardArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TaxRegistrationCountryOptionsMeArgs extends com.pulumi.resources.ResourceArgs {

    public static final TaxRegistrationCountryOptionsMeArgs Empty = new TaxRegistrationCountryOptionsMeArgs();

    /**
     * Options for the standard registration.
     * 
     */
    @Import(name="standard")
    private @Nullable Output<TaxRegistrationCountryOptionsMeStandardArgs> standard;

    /**
     * @return Options for the standard registration.
     * 
     */
    public Optional<Output<TaxRegistrationCountryOptionsMeStandardArgs>> standard() {
        return Optional.ofNullable(this.standard);
    }

    /**
     * Type of registration in &lt;span pulumi-lang-nodejs=&#34;`country`&#34; pulumi-lang-dotnet=&#34;`Country`&#34; pulumi-lang-go=&#34;`country`&#34; pulumi-lang-python=&#34;`country`&#34; pulumi-lang-yaml=&#34;`country`&#34; pulumi-lang-java=&#34;`country`&#34; pulumi-lang-hcl=&#34;`country`&#34;&gt;`country`&lt;/span&gt;.
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return Type of registration in &lt;span pulumi-lang-nodejs=&#34;`country`&#34; pulumi-lang-dotnet=&#34;`Country`&#34; pulumi-lang-go=&#34;`country`&#34; pulumi-lang-python=&#34;`country`&#34; pulumi-lang-yaml=&#34;`country`&#34; pulumi-lang-java=&#34;`country`&#34; pulumi-lang-hcl=&#34;`country`&#34;&gt;`country`&lt;/span&gt;.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private TaxRegistrationCountryOptionsMeArgs() {}

    private TaxRegistrationCountryOptionsMeArgs(TaxRegistrationCountryOptionsMeArgs $) {
        this.standard = $.standard;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TaxRegistrationCountryOptionsMeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TaxRegistrationCountryOptionsMeArgs $;

        public Builder() {
            $ = new TaxRegistrationCountryOptionsMeArgs();
        }

        public Builder(TaxRegistrationCountryOptionsMeArgs defaults) {
            $ = new TaxRegistrationCountryOptionsMeArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param standard Options for the standard registration.
         * 
         * @return builder
         * 
         */
        public Builder standard(@Nullable Output<TaxRegistrationCountryOptionsMeStandardArgs> standard) {
            $.standard = standard;
            return this;
        }

        /**
         * @param standard Options for the standard registration.
         * 
         * @return builder
         * 
         */
        public Builder standard(TaxRegistrationCountryOptionsMeStandardArgs standard) {
            return standard(Output.of(standard));
        }

        /**
         * @param type Type of registration in &lt;span pulumi-lang-nodejs=&#34;`country`&#34; pulumi-lang-dotnet=&#34;`Country`&#34; pulumi-lang-go=&#34;`country`&#34; pulumi-lang-python=&#34;`country`&#34; pulumi-lang-yaml=&#34;`country`&#34; pulumi-lang-java=&#34;`country`&#34; pulumi-lang-hcl=&#34;`country`&#34;&gt;`country`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Type of registration in &lt;span pulumi-lang-nodejs=&#34;`country`&#34; pulumi-lang-dotnet=&#34;`Country`&#34; pulumi-lang-go=&#34;`country`&#34; pulumi-lang-python=&#34;`country`&#34; pulumi-lang-yaml=&#34;`country`&#34; pulumi-lang-java=&#34;`country`&#34; pulumi-lang-hcl=&#34;`country`&#34;&gt;`country`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public TaxRegistrationCountryOptionsMeArgs build() {
            if ($.type == null) {
                throw new MissingRequiredPropertyException("TaxRegistrationCountryOptionsMeArgs", "type");
            }
            return $;
        }
    }

}
