// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TaxRegistrationCountryOptionsSgStandardArgs extends com.pulumi.resources.ResourceArgs {

    public static final TaxRegistrationCountryOptionsSgStandardArgs Empty = new TaxRegistrationCountryOptionsSgStandardArgs();

    /**
     * Place of supply scheme used in an Default standard registration.
     * 
     */
    @Import(name="placeOfSupplyScheme")
    private @Nullable Output<String> placeOfSupplyScheme;

    /**
     * @return Place of supply scheme used in an Default standard registration.
     * 
     */
    public Optional<Output<String>> placeOfSupplyScheme() {
        return Optional.ofNullable(this.placeOfSupplyScheme);
    }

    private TaxRegistrationCountryOptionsSgStandardArgs() {}

    private TaxRegistrationCountryOptionsSgStandardArgs(TaxRegistrationCountryOptionsSgStandardArgs $) {
        this.placeOfSupplyScheme = $.placeOfSupplyScheme;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TaxRegistrationCountryOptionsSgStandardArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TaxRegistrationCountryOptionsSgStandardArgs $;

        public Builder() {
            $ = new TaxRegistrationCountryOptionsSgStandardArgs();
        }

        public Builder(TaxRegistrationCountryOptionsSgStandardArgs defaults) {
            $ = new TaxRegistrationCountryOptionsSgStandardArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param placeOfSupplyScheme Place of supply scheme used in an Default standard registration.
         * 
         * @return builder
         * 
         */
        public Builder placeOfSupplyScheme(@Nullable Output<String> placeOfSupplyScheme) {
            $.placeOfSupplyScheme = placeOfSupplyScheme;
            return this;
        }

        /**
         * @param placeOfSupplyScheme Place of supply scheme used in an Default standard registration.
         * 
         * @return builder
         * 
         */
        public Builder placeOfSupplyScheme(String placeOfSupplyScheme) {
            return placeOfSupplyScheme(Output.of(placeOfSupplyScheme));
        }

        public TaxRegistrationCountryOptionsSgStandardArgs build() {
            return $;
        }
    }

}
