// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.stripe.inputs.TerminalReaderActionSetReaderDisplayCartArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TerminalReaderActionSetReaderDisplayArgs extends com.pulumi.resources.ResourceArgs {

    public static final TerminalReaderActionSetReaderDisplayArgs Empty = new TerminalReaderActionSetReaderDisplayArgs();

    /**
     * Cart object to be displayed by the reader, including line items, amounts, and currency.
     * 
     */
    @Import(name="cart")
    private @Nullable Output<TerminalReaderActionSetReaderDisplayCartArgs> cart;

    /**
     * @return Cart object to be displayed by the reader, including line items, amounts, and currency.
     * 
     */
    public Optional<Output<TerminalReaderActionSetReaderDisplayCartArgs>> cart() {
        return Optional.ofNullable(this.cart);
    }

    /**
     * Type of information to be displayed by the reader. Only &lt;span pulumi-lang-nodejs=&#34;`cart`&#34; pulumi-lang-dotnet=&#34;`Cart`&#34; pulumi-lang-go=&#34;`cart`&#34; pulumi-lang-python=&#34;`cart`&#34; pulumi-lang-yaml=&#34;`cart`&#34; pulumi-lang-java=&#34;`cart`&#34; pulumi-lang-hcl=&#34;`cart`&#34;&gt;`cart`&lt;/span&gt; is currently supported.
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return Type of information to be displayed by the reader. Only &lt;span pulumi-lang-nodejs=&#34;`cart`&#34; pulumi-lang-dotnet=&#34;`Cart`&#34; pulumi-lang-go=&#34;`cart`&#34; pulumi-lang-python=&#34;`cart`&#34; pulumi-lang-yaml=&#34;`cart`&#34; pulumi-lang-java=&#34;`cart`&#34; pulumi-lang-hcl=&#34;`cart`&#34;&gt;`cart`&lt;/span&gt; is currently supported.
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private TerminalReaderActionSetReaderDisplayArgs() {}

    private TerminalReaderActionSetReaderDisplayArgs(TerminalReaderActionSetReaderDisplayArgs $) {
        this.cart = $.cart;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TerminalReaderActionSetReaderDisplayArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TerminalReaderActionSetReaderDisplayArgs $;

        public Builder() {
            $ = new TerminalReaderActionSetReaderDisplayArgs();
        }

        public Builder(TerminalReaderActionSetReaderDisplayArgs defaults) {
            $ = new TerminalReaderActionSetReaderDisplayArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param cart Cart object to be displayed by the reader, including line items, amounts, and currency.
         * 
         * @return builder
         * 
         */
        public Builder cart(@Nullable Output<TerminalReaderActionSetReaderDisplayCartArgs> cart) {
            $.cart = cart;
            return this;
        }

        /**
         * @param cart Cart object to be displayed by the reader, including line items, amounts, and currency.
         * 
         * @return builder
         * 
         */
        public Builder cart(TerminalReaderActionSetReaderDisplayCartArgs cart) {
            return cart(Output.of(cart));
        }

        /**
         * @param type Type of information to be displayed by the reader. Only &lt;span pulumi-lang-nodejs=&#34;`cart`&#34; pulumi-lang-dotnet=&#34;`Cart`&#34; pulumi-lang-go=&#34;`cart`&#34; pulumi-lang-python=&#34;`cart`&#34; pulumi-lang-yaml=&#34;`cart`&#34; pulumi-lang-java=&#34;`cart`&#34; pulumi-lang-hcl=&#34;`cart`&#34;&gt;`cart`&lt;/span&gt; is currently supported.
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Type of information to be displayed by the reader. Only &lt;span pulumi-lang-nodejs=&#34;`cart`&#34; pulumi-lang-dotnet=&#34;`Cart`&#34; pulumi-lang-go=&#34;`cart`&#34; pulumi-lang-python=&#34;`cart`&#34; pulumi-lang-yaml=&#34;`cart`&#34; pulumi-lang-java=&#34;`cart`&#34; pulumi-lang-hcl=&#34;`cart`&#34;&gt;`cart`&lt;/span&gt; is currently supported.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public TerminalReaderActionSetReaderDisplayArgs build() {
            return $;
        }
    }

}
