// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TerminalConfigurationVerifoneV660pArgs extends com.pulumi.resources.ResourceArgs {

    public static final TerminalConfigurationVerifoneV660pArgs Empty = new TerminalConfigurationVerifoneV660pArgs();

    /**
     * A File ID representing an image to display on the reader
     * 
     */
    @Import(name="splashscreen")
    private @Nullable Output<String> splashscreen;

    /**
     * @return A File ID representing an image to display on the reader
     * 
     */
    public Optional<Output<String>> splashscreen() {
        return Optional.ofNullable(this.splashscreen);
    }

    private TerminalConfigurationVerifoneV660pArgs() {}

    private TerminalConfigurationVerifoneV660pArgs(TerminalConfigurationVerifoneV660pArgs $) {
        this.splashscreen = $.splashscreen;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TerminalConfigurationVerifoneV660pArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TerminalConfigurationVerifoneV660pArgs $;

        public Builder() {
            $ = new TerminalConfigurationVerifoneV660pArgs();
        }

        public Builder(TerminalConfigurationVerifoneV660pArgs defaults) {
            $ = new TerminalConfigurationVerifoneV660pArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param splashscreen A File ID representing an image to display on the reader
         * 
         * @return builder
         * 
         */
        public Builder splashscreen(@Nullable Output<String> splashscreen) {
            $.splashscreen = splashscreen;
            return this;
        }

        /**
         * @param splashscreen A File ID representing an image to display on the reader
         * 
         * @return builder
         * 
         */
        public Builder splashscreen(String splashscreen) {
            return splashscreen(Output.of(splashscreen));
        }

        public TerminalConfigurationVerifoneV660pArgs build() {
            return $;
        }
    }

}
