// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TerminalReaderActionConfirmPaymentIntentConfirmConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final TerminalReaderActionConfirmPaymentIntentConfirmConfigArgs Empty = new TerminalReaderActionConfirmPaymentIntentConfirmConfigArgs();

    /**
     * If the customer doesn&#39;t abandon authenticating the payment, they&#39;re redirected to this URL after completion.
     * 
     */
    @Import(name="returnUrl")
    private @Nullable Output<String> returnUrl;

    /**
     * @return If the customer doesn&#39;t abandon authenticating the payment, they&#39;re redirected to this URL after completion.
     * 
     */
    public Optional<Output<String>> returnUrl() {
        return Optional.ofNullable(this.returnUrl);
    }

    private TerminalReaderActionConfirmPaymentIntentConfirmConfigArgs() {}

    private TerminalReaderActionConfirmPaymentIntentConfirmConfigArgs(TerminalReaderActionConfirmPaymentIntentConfirmConfigArgs $) {
        this.returnUrl = $.returnUrl;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TerminalReaderActionConfirmPaymentIntentConfirmConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TerminalReaderActionConfirmPaymentIntentConfirmConfigArgs $;

        public Builder() {
            $ = new TerminalReaderActionConfirmPaymentIntentConfirmConfigArgs();
        }

        public Builder(TerminalReaderActionConfirmPaymentIntentConfirmConfigArgs defaults) {
            $ = new TerminalReaderActionConfirmPaymentIntentConfirmConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param returnUrl If the customer doesn&#39;t abandon authenticating the payment, they&#39;re redirected to this URL after completion.
         * 
         * @return builder
         * 
         */
        public Builder returnUrl(@Nullable Output<String> returnUrl) {
            $.returnUrl = returnUrl;
            return this;
        }

        /**
         * @param returnUrl If the customer doesn&#39;t abandon authenticating the payment, they&#39;re redirected to this URL after completion.
         * 
         * @return builder
         * 
         */
        public Builder returnUrl(String returnUrl) {
            return returnUrl(Output.of(returnUrl));
        }

        public TerminalReaderActionConfirmPaymentIntentConfirmConfigArgs build() {
            return $;
        }
    }

}
