// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TerminalConfigurationWifiEnterpriseEapPeapArgs extends com.pulumi.resources.ResourceArgs {

    public static final TerminalConfigurationWifiEnterpriseEapPeapArgs Empty = new TerminalConfigurationWifiEnterpriseEapPeapArgs();

    /**
     * A File ID representing a PEM file containing the server certificate
     * 
     */
    @Import(name="caCertificateFile")
    private @Nullable Output<String> caCertificateFile;

    /**
     * @return A File ID representing a PEM file containing the server certificate
     * 
     */
    public Optional<Output<String>> caCertificateFile() {
        return Optional.ofNullable(this.caCertificateFile);
    }

    /**
     * Password for connecting to the WiFi network
     * 
     */
    @Import(name="password", required=true)
    private Output<String> password;

    /**
     * @return Password for connecting to the WiFi network
     * 
     */
    public Output<String> password() {
        return this.password;
    }

    /**
     * Name of the WiFi network
     * 
     */
    @Import(name="ssid", required=true)
    private Output<String> ssid;

    /**
     * @return Name of the WiFi network
     * 
     */
    public Output<String> ssid() {
        return this.ssid;
    }

    /**
     * Username for connecting to the WiFi network
     * 
     */
    @Import(name="username", required=true)
    private Output<String> username;

    /**
     * @return Username for connecting to the WiFi network
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    private TerminalConfigurationWifiEnterpriseEapPeapArgs() {}

    private TerminalConfigurationWifiEnterpriseEapPeapArgs(TerminalConfigurationWifiEnterpriseEapPeapArgs $) {
        this.caCertificateFile = $.caCertificateFile;
        this.password = $.password;
        this.ssid = $.ssid;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TerminalConfigurationWifiEnterpriseEapPeapArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TerminalConfigurationWifiEnterpriseEapPeapArgs $;

        public Builder() {
            $ = new TerminalConfigurationWifiEnterpriseEapPeapArgs();
        }

        public Builder(TerminalConfigurationWifiEnterpriseEapPeapArgs defaults) {
            $ = new TerminalConfigurationWifiEnterpriseEapPeapArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param caCertificateFile A File ID representing a PEM file containing the server certificate
         * 
         * @return builder
         * 
         */
        public Builder caCertificateFile(@Nullable Output<String> caCertificateFile) {
            $.caCertificateFile = caCertificateFile;
            return this;
        }

        /**
         * @param caCertificateFile A File ID representing a PEM file containing the server certificate
         * 
         * @return builder
         * 
         */
        public Builder caCertificateFile(String caCertificateFile) {
            return caCertificateFile(Output.of(caCertificateFile));
        }

        /**
         * @param password Password for connecting to the WiFi network
         * 
         * @return builder
         * 
         */
        public Builder password(Output<String> password) {
            $.password = password;
            return this;
        }

        /**
         * @param password Password for connecting to the WiFi network
         * 
         * @return builder
         * 
         */
        public Builder password(String password) {
            return password(Output.of(password));
        }

        /**
         * @param ssid Name of the WiFi network
         * 
         * @return builder
         * 
         */
        public Builder ssid(Output<String> ssid) {
            $.ssid = ssid;
            return this;
        }

        /**
         * @param ssid Name of the WiFi network
         * 
         * @return builder
         * 
         */
        public Builder ssid(String ssid) {
            return ssid(Output.of(ssid));
        }

        /**
         * @param username Username for connecting to the WiFi network
         * 
         * @return builder
         * 
         */
        public Builder username(Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username Username for connecting to the WiFi network
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public TerminalConfigurationWifiEnterpriseEapPeapArgs build() {
            if ($.password == null) {
                throw new MissingRequiredPropertyException("TerminalConfigurationWifiEnterpriseEapPeapArgs", "password");
            }
            if ($.ssid == null) {
                throw new MissingRequiredPropertyException("TerminalConfigurationWifiEnterpriseEapPeapArgs", "ssid");
            }
            if ($.username == null) {
                throw new MissingRequiredPropertyException("TerminalConfigurationWifiEnterpriseEapPeapArgs", "username");
            }
            return $;
        }
    }

}
