// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.stripe.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.stripe.inputs.V2BillingRateCardRateTierArgs;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class V2BillingRateCardRateState extends com.pulumi.resources.ResourceArgs {

    public static final V2BillingRateCardRateState Empty = new V2BillingRateCardRateState();

    /**
     * Set of [key-value pairs](https://www.terraform.io/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * 
     */
    @Import(name="metadata")
    private @Nullable Output<Map<String,String>> metadata;

    /**
     * @return Set of [key-value pairs](https://www.terraform.io/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * 
     */
    public Optional<Output<Map<String,String>>> metadata() {
        return Optional.ofNullable(this.metadata);
    }

    /**
     * The Metered Item that this rate binds to.
     * 
     */
    @Import(name="meteredItem")
    private @Nullable Output<String> meteredItem;

    /**
     * @return The Metered Item that this rate binds to.
     * 
     */
    public Optional<Output<String>> meteredItem() {
        return Optional.ofNullable(this.meteredItem);
    }

    /**
     * The ID of the Rate Card it belongs to.
     * 
     */
    @Import(name="rateCard")
    private @Nullable Output<String> rateCard;

    /**
     * @return The ID of the Rate Card it belongs to.
     * 
     */
    public Optional<Output<String>> rateCard() {
        return Optional.ofNullable(this.rateCard);
    }

    /**
     * Path parameter: rate_card_id
     * 
     */
    @Import(name="rateCardId")
    private @Nullable Output<String> rateCardId;

    /**
     * @return Path parameter: rate_card_id
     * 
     */
    public Optional<Output<String>> rateCardId() {
        return Optional.ofNullable(this.rateCardId);
    }

    /**
     * The ID of the Rate Card Version it was created on.
     * 
     */
    @Import(name="rateCardVersion")
    private @Nullable Output<String> rateCardVersion;

    /**
     * @return The ID of the Rate Card Version it was created on.
     * 
     */
    public Optional<Output<String>> rateCardVersion() {
        return Optional.ofNullable(this.rateCardVersion);
    }

    /**
     * Defines whether the tiered price should be graduated or volume-based. In volume-based tiering, the maximum quantity within a period determines the per-unit price. In graduated tiering, the pricing changes as the quantity grows into new tiers. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
     * 
     */
    @Import(name="tieringMode")
    private @Nullable Output<String> tieringMode;

    /**
     * @return Defines whether the tiered price should be graduated or volume-based. In volume-based tiering, the maximum quantity within a period determines the per-unit price. In graduated tiering, the pricing changes as the quantity grows into new tiers. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
     * 
     */
    public Optional<Output<String>> tieringMode() {
        return Optional.ofNullable(this.tieringMode);
    }

    /**
     * Each element represents a pricing tier. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
     * 
     */
    @Import(name="tiers")
    private @Nullable Output<List<V2BillingRateCardRateTierArgs>> tiers;

    /**
     * @return Each element represents a pricing tier. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
     * 
     */
    public Optional<Output<List<V2BillingRateCardRateTierArgs>>> tiers() {
        return Optional.ofNullable(this.tiers);
    }

    /**
     * The per-unit amount to be charged, represented as a decimal string in minor currency units with at most 12 decimal places. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
     * 
     */
    @Import(name="unitAmount")
    private @Nullable Output<String> unitAmount;

    /**
     * @return The per-unit amount to be charged, represented as a decimal string in minor currency units with at most 12 decimal places. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
     * 
     */
    public Optional<Output<String>> unitAmount() {
        return Optional.ofNullable(this.unitAmount);
    }

    private V2BillingRateCardRateState() {}

    private V2BillingRateCardRateState(V2BillingRateCardRateState $) {
        this.metadata = $.metadata;
        this.meteredItem = $.meteredItem;
        this.rateCard = $.rateCard;
        this.rateCardId = $.rateCardId;
        this.rateCardVersion = $.rateCardVersion;
        this.tieringMode = $.tieringMode;
        this.tiers = $.tiers;
        this.unitAmount = $.unitAmount;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(V2BillingRateCardRateState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private V2BillingRateCardRateState $;

        public Builder() {
            $ = new V2BillingRateCardRateState();
        }

        public Builder(V2BillingRateCardRateState defaults) {
            $ = new V2BillingRateCardRateState(Objects.requireNonNull(defaults));
        }

        /**
         * @param metadata Set of [key-value pairs](https://www.terraform.io/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
         * 
         * @return builder
         * 
         */
        public Builder metadata(@Nullable Output<Map<String,String>> metadata) {
            $.metadata = metadata;
            return this;
        }

        /**
         * @param metadata Set of [key-value pairs](https://www.terraform.io/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
         * 
         * @return builder
         * 
         */
        public Builder metadata(Map<String,String> metadata) {
            return metadata(Output.of(metadata));
        }

        /**
         * @param meteredItem The Metered Item that this rate binds to.
         * 
         * @return builder
         * 
         */
        public Builder meteredItem(@Nullable Output<String> meteredItem) {
            $.meteredItem = meteredItem;
            return this;
        }

        /**
         * @param meteredItem The Metered Item that this rate binds to.
         * 
         * @return builder
         * 
         */
        public Builder meteredItem(String meteredItem) {
            return meteredItem(Output.of(meteredItem));
        }

        /**
         * @param rateCard The ID of the Rate Card it belongs to.
         * 
         * @return builder
         * 
         */
        public Builder rateCard(@Nullable Output<String> rateCard) {
            $.rateCard = rateCard;
            return this;
        }

        /**
         * @param rateCard The ID of the Rate Card it belongs to.
         * 
         * @return builder
         * 
         */
        public Builder rateCard(String rateCard) {
            return rateCard(Output.of(rateCard));
        }

        /**
         * @param rateCardId Path parameter: rate_card_id
         * 
         * @return builder
         * 
         */
        public Builder rateCardId(@Nullable Output<String> rateCardId) {
            $.rateCardId = rateCardId;
            return this;
        }

        /**
         * @param rateCardId Path parameter: rate_card_id
         * 
         * @return builder
         * 
         */
        public Builder rateCardId(String rateCardId) {
            return rateCardId(Output.of(rateCardId));
        }

        /**
         * @param rateCardVersion The ID of the Rate Card Version it was created on.
         * 
         * @return builder
         * 
         */
        public Builder rateCardVersion(@Nullable Output<String> rateCardVersion) {
            $.rateCardVersion = rateCardVersion;
            return this;
        }

        /**
         * @param rateCardVersion The ID of the Rate Card Version it was created on.
         * 
         * @return builder
         * 
         */
        public Builder rateCardVersion(String rateCardVersion) {
            return rateCardVersion(Output.of(rateCardVersion));
        }

        /**
         * @param tieringMode Defines whether the tiered price should be graduated or volume-based. In volume-based tiering, the maximum quantity within a period determines the per-unit price. In graduated tiering, the pricing changes as the quantity grows into new tiers. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
         * 
         * @return builder
         * 
         */
        public Builder tieringMode(@Nullable Output<String> tieringMode) {
            $.tieringMode = tieringMode;
            return this;
        }

        /**
         * @param tieringMode Defines whether the tiered price should be graduated or volume-based. In volume-based tiering, the maximum quantity within a period determines the per-unit price. In graduated tiering, the pricing changes as the quantity grows into new tiers. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
         * 
         * @return builder
         * 
         */
        public Builder tieringMode(String tieringMode) {
            return tieringMode(Output.of(tieringMode));
        }

        /**
         * @param tiers Each element represents a pricing tier. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
         * 
         * @return builder
         * 
         */
        public Builder tiers(@Nullable Output<List<V2BillingRateCardRateTierArgs>> tiers) {
            $.tiers = tiers;
            return this;
        }

        /**
         * @param tiers Each element represents a pricing tier. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
         * 
         * @return builder
         * 
         */
        public Builder tiers(List<V2BillingRateCardRateTierArgs> tiers) {
            return tiers(Output.of(tiers));
        }

        /**
         * @param tiers Each element represents a pricing tier. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
         * 
         * @return builder
         * 
         */
        public Builder tiers(V2BillingRateCardRateTierArgs... tiers) {
            return tiers(List.of(tiers));
        }

        /**
         * @param unitAmount The per-unit amount to be charged, represented as a decimal string in minor currency units with at most 12 decimal places. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
         * 
         * @return builder
         * 
         */
        public Builder unitAmount(@Nullable Output<String> unitAmount) {
            $.unitAmount = unitAmount;
            return this;
        }

        /**
         * @param unitAmount The per-unit amount to be charged, represented as a decimal string in minor currency units with at most 12 decimal places. One of &lt;span pulumi-lang-nodejs=&#34;`unitAmount`&#34; pulumi-lang-dotnet=&#34;`UnitAmount`&#34; pulumi-lang-go=&#34;`unitAmount`&#34; pulumi-lang-python=&#34;`unit_amount`&#34; pulumi-lang-yaml=&#34;`unitAmount`&#34; pulumi-lang-java=&#34;`unitAmount`&#34; pulumi-lang-hcl=&#34;`unit_amount`&#34;&gt;`unitAmount`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`tiers`&#34; pulumi-lang-dotnet=&#34;`Tiers`&#34; pulumi-lang-go=&#34;`tiers`&#34; pulumi-lang-python=&#34;`tiers`&#34; pulumi-lang-yaml=&#34;`tiers`&#34; pulumi-lang-java=&#34;`tiers`&#34; pulumi-lang-hcl=&#34;`tiers`&#34;&gt;`tiers`&lt;/span&gt;, or &lt;span pulumi-lang-nodejs=&#34;`customPricingUnitAmount`&#34; pulumi-lang-dotnet=&#34;`CustomPricingUnitAmount`&#34; pulumi-lang-go=&#34;`customPricingUnitAmount`&#34; pulumi-lang-python=&#34;`custom_pricing_unit_amount`&#34; pulumi-lang-yaml=&#34;`customPricingUnitAmount`&#34; pulumi-lang-java=&#34;`customPricingUnitAmount`&#34; pulumi-lang-hcl=&#34;`custom_pricing_unit_amount`&#34;&gt;`customPricingUnitAmount`&lt;/span&gt; is required.
         * 
         * @return builder
         * 
         */
        public Builder unitAmount(String unitAmount) {
            return unitAmount(Output.of(unitAmount));
        }

        public V2BillingRateCardRateState build() {
            return $;
        }
    }

}
